load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "picker",
    srcs = [
        "item.go",
        "model.go",
        "picker.go",
        "styles.go",
    ],
    importpath = "github.com/stigmer/stigmer/client-apps/cli/pkg/picker",
    visibility = ["//visibility:public"],
    deps = [
        "@land_charm_bubbles_v2//textinput",
        "@land_charm_bubbletea_v2//:bubbletea",
        "@land_charm_lipgloss_v2//:lipgloss",
        "@org_golang_x_term//:term",
    ],
)
