load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "apiresourcekind",
    srcs = [
        "api_resource_group.pb.go",
        "api_resource_kind.pb.go",
        "authorization_config.pb.go",
    ],
    importpath = "github.com/stigmer/stigmer/mcp-server/proto/ai/stigmer/commons/apiresource/apiresourcekind",
    visibility = ["//visibility:public"],
    deps = [
        "//mcp-server/proto/ai/stigmer/iam/v1:iam",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_google_protobuf//types/descriptorpb",
    ],
)
