// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/agentexecution/v1/io.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.agentexecution.v1;

@com.google.protobuf.Generated
public interface GetArtifactContentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.agentic.agentexecution.v1.GetArtifactContentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the agent execution that produced the artifact.
   *
   * Used for authorization (can_view check) and storage_key validation.
   *
   * Format: "aex_{ulid}"
   * Example: "aex_abc123xyz456"
   *
   * Validation: Required, minimum 1 character
   * </pre>
   *
   * <code>string execution_id = 1 [json_name = "executionId", (.buf.validate.field) = { ... }</code>
   * @return The executionId.
   */
  java.lang.String getExecutionId();
  /**
   * <pre>
   * ID of the agent execution that produced the artifact.
   *
   * Used for authorization (can_view check) and storage_key validation.
   *
   * Format: "aex_{ulid}"
   * Example: "aex_abc123xyz456"
   *
   * Validation: Required, minimum 1 character
   * </pre>
   *
   * <code>string execution_id = 1 [json_name = "executionId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for executionId.
   */
  com.google.protobuf.ByteString
      getExecutionIdBytes();

  /**
   * <pre>
   * Storage key of the artifact to read.
   *
   * Must be an artifact from the specified execution. The storage_key
   * is validated to start with "artifacts/{execution_id}/" to prevent
   * access to other executions' artifacts.
   *
   * Obtain this value from ExecutionArtifact.storage_key in the execution status.
   *
   * Format: "artifacts/{execution_id}/{filename}"
   * Example: "artifacts/aex_abc123xyz456/pr-review-agent.yaml"
   *
   * Validation: Required, minimum 1 character
   * </pre>
   *
   * <code>string storage_key = 2 [json_name = "storageKey", (.buf.validate.field) = { ... }</code>
   * @return The storageKey.
   */
  java.lang.String getStorageKey();
  /**
   * <pre>
   * Storage key of the artifact to read.
   *
   * Must be an artifact from the specified execution. The storage_key
   * is validated to start with "artifacts/{execution_id}/" to prevent
   * access to other executions' artifacts.
   *
   * Obtain this value from ExecutionArtifact.storage_key in the execution status.
   *
   * Format: "artifacts/{execution_id}/{filename}"
   * Example: "artifacts/aex_abc123xyz456/pr-review-agent.yaml"
   *
   * Validation: Required, minimum 1 character
   * </pre>
   *
   * <code>string storage_key = 2 [json_name = "storageKey", (.buf.validate.field) = { ... }</code>
   * @return The bytes for storageKey.
   */
  com.google.protobuf.ByteString
      getStorageKeyBytes();

  /**
   * <pre>
   * Maximum number of bytes to return.
   *
   * If the artifact is larger than this limit, the response will contain
   * the first max_bytes of content with truncated=true.
   *
   * When 0 or unset, the server applies a default limit (512 KB).
   * The server may also enforce a hard upper bound regardless of this value.
   *
   * Example: 524288 (512 KB)
   * </pre>
   *
   * <code>int64 max_bytes = 3 [json_name = "maxBytes"];</code>
   * @return The maxBytes.
   */
  long getMaxBytes();
}
