// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/agentexecution/v1/spec.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.agentexecution.v1;

@com.google.protobuf.Generated
public final class SpecProto extends com.google.protobuf.GeneratedFile {
  private SpecProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "SpecProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_RuntimeEnvEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_RuntimeEnvEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_agentic_agentexecution_v1_ExecutionConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_agentic_agentexecution_v1_ExecutionConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_agentic_agentexecution_v1_ContextManagementConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_agentic_agentexecution_v1_ContextManagementConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_agentic_agentexecution_v1_Attachment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_agentic_agentexecution_v1_Attachment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_agentic_agentexecution_v1_ConversationCatchup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_agentic_agentexecution_v1_ConversationCatchup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_agentic_agentexecution_v1_DeclaredPreferences_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_agentic_agentexecution_v1_DeclaredPreferences_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_agentic_agentexecution_v1_RecalledMemories_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_agentic_agentexecution_v1_RecalledMemories_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_agentic_agentexecution_v1_RecalledMemoryFact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_agentic_agentexecution_v1_RecalledMemoryFact_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/ai/stigmer/agentic/agentexecution/v1/s" +
      "pec.proto\022$ai.stigmer.agentic.agentexecu" +
      "tion.v1\032/ai/stigmer/agentic/agentexecuti" +
      "on/v1/enum.proto\0321ai/stigmer/agentic/exe" +
      "cutioncontext/v1/spec.proto\032(ai/stigmer/" +
      "agentic/session/v1/spec.proto\032\033buf/valid" +
      "ate/validate.proto\032\034google/protobuf/stru" +
      "ct.proto\032\037google/protobuf/timestamp.prot" +
      "o\"\353\014\n\022AgentExecutionSpec\022\035\n\nsession_id\030\001" +
      " \001(\tR\tsessionId\022\031\n\010agent_id\030\002 \001(\tR\007agent" +
      "Id\022M\n\014session_spec\030\r \001(\0132*.ai.stigmer.ag" +
      "entic.session.v1.SessionSpecR\013sessionSpe" +
      "c\022!\n\007message\030\003 \001(\tB\007\272H\004r\002\020\001R\007message\022`\n\020" +
      "execution_config\030\004 \001(\01325.ai.stigmer.agen" +
      "tic.agentexecution.v1.ExecutionConfigR\017e" +
      "xecutionConfig\022i\n\013runtime_env\030\005 \003(\0132H.ai" +
      ".stigmer.agentic.agentexecution.v1.Agent" +
      "ExecutionSpec.RuntimeEnvEntryR\nruntimeEn" +
      "v\022%\n\016callback_token\030\006 \001(\014R\rcallbackToken" +
      "\022(\n\020auto_approve_all\030\007 \001(\010R\016autoApproveA" +
      "ll\022,\n\022parent_workflow_id\030\010 \001(\tR\020parentWo" +
      "rkflowId\022R\n\013attachments\030\t \003(\01320.ai.stigm" +
      "er.agentic.agentexecution.v1.AttachmentR" +
      "\013attachments\022.\n\023workspace_file_refs\030\n \003(" +
      "\tR\021workspaceFileRefs\022.\n\023activity_task_qu" +
      "eue\030\013 \001(\tR\021activityTaskQueue\0226\n\027supersed" +
      "es_execution_id\030\014 \001(\tR\025supersedesExecuti" +
      "onId\022l\n\024conversation_catchup\030\016 \001(\01329.ai." +
      "stigmer.agentic.agentexecution.v1.Conver" +
      "sationCatchupR\023conversationCatchup\022l\n\024de" +
      "clared_preferences\030\017 \001(\01329.ai.stigmer.ag" +
      "entic.agentexecution.v1.DeclaredPreferen" +
      "cesR\023declaredPreferences\022c\n\021recalled_mem" +
      "ories\030\020 \001(\01326.ai.stigmer.agentic.agentex" +
      "ecution.v1.RecalledMemoriesR\020recalledMem" +
      "ories\032u\n\017RuntimeEnvEntry\022\020\n\003key\030\001 \001(\tR\003k" +
      "ey\022L\n\005value\030\002 \001(\01326.ai.stigmer.agentic.e" +
      "xecutioncontext.v1.ExecutionValueR\005value" +
      ":\0028\001:\270\003\272H\264\003\032\313\001\n!agent_execution.session_" +
      "exclusive\022rsession_id and session_spec a" +
      "re mutually exclusive \342\200\224 reference an e" +
      "xisting session or define a new one, not" +
      " both\0322!(this.session_id != \'\' && has(th" +
      "is.session_spec))\032\343\001\n*agent_execution.se" +
      "ssion_spec_harness_state\022psession_spec.h" +
      "arness_state_id must be empty \342\200\224 harnes" +
      "s state is created by the runner after t" +
      "he first execution\032C!has(this.session_sp" +
      "ec) || this.session_spec.harness_state_i" +
      "d == \'\'\"\250\006\n\017ExecutionConfig\022\035\n\nmodel_nam" +
      "e\030\001 \001(\tR\tmodelName\022l\n\022context_management" +
      "\030\002 \001(\0132=.ai.stigmer.agentic.agentexecuti" +
      "on.v1.ContextManagementConfigR\021contextMa" +
      "nagement\022&\n\017max_tool_rounds\030\003 \001(\005R\rmaxTo" +
      "olRounds\0221\n\025max_tool_result_chars\030\004 \001(\005R" +
      "\022maxToolResultChars\022 \n\014max_cost_usd\030\005 \001(" +
      "\001R\nmaxCostUsd\022j\n\020interaction_mode\030\006 \001(\0162" +
      "5.ai.stigmer.agentic.agentexecution.v1.I" +
      "nteractionModeB\010\272H\005\202\001\002\020\001R\017interactionMod" +
      "e\022Q\n\030structured_output_schema\030\007 \001(\0132\027.go" +
      "ogle.protobuf.StructR\026structuredOutputSc" +
      "hema\022&\n\017build_from_plan\030\010 \001(\010R\rbuildFrom" +
      "Plan\022a\n\rapproval_mode\030\t \001(\01622.ai.stigmer" +
      ".agentic.agentexecution.v1.ApprovalModeB" +
      "\010\272H\005\202\001\002\020\001R\014approvalMode\022^\n\014service_tier\030" +
      "\n \001(\01621.ai.stigmer.agentic.agentexecutio" +
      "n.v1.ServiceTierB\010\272H\005\202\001\002\020\001R\013serviceTier\022" +
      "a\n\rthinking_mode\030\013 \001(\01622.ai.stigmer.agen" +
      "tic.agentexecution.v1.ThinkingModeB\010\272H\005\202" +
      "\001\002\020\001R\014thinkingMode\"\314\001\n\027ContextManagement" +
      "Config\0223\n\025disable_summarization\030\001 \001(\010R\024d" +
      "isableSummarization\022A\n\030custom_trigger_th" +
      "reshold\030\002 \001(\005B\007\272H\004\032\002(\000R\026customTriggerThr" +
      "eshold\0229\n\024custom_target_tokens\030\003 \001(\005B\007\272H" +
      "\004\032\002(\000R\022customTargetTokens\"\226\003\n\nAttachment" +
      "\022\342\001\n\010filename\030\001 \001(\tB\305\001\272H\301\001r\002\020\001\272\001\271\001\n\033atta" +
      "chment.filename.no_path\022Nfilename must b" +
      "e a bare filename without path separator" +
      "s or traversal segments\032J!this.contains(" +
      "\'/\') && !this.contains(\'\\\\\') && this != " +
      "\'.\' && this != \'..\'R\010filename\022(\n\013storage" +
      "_key\030\002 \001(\tB\007\272H\004r\002\020\001R\nstorageKey\022\035\n\nmount" +
      "_path\030\003 \001(\tR\tmountPath\022!\n\014content_type\030\004" +
      " \001(\tR\013contentType\022\030\n\007extract\030\005 \001(\010R\007extr" +
      "act\022\035\n\nlocal_path\030\006 \001(\tR\tlocalPath\"h\n\023Co" +
      "nversationCatchup\022\026\n\006digest\030\001 \001(\tR\006diges" +
      "t\0229\n\nwindow_end\030\002 \001(\0132\032.google.protobuf." +
      "TimestampR\twindowEnd\"Y\n\023DeclaredPreferen" +
      "ces\022\037\n\013org_context\030\001 \001(\tR\norgContext\022!\n\014" +
      "user_context\030\002 \001(\tR\013userContext\"|\n\020Recal" +
      "ledMemories\022\030\n\007enabled\030\001 \001(\010R\007enabled\022N\n" +
      "\005facts\030\002 \003(\01328.ai.stigmer.agentic.agente" +
      "xecution.v1.RecalledMemoryFactR\005facts\"K\n" +
      "\022RecalledMemoryFact\022\033\n\tmemory_id\030\001 \001(\tR\010" +
      "memoryId\022\030\n\007content\030\002 \001(\tR\007contentB\300\001B\tS" +
      "pecProtoP\001\242\002\004ASAA\252\002$Ai.Stigmer.Agentic.A" +
      "gentexecution.V1\312\002$Ai\\Stigmer\\Agentic\\Ag" +
      "entexecution\\V1\342\0020Ai\\Stigmer\\Agentic\\Age" +
      "ntexecution\\V1\\GPBMetadata\352\002(Ai::Stigmer" +
      "::Agentic::Agentexecution::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ai.stigmer.agentic.agentexecution.v1.EnumProto.getDescriptor(),
          ai.stigmer.agentic.executioncontext.v1.SpecProto.getDescriptor(),
          ai.stigmer.agentic.session.v1.SpecProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_descriptor,
        new java.lang.String[] { "SessionId", "AgentId", "SessionSpec", "Message", "ExecutionConfig", "RuntimeEnv", "CallbackToken", "AutoApproveAll", "ParentWorkflowId", "Attachments", "WorkspaceFileRefs", "ActivityTaskQueue", "SupersedesExecutionId", "ConversationCatchup", "DeclaredPreferences", "RecalledMemories", });
    internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_RuntimeEnvEntry_descriptor =
      internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_descriptor.getNestedType(0);
    internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_RuntimeEnvEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_agentic_agentexecution_v1_AgentExecutionSpec_RuntimeEnvEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ai_stigmer_agentic_agentexecution_v1_ExecutionConfig_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_ai_stigmer_agentic_agentexecution_v1_ExecutionConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_agentic_agentexecution_v1_ExecutionConfig_descriptor,
        new java.lang.String[] { "ModelName", "ContextManagement", "MaxToolRounds", "MaxToolResultChars", "MaxCostUsd", "InteractionMode", "StructuredOutputSchema", "BuildFromPlan", "ApprovalMode", "ServiceTier", "ThinkingMode", });
    internal_static_ai_stigmer_agentic_agentexecution_v1_ContextManagementConfig_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_ai_stigmer_agentic_agentexecution_v1_ContextManagementConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_agentic_agentexecution_v1_ContextManagementConfig_descriptor,
        new java.lang.String[] { "DisableSummarization", "CustomTriggerThreshold", "CustomTargetTokens", });
    internal_static_ai_stigmer_agentic_agentexecution_v1_Attachment_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_ai_stigmer_agentic_agentexecution_v1_Attachment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_agentic_agentexecution_v1_Attachment_descriptor,
        new java.lang.String[] { "Filename", "StorageKey", "MountPath", "ContentType", "Extract", "LocalPath", });
    internal_static_ai_stigmer_agentic_agentexecution_v1_ConversationCatchup_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_ai_stigmer_agentic_agentexecution_v1_ConversationCatchup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_agentic_agentexecution_v1_ConversationCatchup_descriptor,
        new java.lang.String[] { "Digest", "WindowEnd", });
    internal_static_ai_stigmer_agentic_agentexecution_v1_DeclaredPreferences_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_ai_stigmer_agentic_agentexecution_v1_DeclaredPreferences_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_agentic_agentexecution_v1_DeclaredPreferences_descriptor,
        new java.lang.String[] { "OrgContext", "UserContext", });
    internal_static_ai_stigmer_agentic_agentexecution_v1_RecalledMemories_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_ai_stigmer_agentic_agentexecution_v1_RecalledMemories_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_agentic_agentexecution_v1_RecalledMemories_descriptor,
        new java.lang.String[] { "Enabled", "Facts", });
    internal_static_ai_stigmer_agentic_agentexecution_v1_RecalledMemoryFact_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_ai_stigmer_agentic_agentexecution_v1_RecalledMemoryFact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_agentic_agentexecution_v1_RecalledMemoryFact_descriptor,
        new java.lang.String[] { "MemoryId", "Content", });
    descriptor.resolveAllFeaturesImmutable();
    ai.stigmer.agentic.agentexecution.v1.EnumProto.getDescriptor();
    ai.stigmer.agentic.executioncontext.v1.SpecProto.getDescriptor();
    ai.stigmer.agentic.session.v1.SpecProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    registry.add(build.buf.validate.ValidateProto.message);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
