load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "rpc",
    srcs = [
        "authorization_config.pb.go",
        "method_options.pb.go",
        "pagination.pb.go",
    ],
    importpath = "github.com/stigmer/stigmer/apis/stubs/go/ai/stigmer/commons/rpc",
    visibility = ["//visibility:public"],
    deps = [
        "//apis/stubs/go/ai/stigmer/commons/apiresource/apiresourcekind",
        "//apis/stubs/go/ai/stigmer/iam/v1:iam",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_google_protobuf//types/descriptorpb",
    ],
)
