load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "auth",
    srcs = [
        "callback.go",
        "config.go",
        "login.go",
        "pages.go",
        "whoami.go",
    ],
    importpath = "github.com/stigmer/stigmer/client-apps/cli/internal/cli/auth",
    visibility = ["//client-apps/cli:__subpackages__"],
    deps = [
        "//client-apps/cli/internal/cli/browser",
        "//client-apps/cli/internal/cli/config",
        "@com_github_pkg_errors//:errors",
        "@com_github_stigmer_stigmer_sdk_go//proto/ai/stigmer/iam/identityaccount/v1:identityaccount",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//credentials/insecure",
        "@org_golang_google_protobuf//types/known/emptypb",
        "@org_golang_x_oauth2//:oauth2",
    ],
)
