// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/billing/v1/io.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.billing.v1;

@com.google.protobuf.Generated
public interface GetBillingUsageReportInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.billing.v1.GetBillingUsageReportInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string org = 1 [json_name = "org", (.buf.validate.field) = { ... }</code>
   * @return The org.
   */
  java.lang.String getOrg();
  /**
   * <code>string org = 1 [json_name = "org", (.buf.validate.field) = { ... }</code>
   * @return The bytes for org.
   */
  com.google.protobuf.ByteString
      getOrgBytes();

  /**
   * <pre>
   * Start of the reporting period.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 2 [json_name = "startTime", (.buf.validate.field) = { ... }</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <pre>
   * Start of the reporting period.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 2 [json_name = "startTime", (.buf.validate.field) = { ... }</code>
   * @return The startTime.
   */
  com.google.protobuf.Timestamp getStartTime();
  /**
   * <pre>
   * Start of the reporting period.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 2 [json_name = "startTime", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

  /**
   * <pre>
   * End of the reporting period.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 3 [json_name = "endTime", (.buf.validate.field) = { ... }</code>
   * @return Whether the endTime field is set.
   */
  boolean hasEndTime();
  /**
   * <pre>
   * End of the reporting period.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 3 [json_name = "endTime", (.buf.validate.field) = { ... }</code>
   * @return The endTime.
   */
  com.google.protobuf.Timestamp getEndTime();
  /**
   * <pre>
   * End of the reporting period.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp end_time = 3 [json_name = "endTime", (.buf.validate.field) = { ... }</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndTimeOrBuilder();
}
