# GoReleaser configuration for Stigmer
# Builds and packages both CLI and server binaries

version: 2

before:
  hooks:
    - go mod tidy
    - make protos

builds:
  # Build stigmer CLI
  - id: stigmer-cli
    main: ./client-apps/cli
    binary: stigmer
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/stigmer/stigmer/client-apps/cli/internal/cli/version.Version={{.Version}}
      - -X github.com/stigmer/stigmer/client-apps/cli/internal/cli/version.Commit={{.Commit}}
      - -X github.com/stigmer/stigmer/client-apps/cli/internal/cli/version.Date={{.Date}}

  # Build stigmer-server
  - id: stigmer-server
    main: ./backend/services/stigmer-server/cmd/server
    binary: stigmer-server
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: stigmer-bundle
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    # Include both binaries in the archive
    builds:
      - stigmer-cli
      - stigmer-server
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

# Homebrew tap configuration
brews:
  - repository:
      owner: stigmer
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/stigmer/stigmer"
    description: "AI-powered workflow automation with local LLMs"
    license: "Apache-2.0"
    test: |
      system "#{bin}/stigmer", "--version"
      system "#{bin}/stigmer-server", "--version"
    install: |
      bin.install "stigmer"
      bin.install "stigmer-server"
    # Include both binaries
    ids:
      - stigmer-bundle

# Docker images (optional, for server deployment)
dockers:
  - image_templates:
      - "ghcr.io/stigmer/stigmer-server:{{ .Version }}"
      - "ghcr.io/stigmer/stigmer-server:latest"
    dockerfile: Dockerfile.server
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - backend/services/stigmer-server/

# Announce releases
announce:
  skip: '{{gt .Patch 0}}'  # Only announce major/minor releases
