// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/agentchannel/v1/io.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.agentchannel.v1;

@com.google.protobuf.Generated
public interface InitiateChannelInstallOutputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.agentic.agentchannel.v1.InitiateChannelInstallOutput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Provider authorization URL to redirect the installing user to
   * (for Slack: the "Add to Slack" consent screen).
   * </pre>
   *
   * <code>string authorization_url = 1 [json_name = "authorizationUrl"];</code>
   * @return The authorizationUrl.
   */
  java.lang.String getAuthorizationUrl();
  /**
   * <pre>
   * Provider authorization URL to redirect the installing user to
   * (for Slack: the "Add to Slack" consent screen).
   * </pre>
   *
   * <code>string authorization_url = 1 [json_name = "authorizationUrl"];</code>
   * @return The bytes for authorizationUrl.
   */
  com.google.protobuf.ByteString
      getAuthorizationUrlBytes();

  /**
   * <pre>
   * Single-use opaque state parameter bound to this install attempt.
   *
   * &#64;internal
   * Persisted server-side (PendingOAuthStateDocument pattern) and consumed
   * atomically by completeInstall; expired or replayed states are rejected.
   * </pre>
   *
   * <code>string state = 2 [json_name = "state"];</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <pre>
   * Single-use opaque state parameter bound to this install attempt.
   *
   * &#64;internal
   * Persisted server-side (PendingOAuthStateDocument pattern) and consumed
   * atomically by completeInstall; expired or replayed states are rejected.
   * </pre>
   *
   * <code>string state = 2 [json_name = "state"];</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();
}
