// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file ai/stigmer/agentic/agentrunner/v1/command.proto (package ai.stigmer.agentic.agentrunner.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AgentRunner } from "./api_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { AgentRunnerHeartbeatInput, AgentRunnerId } from "./io_pb.js";

/**
 * AgentRunnerCommandController handles write operations for agent runners.
 *
 * Two creation patterns are supported:
 *
 * 1. **CLI/Desktop (persistent runners)**: The client calls apply with a slug
 *    stored in ~/.stigmer/runner.json. If the runner exists, it reactivates.
 *    If not, it creates. This is the primary registration path.
 *
 * 2. **Platform (ephemeral runners)**: The execution workflow calls create
 *    with metadata label stigmer.ai/system-managed: "true". The runner is
 *    torn down via delete when the execution completes.
 *
 * The heartbeat RPC is called by the runner process on a regular interval
 * (default 30s) to report liveness and state. It is the runner's only
 * ongoing communication channel with the server.
 *
 * @generated from service ai.stigmer.agentic.agentrunner.v1.AgentRunnerCommandController
 */
export const AgentRunnerCommandController = {
  typeName: "ai.stigmer.agentic.agentrunner.v1.AgentRunnerCommandController",
  methods: {
    /**
     * Create or update an agent runner.
     *
     * @internal
     * Primary registration path for CLI/Desktop runners. The handler determines
     * whether to create or update based on whether the resource already exists
     * (resolved by org + slug). Authorization is handled in the handler.
     *
     * @generated from rpc ai.stigmer.agentic.agentrunner.v1.AgentRunnerCommandController.apply
     */
    apply: {
      name: "apply",
      I: AgentRunner,
      O: AgentRunner,
      kind: MethodKind.Unary,
    },
    /**
     * Create a new agent runner.
     *
     * @internal
     * Authorization: Caller must have can_create_agent_runner permission in the
     * organization. The server generates the task queue name (agent-runner:{id})
     * and sets the initial phase to PENDING.
     *
     * @generated from rpc ai.stigmer.agentic.agentrunner.v1.AgentRunnerCommandController.create
     */
    create: {
      name: "create",
      I: AgentRunner,
      O: AgentRunner,
      kind: MethodKind.Unary,
    },
    /**
     * Update an existing agent runner.
     *
     * @internal
     * Used for updating spec fields (e.g., description). Status fields are
     * updated via heartbeat, not via this RPC.
     *
     * @generated from rpc ai.stigmer.agentic.agentrunner.v1.AgentRunnerCommandController.update
     */
    update: {
      name: "update",
      I: AgentRunner,
      O: AgentRunner,
      kind: MethodKind.Unary,
    },
    /**
     * Delete an agent runner.
     *
     * @internal
     * For persistent runners: removes the resource and its task queue.
     * For system-managed runners: called by the execution workflow during
     * cleanup after the execution completes.
     *
     * @generated from rpc ai.stigmer.agentic.agentrunner.v1.AgentRunnerCommandController.delete
     */
    delete: {
      name: "delete",
      I: AgentRunnerId,
      O: AgentRunner,
      kind: MethodKind.Unary,
    },
    /**
     * Report runner liveness and operational state.
     *
     * Called by the runner process every 30 seconds. Updates status fields
     * (phase, last_heartbeat_at, current_executions, connection_info) without
     * modifying spec or metadata.
     *
     * If the runner is in PENDING or STOPPED phase, a heartbeat transitions it
     * to the phase reported in the input (typically READY). This enables the
     * "restart and reconnect" flow: a stopped runner resumes heartbeating and
     * goes back to READY with the same identity and task queue.
     *
     * @internal
     * Authorization is handled in the handler: the caller must own the runner.
     * Skipped at the interceptor level because the input is AgentRunnerHeartbeatInput
     * (not a resource), and the ownership check requires a DB lookup.
     *
     * @generated from rpc ai.stigmer.agentic.agentrunner.v1.AgentRunnerCommandController.heartbeat
     */
    heartbeat: {
      name: "heartbeat",
      I: AgentRunnerHeartbeatInput,
      O: AgentRunner,
      kind: MethodKind.Unary,
    },
  }
} as const;

