load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "config",
    srcs = ["config.go"],
    importpath = "github.com/stigmer/stigmer/backend/services/stigmer-server/pkg/config",
    visibility = ["//visibility:public"],
    deps = [
        "//backend/services/stigmer-server/pkg/domain/artifact/storage",
        "//backend/services/stigmer-server/pkg/encryption/payloadcodec",
    ],
)

go_test(
    name = "config_test",
    srcs = ["config_test.go"],
    embed = [":config"],
)
