// Code generated by stigmer-codegen. DO NOT EDIT.

package stigmer

import "github.com/stigmer/stigmer/sdk/go/v3/internal/gen"

// Resource clients -- one per API resource.
type AgentClient = gen.AgentClient
type AgentChannelClient = gen.AgentChannelClient
type AgentShareClient = gen.AgentShareClient
type ApiKeyClient = gen.ApiKeyClient
type ChannelAppClient = gen.ChannelAppClient
type EvaluatorClient = gen.EvaluatorClient
type IamPolicyClient = gen.IamPolicyClient
type IdentityAccountClient = gen.IdentityAccountClient
type IdentityProviderClient = gen.IdentityProviderClient
type InvitationClient = gen.InvitationClient
type LicenseClient = gen.LicenseClient
type MemoryClient = gen.MemoryClient
type OAuthAppClient = gen.OAuthAppClient
type OrganizationClient = gen.OrganizationClient
type PlanClient = gen.PlanClient
type PlatformClientClient = gen.PlatformClientClient
type PluginClient = gen.PluginClient
type ProviderKeyClient = gen.ProviderKeyClient
type RunClient = gen.RunClient
type ScheduleClient = gen.ScheduleClient
type ScoreClient = gen.ScoreClient
type SessionClient = gen.SessionClient

// SkillClient is NOT aliased here: the handwritten wrapper in skill.go
// (push routing over the artifact transfer lane, #675) takes the name so
// client.Skill and the exported type agree.
type SubscriptionClient = gen.SubscriptionClient
type TeamClient = gen.TeamClient
type VaultClient = gen.VaultClient

// Input types for resource mutation (Create, Update, Apply).
type AgentInput = gen.AgentInput
type SubAgentInput = gen.SubAgentInput
type EnvVarDeclarationInput = gen.EnvVarDeclarationInput
type HookSourceInput = gen.HookSourceInput
type HookConfigInput = gen.HookConfigInput
type HookGroupInput = gen.HookGroupInput
type HookHandlerInput = gen.HookHandlerInput
type RunConfigInput = gen.RunConfigInput
type AgentChannelInput = gen.AgentChannelInput
type SlackChannelConfigInput = gen.SlackChannelConfigInput
type WhatsAppChannelConfigInput = gen.WhatsAppChannelConfigInput
type AgentShareInput = gen.AgentShareInput
type AgentShareMessagesInput = gen.AgentShareMessagesInput
type ApiKeyInput = gen.ApiKeyInput
type ChannelAppInput = gen.ChannelAppInput
type SlackChannelAppConfigInput = gen.SlackChannelAppConfigInput
type WhatsAppChannelAppConfigInput = gen.WhatsAppChannelAppConfigInput
type EvaluatorInput = gen.EvaluatorInput
type IamPolicyInput = gen.IamPolicyInput
type ApiResourceRefInput = gen.ApiResourceRefInput
type IdentityAccountInput = gen.IdentityAccountInput
type IdentityAccountPreferencesInput = gen.IdentityAccountPreferencesInput
type IdentityProviderInput = gen.IdentityProviderInput
type InvitationInput = gen.InvitationInput
type LicenseInput = gen.LicenseInput
type LicenseCustomerInput = gen.LicenseCustomerInput
type EntitlementsInput = gen.EntitlementsInput
type EntitlementLimitsInput = gen.EntitlementLimitsInput
type MemoryInput = gen.MemoryInput
type MemoryProvenanceInput = gen.MemoryProvenanceInput
type OAuthAppInput = gen.OAuthAppInput
type OrganizationInput = gen.OrganizationInput
type OrganizationPreferencesInput = gen.OrganizationPreferencesInput
type PlanInput = gen.PlanInput
type PlanTermsInput = gen.PlanTermsInput
type PlatformClientInput = gen.PlatformClientInput
type PluginInput = gen.PluginInput
type PluginAuthorInput = gen.PluginAuthorInput
type RunInput = gen.RunInput
type SessionSpecInput = gen.SessionSpecInput
type WorkspaceEntryInput = gen.WorkspaceEntryInput
type WorkspaceSourceInput = gen.WorkspaceSourceInput
type GitRepoSourceInput = gen.GitRepoSourceInput
type LocalPathSourceInput = gen.LocalPathSourceInput
type AttachmentInput = gen.AttachmentInput
type ConversationCatchupInput = gen.ConversationCatchupInput
type ScheduleInput = gen.ScheduleInput
type AgentInvocationInput = gen.AgentInvocationInput
type ScoreInput = gen.ScoreInput
type ScoreCriterionInput = gen.ScoreCriterionInput
type SessionInput = gen.SessionInput
type SkillInput = gen.SkillInput
type SubscriptionInput = gen.SubscriptionInput
type TeamInput = gen.TeamInput
type VaultInput = gen.VaultInput
type VaultSecretInput = gen.VaultSecretInput
type VaultConnectionInput = gen.VaultConnectionInput
type VaultConnectionSignInInput = gen.VaultConnectionSignInInput

// Streaming types.
type RunSubscribeStream = gen.RunSubscribeStream

// Shared SDK types.
type DeleteResourceInput = gen.DeleteResourceInput
type ResourceRef = gen.ResourceRef
type Page = gen.Page
type ListParams = gen.ListParams
type ListResult = gen.ListResult
