load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "agentexecution",
    srcs = ["client.go"],
    importpath = "github.com/stigmer/stigmer/backend/services/stigmer-server/pkg/downstream/agentexecution",
    visibility = ["//visibility:public"],
    deps = [
        "//apis/stubs/go/ai/stigmer/agentic/agentexecution/v1:agentexecution",
        "@com_github_rs_zerolog//log",
        "@org_golang_google_grpc//:grpc",
    ],
)
