// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/datastore/v1/record_io.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.datastore.v1;

/**
 * <pre>
 * DatastoreDescription is a datastore's schema and the calling
 * subject's effective access, for agent and client discovery.
 *
 * &#64;internal
 * The projection deliberately excludes operator state (bindings, seed
 * records, sync report): a caller learns the shape of the data and what
 * it may do, never who else has access.
 * </pre>
 *
 * Protobuf type {@code ai.stigmer.agentic.datastore.v1.DatastoreDescription}
 */
@com.google.protobuf.Generated
public final class DatastoreDescription extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ai.stigmer.agentic.datastore.v1.DatastoreDescription)
    DatastoreDescriptionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "DatastoreDescription");
  }
  // Use DatastoreDescription.newBuilder() to construct.
  private DatastoreDescription(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DatastoreDescription() {
    datastore_ = "";
    description_ = "";
    timezone_ = "";
    collections_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.stigmer.agentic.datastore.v1.RecordIoProto.internal_static_ai_stigmer_agentic_datastore_v1_DatastoreDescription_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return ai.stigmer.agentic.datastore.v1.RecordIoProto.internal_static_ai_stigmer_agentic_datastore_v1_DatastoreDescription_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.stigmer.agentic.datastore.v1.RecordIoProto.internal_static_ai_stigmer_agentic_datastore_v1_DatastoreDescription_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.stigmer.agentic.datastore.v1.DatastoreDescription.class, ai.stigmer.agentic.datastore.v1.DatastoreDescription.Builder.class);
  }

  public static final int DATASTORE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object datastore_ = "";
  /**
   * <pre>
   * Datastore slug.
   * </pre>
   *
   * <code>string datastore = 1 [json_name = "datastore"];</code>
   * @return The datastore.
   */
  @java.lang.Override
  public java.lang.String getDatastore() {
    java.lang.Object ref = datastore_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      datastore_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Datastore slug.
   * </pre>
   *
   * <code>string datastore = 1 [json_name = "datastore"];</code>
   * @return The bytes for datastore.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDatastoreBytes() {
    java.lang.Object ref = datastore_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      datastore_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * Datastore description from the spec.
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Datastore description from the spec.
   * </pre>
   *
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEZONE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object timezone_ = "";
  /**
   * <pre>
   * IANA timezone bound as `tz` in constraint evaluation.
   * </pre>
   *
   * <code>string timezone = 3 [json_name = "timezone"];</code>
   * @return The timezone.
   */
  @java.lang.Override
  public java.lang.String getTimezone() {
    java.lang.Object ref = timezone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timezone_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * IANA timezone bound as `tz` in constraint evaluation.
   * </pre>
   *
   * <code>string timezone = 3 [json_name = "timezone"];</code>
   * @return The bytes for timezone.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimezoneBytes() {
    java.lang.Object ref = timezone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timezone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLLECTIONS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<ai.stigmer.agentic.datastore.v1.CollectionDescription> collections_;
  /**
   * <pre>
   * Collections with schema and caller-effective access.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
   */
  @java.lang.Override
  public java.util.List<ai.stigmer.agentic.datastore.v1.CollectionDescription> getCollectionsList() {
    return collections_;
  }
  /**
   * <pre>
   * Collections with schema and caller-effective access.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends ai.stigmer.agentic.datastore.v1.CollectionDescriptionOrBuilder> 
      getCollectionsOrBuilderList() {
    return collections_;
  }
  /**
   * <pre>
   * Collections with schema and caller-effective access.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
   */
  @java.lang.Override
  public int getCollectionsCount() {
    return collections_.size();
  }
  /**
   * <pre>
   * Collections with schema and caller-effective access.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
   */
  @java.lang.Override
  public ai.stigmer.agentic.datastore.v1.CollectionDescription getCollections(int index) {
    return collections_.get(index);
  }
  /**
   * <pre>
   * Collections with schema and caller-effective access.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
   */
  @java.lang.Override
  public ai.stigmer.agentic.datastore.v1.CollectionDescriptionOrBuilder getCollectionsOrBuilder(
      int index) {
    return collections_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(datastore_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, datastore_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timezone_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, timezone_);
    }
    for (int i = 0; i < collections_.size(); i++) {
      output.writeMessage(4, collections_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(datastore_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, datastore_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, description_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(timezone_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, timezone_);
    }

        {
          final int count = collections_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(collections_.get(i));
          }
          size += 1 * count;
        }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.stigmer.agentic.datastore.v1.DatastoreDescription)) {
      return super.equals(obj);
    }
    ai.stigmer.agentic.datastore.v1.DatastoreDescription other = (ai.stigmer.agentic.datastore.v1.DatastoreDescription) obj;

    if (!getDatastore()
        .equals(other.getDatastore())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (!getTimezone()
        .equals(other.getTimezone())) return false;
    if (!getCollectionsList()
        .equals(other.getCollectionsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATASTORE_FIELD_NUMBER;
    hash = (53 * hash) + getDatastore().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + TIMEZONE_FIELD_NUMBER;
    hash = (53 * hash) + getTimezone().hashCode();
    if (getCollectionsCount() > 0) {
      hash = (37 * hash) + COLLECTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getCollectionsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.stigmer.agentic.datastore.v1.DatastoreDescription prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DatastoreDescription is a datastore's schema and the calling
   * subject's effective access, for agent and client discovery.
   *
   * &#64;internal
   * The projection deliberately excludes operator state (bindings, seed
   * records, sync report): a caller learns the shape of the data and what
   * it may do, never who else has access.
   * </pre>
   *
   * Protobuf type {@code ai.stigmer.agentic.datastore.v1.DatastoreDescription}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ai.stigmer.agentic.datastore.v1.DatastoreDescription)
      ai.stigmer.agentic.datastore.v1.DatastoreDescriptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.stigmer.agentic.datastore.v1.RecordIoProto.internal_static_ai_stigmer_agentic_datastore_v1_DatastoreDescription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.stigmer.agentic.datastore.v1.RecordIoProto.internal_static_ai_stigmer_agentic_datastore_v1_DatastoreDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.stigmer.agentic.datastore.v1.DatastoreDescription.class, ai.stigmer.agentic.datastore.v1.DatastoreDescription.Builder.class);
    }

    // Construct using ai.stigmer.agentic.datastore.v1.DatastoreDescription.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      datastore_ = "";
      description_ = "";
      timezone_ = "";
      if (collectionsBuilder_ == null) {
        collections_ = java.util.Collections.emptyList();
      } else {
        collections_ = null;
        collectionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.stigmer.agentic.datastore.v1.RecordIoProto.internal_static_ai_stigmer_agentic_datastore_v1_DatastoreDescription_descriptor;
    }

    @java.lang.Override
    public ai.stigmer.agentic.datastore.v1.DatastoreDescription getDefaultInstanceForType() {
      return ai.stigmer.agentic.datastore.v1.DatastoreDescription.getDefaultInstance();
    }

    @java.lang.Override
    public ai.stigmer.agentic.datastore.v1.DatastoreDescription build() {
      ai.stigmer.agentic.datastore.v1.DatastoreDescription result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.stigmer.agentic.datastore.v1.DatastoreDescription buildPartial() {
      ai.stigmer.agentic.datastore.v1.DatastoreDescription result = new ai.stigmer.agentic.datastore.v1.DatastoreDescription(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ai.stigmer.agentic.datastore.v1.DatastoreDescription result) {
      if (collectionsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          collections_ = java.util.Collections.unmodifiableList(collections_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.collections_ = collections_;
      } else {
        result.collections_ = collectionsBuilder_.build();
      }
    }

    private void buildPartial0(ai.stigmer.agentic.datastore.v1.DatastoreDescription result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.datastore_ = datastore_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timezone_ = timezone_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.stigmer.agentic.datastore.v1.DatastoreDescription) {
        return mergeFrom((ai.stigmer.agentic.datastore.v1.DatastoreDescription)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.stigmer.agentic.datastore.v1.DatastoreDescription other) {
      if (other == ai.stigmer.agentic.datastore.v1.DatastoreDescription.getDefaultInstance()) return this;
      if (!other.getDatastore().isEmpty()) {
        datastore_ = other.datastore_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTimezone().isEmpty()) {
        timezone_ = other.timezone_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (collectionsBuilder_ == null) {
        if (!other.collections_.isEmpty()) {
          if (collections_.isEmpty()) {
            collections_ = other.collections_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCollectionsIsMutable();
            collections_.addAll(other.collections_);
          }
          onChanged();
        }
      } else {
        if (!other.collections_.isEmpty()) {
          if (collectionsBuilder_.isEmpty()) {
            collectionsBuilder_.dispose();
            collectionsBuilder_ = null;
            collections_ = other.collections_;
            bitField0_ = (bitField0_ & ~0x00000008);
            collectionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetCollectionsFieldBuilder() : null;
          } else {
            collectionsBuilder_.addAllMessages(other.collections_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              datastore_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              timezone_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              ai.stigmer.agentic.datastore.v1.CollectionDescription m =
                  input.readMessage(
                      ai.stigmer.agentic.datastore.v1.CollectionDescription.parser(),
                      extensionRegistry);
              if (collectionsBuilder_ == null) {
                ensureCollectionsIsMutable();
                collections_.add(m);
              } else {
                collectionsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object datastore_ = "";
    /**
     * <pre>
     * Datastore slug.
     * </pre>
     *
     * <code>string datastore = 1 [json_name = "datastore"];</code>
     * @return The datastore.
     */
    public java.lang.String getDatastore() {
      java.lang.Object ref = datastore_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datastore_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Datastore slug.
     * </pre>
     *
     * <code>string datastore = 1 [json_name = "datastore"];</code>
     * @return The bytes for datastore.
     */
    public com.google.protobuf.ByteString
        getDatastoreBytes() {
      java.lang.Object ref = datastore_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datastore_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Datastore slug.
     * </pre>
     *
     * <code>string datastore = 1 [json_name = "datastore"];</code>
     * @param value The datastore to set.
     * @return This builder for chaining.
     */
    public Builder setDatastore(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      datastore_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Datastore slug.
     * </pre>
     *
     * <code>string datastore = 1 [json_name = "datastore"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDatastore() {
      datastore_ = getDefaultInstance().getDatastore();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Datastore slug.
     * </pre>
     *
     * <code>string datastore = 1 [json_name = "datastore"];</code>
     * @param value The bytes for datastore to set.
     * @return This builder for chaining.
     */
    public Builder setDatastoreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      datastore_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * Datastore description from the spec.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Datastore description from the spec.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Datastore description from the spec.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Datastore description from the spec.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Datastore description from the spec.
     * </pre>
     *
     * <code>string description = 2 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object timezone_ = "";
    /**
     * <pre>
     * IANA timezone bound as `tz` in constraint evaluation.
     * </pre>
     *
     * <code>string timezone = 3 [json_name = "timezone"];</code>
     * @return The timezone.
     */
    public java.lang.String getTimezone() {
      java.lang.Object ref = timezone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timezone_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * IANA timezone bound as `tz` in constraint evaluation.
     * </pre>
     *
     * <code>string timezone = 3 [json_name = "timezone"];</code>
     * @return The bytes for timezone.
     */
    public com.google.protobuf.ByteString
        getTimezoneBytes() {
      java.lang.Object ref = timezone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timezone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * IANA timezone bound as `tz` in constraint evaluation.
     * </pre>
     *
     * <code>string timezone = 3 [json_name = "timezone"];</code>
     * @param value The timezone to set.
     * @return This builder for chaining.
     */
    public Builder setTimezone(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      timezone_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IANA timezone bound as `tz` in constraint evaluation.
     * </pre>
     *
     * <code>string timezone = 3 [json_name = "timezone"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTimezone() {
      timezone_ = getDefaultInstance().getTimezone();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * IANA timezone bound as `tz` in constraint evaluation.
     * </pre>
     *
     * <code>string timezone = 3 [json_name = "timezone"];</code>
     * @param value The bytes for timezone to set.
     * @return This builder for chaining.
     */
    public Builder setTimezoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      timezone_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<ai.stigmer.agentic.datastore.v1.CollectionDescription> collections_ =
      java.util.Collections.emptyList();
    private void ensureCollectionsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        collections_ = new java.util.ArrayList<ai.stigmer.agentic.datastore.v1.CollectionDescription>(collections_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ai.stigmer.agentic.datastore.v1.CollectionDescription, ai.stigmer.agentic.datastore.v1.CollectionDescription.Builder, ai.stigmer.agentic.datastore.v1.CollectionDescriptionOrBuilder> collectionsBuilder_;

    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public java.util.List<ai.stigmer.agentic.datastore.v1.CollectionDescription> getCollectionsList() {
      if (collectionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(collections_);
      } else {
        return collectionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public int getCollectionsCount() {
      if (collectionsBuilder_ == null) {
        return collections_.size();
      } else {
        return collectionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public ai.stigmer.agentic.datastore.v1.CollectionDescription getCollections(int index) {
      if (collectionsBuilder_ == null) {
        return collections_.get(index);
      } else {
        return collectionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public Builder setCollections(
        int index, ai.stigmer.agentic.datastore.v1.CollectionDescription value) {
      if (collectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCollectionsIsMutable();
        collections_.set(index, value);
        onChanged();
      } else {
        collectionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public Builder setCollections(
        int index, ai.stigmer.agentic.datastore.v1.CollectionDescription.Builder builderForValue) {
      if (collectionsBuilder_ == null) {
        ensureCollectionsIsMutable();
        collections_.set(index, builderForValue.build());
        onChanged();
      } else {
        collectionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public Builder addCollections(ai.stigmer.agentic.datastore.v1.CollectionDescription value) {
      if (collectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCollectionsIsMutable();
        collections_.add(value);
        onChanged();
      } else {
        collectionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public Builder addCollections(
        int index, ai.stigmer.agentic.datastore.v1.CollectionDescription value) {
      if (collectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCollectionsIsMutable();
        collections_.add(index, value);
        onChanged();
      } else {
        collectionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public Builder addCollections(
        ai.stigmer.agentic.datastore.v1.CollectionDescription.Builder builderForValue) {
      if (collectionsBuilder_ == null) {
        ensureCollectionsIsMutable();
        collections_.add(builderForValue.build());
        onChanged();
      } else {
        collectionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public Builder addCollections(
        int index, ai.stigmer.agentic.datastore.v1.CollectionDescription.Builder builderForValue) {
      if (collectionsBuilder_ == null) {
        ensureCollectionsIsMutable();
        collections_.add(index, builderForValue.build());
        onChanged();
      } else {
        collectionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public Builder addAllCollections(
        java.lang.Iterable<? extends ai.stigmer.agentic.datastore.v1.CollectionDescription> values) {
      if (collectionsBuilder_ == null) {
        ensureCollectionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, collections_);
        onChanged();
      } else {
        collectionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public Builder clearCollections() {
      if (collectionsBuilder_ == null) {
        collections_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        collectionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public Builder removeCollections(int index) {
      if (collectionsBuilder_ == null) {
        ensureCollectionsIsMutable();
        collections_.remove(index);
        onChanged();
      } else {
        collectionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public ai.stigmer.agentic.datastore.v1.CollectionDescription.Builder getCollectionsBuilder(
        int index) {
      return internalGetCollectionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public ai.stigmer.agentic.datastore.v1.CollectionDescriptionOrBuilder getCollectionsOrBuilder(
        int index) {
      if (collectionsBuilder_ == null) {
        return collections_.get(index);  } else {
        return collectionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public java.util.List<? extends ai.stigmer.agentic.datastore.v1.CollectionDescriptionOrBuilder> 
         getCollectionsOrBuilderList() {
      if (collectionsBuilder_ != null) {
        return collectionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(collections_);
      }
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public ai.stigmer.agentic.datastore.v1.CollectionDescription.Builder addCollectionsBuilder() {
      return internalGetCollectionsFieldBuilder().addBuilder(
          ai.stigmer.agentic.datastore.v1.CollectionDescription.getDefaultInstance());
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public ai.stigmer.agentic.datastore.v1.CollectionDescription.Builder addCollectionsBuilder(
        int index) {
      return internalGetCollectionsFieldBuilder().addBuilder(
          index, ai.stigmer.agentic.datastore.v1.CollectionDescription.getDefaultInstance());
    }
    /**
     * <pre>
     * Collections with schema and caller-effective access.
     * </pre>
     *
     * <code>repeated .ai.stigmer.agentic.datastore.v1.CollectionDescription collections = 4 [json_name = "collections"];</code>
     */
    public java.util.List<ai.stigmer.agentic.datastore.v1.CollectionDescription.Builder> 
         getCollectionsBuilderList() {
      return internalGetCollectionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ai.stigmer.agentic.datastore.v1.CollectionDescription, ai.stigmer.agentic.datastore.v1.CollectionDescription.Builder, ai.stigmer.agentic.datastore.v1.CollectionDescriptionOrBuilder> 
        internalGetCollectionsFieldBuilder() {
      if (collectionsBuilder_ == null) {
        collectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ai.stigmer.agentic.datastore.v1.CollectionDescription, ai.stigmer.agentic.datastore.v1.CollectionDescription.Builder, ai.stigmer.agentic.datastore.v1.CollectionDescriptionOrBuilder>(
                collections_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        collections_ = null;
      }
      return collectionsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ai.stigmer.agentic.datastore.v1.DatastoreDescription)
  }

  // @@protoc_insertion_point(class_scope:ai.stigmer.agentic.datastore.v1.DatastoreDescription)
  private static final ai.stigmer.agentic.datastore.v1.DatastoreDescription DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.stigmer.agentic.datastore.v1.DatastoreDescription();
  }

  public static ai.stigmer.agentic.datastore.v1.DatastoreDescription getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DatastoreDescription>
      PARSER = new com.google.protobuf.AbstractParser<DatastoreDescription>() {
    @java.lang.Override
    public DatastoreDescription parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DatastoreDescription> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DatastoreDescription> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.stigmer.agentic.datastore.v1.DatastoreDescription getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

