load("@rules_go//go:def.bzl", "go_library", "go_test")

# gazelle:exclude webconsole_embed.go

go_library(
    name = "webconsole",
    srcs = [
        "handler.go",
        "webconsole.go",
    ],
    importpath = "github.com/stigmer/stigmer/client-apps/cli/embedded/webconsole",
    visibility = ["//visibility:public"],
)

go_test(
    name = "webconsole_test",
    srcs = ["handler_test.go"],
    embed = [":webconsole"],
)
