// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/session/v1/event.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.session.v1;

@com.google.protobuf.Generated
public interface SessionThreadStatusRunningEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.agentic.session.v1.SessionThreadStatusRunningEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The event's id, unique in its session: letters, digits, _ . : -, at most 128.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * The event's id, unique in its session: letters, digits, _ . : -, at most 128.
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The name of the agent the thread runs.
   * </pre>
   *
   * <code>string agent_name = 2 [json_name = "agentName"];</code>
   * @return The agentName.
   */
  java.lang.String getAgentName();
  /**
   * <pre>
   * The name of the agent the thread runs.
   * </pre>
   *
   * <code>string agent_name = 2 [json_name = "agentName"];</code>
   * @return The bytes for agentName.
   */
  com.google.protobuf.ByteString
      getAgentNameBytes();

  /**
   * <pre>
   * When the event was appended, as RFC 3339 UTC.
   * </pre>
   *
   * <code>string processed_at = 3 [json_name = "processedAt"];</code>
   * @return The processedAt.
   */
  java.lang.String getProcessedAt();
  /**
   * <pre>
   * When the event was appended, as RFC 3339 UTC.
   * </pre>
   *
   * <code>string processed_at = 3 [json_name = "processedAt"];</code>
   * @return The bytes for processedAt.
   */
  com.google.protobuf.ByteString
      getProcessedAtBytes();

  /**
   * <pre>
   * The thread.
   * </pre>
   *
   * <code>string session_thread_id = 4 [json_name = "sessionThreadId", (.buf.validate.field) = { ... }</code>
   * @return The sessionThreadId.
   */
  java.lang.String getSessionThreadId();
  /**
   * <pre>
   * The thread.
   * </pre>
   *
   * <code>string session_thread_id = 4 [json_name = "sessionThreadId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for sessionThreadId.
   */
  com.google.protobuf.ByteString
      getSessionThreadIdBytes();
}
