load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "mcpserver",
    srcs = [
        "config.go",
        "run.go",
    ],
    importpath = "github.com/stigmer/stigmer/mcp-server/pkg/mcpserver",
    visibility = ["//visibility:public"],
    deps = [
        "//mcp-server/internal/config",
        "//mcp-server/internal/server",
    ],
)

go_test(
    name = "mcpserver_test",
    srcs = [
        "config_test.go",
        "run_test.go",
    ],
    embed = [":mcpserver"],
)
