apiVersion: iam.stigmer.com/v1
kind: IdentityAccount
metadata:
  id: ida_01jpw4t0vthaeq6fry94qq5g2k
spec:
  idpId: auth0|abc123xyz
  email: alice@example.com
  firstName: Alice
  lastName: Smith
  pictureUrl: https://example.com/avatar.jpg




