load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "templates",
    srcs = ["templates.go"],
    importpath = "github.com/stigmer/stigmer/sdk/go/internal/templates",
    visibility = ["//visibility:public"],
)

go_test(
    name = "templates_test",
    srcs = ["templates_test.go"],
    embed = [":templates"],
)
