apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesDeployment
metadata:
  name: stigmer-web
  env: local
  labels:
    pulumi.project-planton.org/stack.name: local.KubernetesDeployment.stigmer-web
spec:
  namespace:
    value: stigmer-local-web
  container:
    app:
      env:
        variables:
          NEXT_PUBLIC_IAM_API_AUDIENCE: $variables-group/stigmer-auth0-config/prod.api-audience
          IAM_DOMAIN: $variables-group/stigmer-auth0-config/prod.domain
          IAM_CLIENT_ID: $variables-group/stigmer-auth0-config/prod.web-client-id
          IAM_API_AUDIENCE: $variables-group/stigmer-auth0-config/prod.api-audience
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_URL_INTERNAL: http://localhost:3000
        secrets:
          IAM_CLIENT_SECRET:
            value: $secrets-group/stigmer-auth0-credentials/prod.web-client-secret
          NEXTAUTH_SECRET:
            value: $secrets-group/stigmer-web/prod.nextauth-secret

