load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "mcp-server-stigmer_lib",
    srcs = ["main.go"],
    importpath = "github.com/stigmer/stigmer/mcp-server/cmd/mcp-server-stigmer",
    visibility = ["//visibility:private"],
    deps = ["//mcp-server/pkg/mcpserver"],
)

go_binary(
    name = "mcp-server-stigmer",
    embed = [":mcp-server-stigmer_lib"],
    visibility = ["//visibility:public"],
)
