// @generated by protoc-gen-es v2.2.2 with parameter "target=ts,import_extension=js"
// @generated from file ai/stigmer/commons/apiresource/status.proto (package ai.stigmer.commons.apiresource, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ai/stigmer/commons/apiresource/status.proto.
 */
export const file_ai_stigmer_commons_apiresource_status: GenFile = /*@__PURE__*/
  fileDesc("CithaS9zdGlnbWVyL2NvbW1vbnMvYXBpcmVzb3VyY2Uvc3RhdHVzLnByb3RvEh5haS5zdGlnbWVyLmNvbW1vbnMuYXBpcmVzb3VyY2UiWQoWQXBpUmVzb3VyY2VBdWRpdFN0YXR1cxI/CgVhdWRpdBhjIAEoCzIwLmFpLnN0aWdtZXIuY29tbW9ucy5hcGlyZXNvdXJjZS5BcGlSZXNvdXJjZUF1ZGl0IqgBChBBcGlSZXNvdXJjZUF1ZGl0EkgKCnNwZWNfYXVkaXQYASABKAsyNC5haS5zdGlnbWVyLmNvbW1vbnMuYXBpcmVzb3VyY2UuQXBpUmVzb3VyY2VBdWRpdEluZm8SSgoMc3RhdHVzX2F1ZGl0GAIgASgLMjQuYWkuc3RpZ21lci5jb21tb25zLmFwaXJlc291cmNlLkFwaVJlc291cmNlQXVkaXRJbmZvIpsCChRBcGlSZXNvdXJjZUF1ZGl0SW5mbxJJCgpjcmVhdGVkX2J5GAEgASgLMjUuYWkuc3RpZ21lci5jb21tb25zLmFwaXJlc291cmNlLkFwaVJlc291cmNlQXVkaXRBY3RvchIuCgpjcmVhdGVkX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBJJCgp1cGRhdGVkX2J5GAMgASgLMjUuYWkuc3RpZ21lci5jb21tb25zLmFwaXJlc291cmNlLkFwaVJlc291cmNlQXVkaXRBY3RvchIuCgp1cGRhdGVkX2F0GAQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBINCgVldmVudBgFIAEoCSJYChVBcGlSZXNvdXJjZUF1ZGl0QWN0b3ISCgoCaWQYASABKAkSDgoGYXZhdGFyGAIgASgJEhQKDGRpc3BsYXlfbmFtZRgDIAEoCRINCgVlbWFpbBgEIAEoCWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * ApiResourceAuditStatus contains system-managed audit information for a resource.
 *
 * @generated from message ai.stigmer.commons.apiresource.ApiResourceAuditStatus
 */
export type ApiResourceAuditStatus = Message<"ai.stigmer.commons.apiresource.ApiResourceAuditStatus"> & {
  /**
   * Audit information tracking creation and modification.
   *
   * @generated from field: ai.stigmer.commons.apiresource.ApiResourceAudit audit = 99;
   */
  audit?: ApiResourceAudit;
};

/**
 * Describes the message ai.stigmer.commons.apiresource.ApiResourceAuditStatus.
 * Use `create(ApiResourceAuditStatusSchema)` to create a new message.
 */
export const ApiResourceAuditStatusSchema: GenMessage<ApiResourceAuditStatus> = /*@__PURE__*/
  messageDesc(file_ai_stigmer_commons_apiresource_status, 0);

/**
 * ApiResourceAudit contains both spec-level and status-level audit details.
 *
 * @generated from message ai.stigmer.commons.apiresource.ApiResourceAudit
 */
export type ApiResourceAudit = Message<"ai.stigmer.commons.apiresource.ApiResourceAudit"> & {
  /**
   * Audit info for the resource's specification (desired state).
   *
   * @generated from field: ai.stigmer.commons.apiresource.ApiResourceAuditInfo spec_audit = 1;
   */
  specAudit?: ApiResourceAuditInfo;

  /**
   * Audit info for the resource's status (actual state).
   *
   * @generated from field: ai.stigmer.commons.apiresource.ApiResourceAuditInfo status_audit = 2;
   */
  statusAudit?: ApiResourceAuditInfo;
};

/**
 * Describes the message ai.stigmer.commons.apiresource.ApiResourceAudit.
 * Use `create(ApiResourceAuditSchema)` to create a new message.
 */
export const ApiResourceAuditSchema: GenMessage<ApiResourceAudit> = /*@__PURE__*/
  messageDesc(file_ai_stigmer_commons_apiresource_status, 1);

/**
 * ApiResourceAuditInfo contains detailed audit information.
 *
 * @generated from message ai.stigmer.commons.apiresource.ApiResourceAuditInfo
 */
export type ApiResourceAuditInfo = Message<"ai.stigmer.commons.apiresource.ApiResourceAuditInfo"> & {
  /**
   * Actor who created this resource.
   *
   * @generated from field: ai.stigmer.commons.apiresource.ApiResourceAuditActor created_by = 1;
   */
  createdBy?: ApiResourceAuditActor;

  /**
   * Timestamp when the resource was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;

  /**
   * Actor who last updated this resource.
   *
   * @generated from field: ai.stigmer.commons.apiresource.ApiResourceAuditActor updated_by = 3;
   */
  updatedBy?: ApiResourceAuditActor;

  /**
   * Timestamp when the resource was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 4;
   */
  updatedAt?: Timestamp;

  /**
   * Type of the last event (e.g., "created", "updated").
   *
   * @generated from field: string event = 5;
   */
  event: string;
};

/**
 * Describes the message ai.stigmer.commons.apiresource.ApiResourceAuditInfo.
 * Use `create(ApiResourceAuditInfoSchema)` to create a new message.
 */
export const ApiResourceAuditInfoSchema: GenMessage<ApiResourceAuditInfo> = /*@__PURE__*/
  messageDesc(file_ai_stigmer_commons_apiresource_status, 2);

/**
 * ApiResourceAuditActor represents the entity that performed an action.
 *
 * This is the platform's single actor vocabulary: every "who did this"
 * reference (created_by / updated_by, version-history applied_by / pushed_by,
 * approval resolved_by_actor) uses this message, so actor rendering is
 * uniform across all surfaces.
 *
 * @generated from message ai.stigmer.commons.apiresource.ApiResourceAuditActor
 */
export type ApiResourceAuditActor = Message<"ai.stigmer.commons.apiresource.ApiResourceAuditActor"> & {
  /**
   * Unique identifier of the actor.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * URL to the actor's avatar image.
   *
   * @generated from field: string avatar = 2;
   */
  avatar: string;

  /**
   * Human-readable display name (e.g. "Ada Lovelace"). Empty when unknown;
   * renderers fall back to email, then id.
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * Email address of the actor. Empty when unknown or not applicable
   * (e.g. machine accounts).
   *
   * @generated from field: string email = 4;
   */
  email: string;
};

/**
 * Describes the message ai.stigmer.commons.apiresource.ApiResourceAuditActor.
 * Use `create(ApiResourceAuditActorSchema)` to create a new message.
 */
export const ApiResourceAuditActorSchema: GenMessage<ApiResourceAuditActor> = /*@__PURE__*/
  messageDesc(file_ai_stigmer_commons_apiresource_status, 3);

