// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ai/stigmer/agentic/datastore/v1/query.proto

package datastorev1

import (
	context "context"
	apiresource "github.com/stigmer/stigmer/apis/stubs/go/ai/stigmer/commons/apiresource"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatastoreQueryController_Get_FullMethodName            = "/ai.stigmer.agentic.datastore.v1.DatastoreQueryController/get"
	DatastoreQueryController_GetByReference_FullMethodName = "/ai.stigmer.agentic.datastore.v1.DatastoreQueryController/getByReference"
	DatastoreQueryController_List_FullMethodName           = "/ai.stigmer.agentic.datastore.v1.DatastoreQueryController/list"
)

// DatastoreQueryControllerClient is the client API for DatastoreQueryController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DatastoreQueryController handles read operations for datastores.
//
// @internal
// These RPCs read the datastore resource (spec + status), not its
// records. Record reads go through DatastoreRecordQueryController.
type DatastoreQueryControllerClient interface {
	// Get a datastore by ID.
	//
	// @internal
	// Authorization: requires can_view permission on the datastore resource.
	Get(ctx context.Context, in *apiresource.ApiResourceId, opts ...grpc.CallOption) (*Datastore, error)
	// Get a datastore by its organization-scoped reference (org/slug).
	// Resolves a human-readable reference like "acme/clinic-records" to the full Datastore resource.
	//
	// @internal
	// Custom authorization in handler — checks both direct resource access
	// and organization-level visibility permissions.
	GetByReference(ctx context.Context, in *apiresource.ApiResourceReference, opts ...grpc.CallOption) (*Datastore, error)
	// List datastores with optional label filtering.
	//
	// @internal
	// Authorization is handled in-handler via FGA-filtered queries (cloud)
	// or unrestricted store queries (OSS).
	List(ctx context.Context, in *ListDatastoresRequest, opts ...grpc.CallOption) (*DatastoreList, error)
}

type datastoreQueryControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewDatastoreQueryControllerClient(cc grpc.ClientConnInterface) DatastoreQueryControllerClient {
	return &datastoreQueryControllerClient{cc}
}

func (c *datastoreQueryControllerClient) Get(ctx context.Context, in *apiresource.ApiResourceId, opts ...grpc.CallOption) (*Datastore, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Datastore)
	err := c.cc.Invoke(ctx, DatastoreQueryController_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreQueryControllerClient) GetByReference(ctx context.Context, in *apiresource.ApiResourceReference, opts ...grpc.CallOption) (*Datastore, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Datastore)
	err := c.cc.Invoke(ctx, DatastoreQueryController_GetByReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datastoreQueryControllerClient) List(ctx context.Context, in *ListDatastoresRequest, opts ...grpc.CallOption) (*DatastoreList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DatastoreList)
	err := c.cc.Invoke(ctx, DatastoreQueryController_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatastoreQueryControllerServer is the server API for DatastoreQueryController service.
// All implementations should embed UnimplementedDatastoreQueryControllerServer
// for forward compatibility.
//
// DatastoreQueryController handles read operations for datastores.
//
// @internal
// These RPCs read the datastore resource (spec + status), not its
// records. Record reads go through DatastoreRecordQueryController.
type DatastoreQueryControllerServer interface {
	// Get a datastore by ID.
	//
	// @internal
	// Authorization: requires can_view permission on the datastore resource.
	Get(context.Context, *apiresource.ApiResourceId) (*Datastore, error)
	// Get a datastore by its organization-scoped reference (org/slug).
	// Resolves a human-readable reference like "acme/clinic-records" to the full Datastore resource.
	//
	// @internal
	// Custom authorization in handler — checks both direct resource access
	// and organization-level visibility permissions.
	GetByReference(context.Context, *apiresource.ApiResourceReference) (*Datastore, error)
	// List datastores with optional label filtering.
	//
	// @internal
	// Authorization is handled in-handler via FGA-filtered queries (cloud)
	// or unrestricted store queries (OSS).
	List(context.Context, *ListDatastoresRequest) (*DatastoreList, error)
}

// UnimplementedDatastoreQueryControllerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatastoreQueryControllerServer struct{}

func (UnimplementedDatastoreQueryControllerServer) Get(context.Context, *apiresource.ApiResourceId) (*Datastore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDatastoreQueryControllerServer) GetByReference(context.Context, *apiresource.ApiResourceReference) (*Datastore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByReference not implemented")
}
func (UnimplementedDatastoreQueryControllerServer) List(context.Context, *ListDatastoresRequest) (*DatastoreList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDatastoreQueryControllerServer) testEmbeddedByValue() {}

// UnsafeDatastoreQueryControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatastoreQueryControllerServer will
// result in compilation errors.
type UnsafeDatastoreQueryControllerServer interface {
	mustEmbedUnimplementedDatastoreQueryControllerServer()
}

func RegisterDatastoreQueryControllerServer(s grpc.ServiceRegistrar, srv DatastoreQueryControllerServer) {
	// If the following call pancis, it indicates UnimplementedDatastoreQueryControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatastoreQueryController_ServiceDesc, srv)
}

func _DatastoreQueryController_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(apiresource.ApiResourceId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreQueryControllerServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreQueryController_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreQueryControllerServer).Get(ctx, req.(*apiresource.ApiResourceId))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreQueryController_GetByReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(apiresource.ApiResourceReference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreQueryControllerServer).GetByReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreQueryController_GetByReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreQueryControllerServer).GetByReference(ctx, req.(*apiresource.ApiResourceReference))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatastoreQueryController_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatastoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatastoreQueryControllerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatastoreQueryController_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatastoreQueryControllerServer).List(ctx, req.(*ListDatastoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DatastoreQueryController_ServiceDesc is the grpc.ServiceDesc for DatastoreQueryController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatastoreQueryController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.stigmer.agentic.datastore.v1.DatastoreQueryController",
	HandlerType: (*DatastoreQueryControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get",
			Handler:    _DatastoreQueryController_Get_Handler,
		},
		{
			MethodName: "getByReference",
			Handler:    _DatastoreQueryController_GetByReference_Handler,
		},
		{
			MethodName: "list",
			Handler:    _DatastoreQueryController_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai/stigmer/agentic/datastore/v1/query.proto",
}
