load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "encryption",
    srcs = [
        "encryption.go",
        "keymanager.go",
    ],
    importpath = "github.com/stigmer/stigmer/backend/services/stigmer-server/pkg/encryption",
    visibility = ["//visibility:public"],
)

go_test(
    name = "encryption_test",
    srcs = ["encryption_test.go"],
    embed = [":encryption"],
)
