load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "activities",
    srcs = [
        "delete_execution_context.go",
    ],
    importpath = "github.com/stigmer/stigmer/backend/services/stigmer-server/pkg/domain/executioncontext/temporal/activities",
    visibility = ["//visibility:public"],
    deps = [
        "//apis/stubs/go/ai/stigmer/agentic/executioncontext/v1:executioncontext",
        "//apis/stubs/go/ai/stigmer/commons/apiresource/apiresourcekind",
        "//backend/libs/go/store",
        "@com_github_rs_zerolog//log",
    ],
)
