// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/schedule/v1/spec.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.schedule.v1;

@com.google.protobuf.Generated
public final class SpecProto extends com.google.protobuf.GeneratedFile {
  private SpecProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "SpecProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_agentic_schedule_v1_ScheduleSpec_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_agentic_schedule_v1_ScheduleSpec_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)ai/stigmer/agentic/schedule/v1/spec.pr" +
      "oto\022\036ai.stigmer.agentic.schedule.v1\0325ai/" +
      "stigmer/agentic/agentexecution/v1/invoca" +
      "tion.proto\032\033buf/validate/validate.proto\"" +
      "\313\001\n\014ScheduleSpec\022\033\n\004cron\030\001 \001(\tB\007\272H\004r\002\020\001R" +
      "\004cron\022$\n\ttime_zone\030\002 \001(\tB\007\272H\004r\002\020\001R\010timeZ" +
      "one\022\030\n\007enabled\030\003 \001(\010R\007enabled\022M\n\005agent\030\004" +
      " \001(\01325.ai.stigmer.agentic.agentexecution" +
      ".v1.AgentInvocationH\000R\005agentB\017\n\006target\022\005" +
      "\272H\002\010\001B\250\001B\tSpecProtoP\001\242\002\004ASAS\252\002\036Ai.Stigme" +
      "r.Agentic.Schedule.V1\312\002\036Ai\\Stigmer\\Agent" +
      "ic\\Schedule\\V1\342\002*Ai\\Stigmer\\Agentic\\Sche" +
      "dule\\V1\\GPBMetadata\352\002\"Ai::Stigmer::Agent" +
      "ic::Schedule::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ai.stigmer.agentic.agentexecution.v1.InvocationProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_ai_stigmer_agentic_schedule_v1_ScheduleSpec_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_ai_stigmer_agentic_schedule_v1_ScheduleSpec_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_agentic_schedule_v1_ScheduleSpec_descriptor,
        new java.lang.String[] { "Cron", "TimeZone", "Enabled", "Agent", "Target", });
    descriptor.resolveAllFeaturesImmutable();
    ai.stigmer.agentic.agentexecution.v1.InvocationProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    registry.add(build.buf.validate.ValidateProto.oneof);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
