// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/stigmer/agentic/plugin/v1/api.proto

package pluginv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	apiresource "github.com/stigmer/stigmer/sdk/go/v3/proto/ai/stigmer/commons/apiresource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Plugin is an installed Agent Plugins package: the unit of install, upgrade
// and removal for a set of skills, MCP servers, an agent and workflows.
//
// A plugin is what you install; an agent is what runs. Installing a plugin
// materialises ordinary Stigmer resources in the organization, each labelled
// with the plugin's id; the plugin owns their grouping, version and removal
// while execution, authorization and sharing stay on the resources.
type Plugin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API version for this resource type.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Resource kind identifier.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Standard resource metadata including name, id, labels, and tags.
	// The name and slug come from the package manifest's name.
	Metadata *apiresource.ApiResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Manifest metadata extracted from the package (desired state).
	Spec *PluginSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// System-managed install state (observed state).
	Status        *PluginStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	mi := &file_ai_stigmer_agentic_plugin_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_ai_stigmer_agentic_plugin_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plugin.ProtoReflect.Descriptor instead.
func (*Plugin) Descriptor() ([]byte, []int) {
	return file_ai_stigmer_agentic_plugin_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *Plugin) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Plugin) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Plugin) GetMetadata() *apiresource.ApiResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Plugin) GetSpec() *PluginSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Plugin) GetStatus() *PluginStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// PluginList represents a paginated list of plugins.
type PluginList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API version for this list type.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Resource kind identifier for the list.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// List of plugin resources.
	Items         []*Plugin `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginList) Reset() {
	*x = PluginList{}
	mi := &file_ai_stigmer_agentic_plugin_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginList) ProtoMessage() {}

func (x *PluginList) ProtoReflect() protoreflect.Message {
	mi := &file_ai_stigmer_agentic_plugin_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginList.ProtoReflect.Descriptor instead.
func (*PluginList) Descriptor() ([]byte, []int) {
	return file_ai_stigmer_agentic_plugin_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *PluginList) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *PluginList) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PluginList) GetItems() []*Plugin {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_ai_stigmer_agentic_plugin_v1_api_proto protoreflect.FileDescriptor

const file_ai_stigmer_agentic_plugin_v1_api_proto_rawDesc = "" +
	"\n" +
	"&ai/stigmer/agentic/plugin/v1/api.proto\x12\x1cai.stigmer.agentic.plugin.v1\x1a'ai/stigmer/agentic/plugin/v1/spec.proto\x1a)ai/stigmer/agentic/plugin/v1/status.proto\x1a-ai/stigmer/commons/apiresource/metadata.proto\x1a\x1bbuf/validate/validate.proto\"\xc5\x02\n" +
	"\x06Plugin\x12=\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1c\xbaH\x19r\x17\n" +
	"\x15agentic.stigmer.ai/v1R\n" +
	"apiVersion\x12!\n" +
	"\x04kind\x18\x02 \x01(\tB\r\xbaH\n" +
	"r\b\n" +
	"\x06PluginR\x04kind\x12W\n" +
	"\bmetadata\x18\x03 \x01(\v23.ai.stigmer.commons.apiresource.ApiResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12<\n" +
	"\x04spec\x18\x04 \x01(\v2(.ai.stigmer.agentic.plugin.v1.PluginSpecR\x04spec\x12B\n" +
	"\x06status\x18\x05 \x01(\v2*.ai.stigmer.agentic.plugin.v1.PluginStatusR\x06status\"}\n" +
	"\n" +
	"PluginList\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12:\n" +
	"\x05items\x18\x03 \x03(\v2$.ai.stigmer.agentic.plugin.v1.PluginR\x05itemsB\x93\x02\n" +
	" com.ai.stigmer.agentic.plugin.v1B\bApiProtoP\x01ZPgithub.com/stigmer/stigmer/sdk/go/v3/proto/ai/stigmer/agentic/plugin/v1;pluginv1\xa2\x02\x04ASAP\xaa\x02\x1cAi.Stigmer.Agentic.Plugin.V1\xca\x02\x1cAi\\Stigmer\\Agentic\\Plugin\\V1\xe2\x02(Ai\\Stigmer\\Agentic\\Plugin\\V1\\GPBMetadata\xea\x02 Ai::Stigmer::Agentic::Plugin::V1b\x06proto3"

var (
	file_ai_stigmer_agentic_plugin_v1_api_proto_rawDescOnce sync.Once
	file_ai_stigmer_agentic_plugin_v1_api_proto_rawDescData []byte
)

func file_ai_stigmer_agentic_plugin_v1_api_proto_rawDescGZIP() []byte {
	file_ai_stigmer_agentic_plugin_v1_api_proto_rawDescOnce.Do(func() {
		file_ai_stigmer_agentic_plugin_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_stigmer_agentic_plugin_v1_api_proto_rawDesc), len(file_ai_stigmer_agentic_plugin_v1_api_proto_rawDesc)))
	})
	return file_ai_stigmer_agentic_plugin_v1_api_proto_rawDescData
}

var file_ai_stigmer_agentic_plugin_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ai_stigmer_agentic_plugin_v1_api_proto_goTypes = []any{
	(*Plugin)(nil),                          // 0: ai.stigmer.agentic.plugin.v1.Plugin
	(*PluginList)(nil),                      // 1: ai.stigmer.agentic.plugin.v1.PluginList
	(*apiresource.ApiResourceMetadata)(nil), // 2: ai.stigmer.commons.apiresource.ApiResourceMetadata
	(*PluginSpec)(nil),                      // 3: ai.stigmer.agentic.plugin.v1.PluginSpec
	(*PluginStatus)(nil),                    // 4: ai.stigmer.agentic.plugin.v1.PluginStatus
}
var file_ai_stigmer_agentic_plugin_v1_api_proto_depIdxs = []int32{
	2, // 0: ai.stigmer.agentic.plugin.v1.Plugin.metadata:type_name -> ai.stigmer.commons.apiresource.ApiResourceMetadata
	3, // 1: ai.stigmer.agentic.plugin.v1.Plugin.spec:type_name -> ai.stigmer.agentic.plugin.v1.PluginSpec
	4, // 2: ai.stigmer.agentic.plugin.v1.Plugin.status:type_name -> ai.stigmer.agentic.plugin.v1.PluginStatus
	0, // 3: ai.stigmer.agentic.plugin.v1.PluginList.items:type_name -> ai.stigmer.agentic.plugin.v1.Plugin
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_stigmer_agentic_plugin_v1_api_proto_init() }
func file_ai_stigmer_agentic_plugin_v1_api_proto_init() {
	if File_ai_stigmer_agentic_plugin_v1_api_proto != nil {
		return
	}
	file_ai_stigmer_agentic_plugin_v1_spec_proto_init()
	file_ai_stigmer_agentic_plugin_v1_status_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_stigmer_agentic_plugin_v1_api_proto_rawDesc), len(file_ai_stigmer_agentic_plugin_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_stigmer_agentic_plugin_v1_api_proto_goTypes,
		DependencyIndexes: file_ai_stigmer_agentic_plugin_v1_api_proto_depIdxs,
		MessageInfos:      file_ai_stigmer_agentic_plugin_v1_api_proto_msgTypes,
	}.Build()
	File_ai_stigmer_agentic_plugin_v1_api_proto = out.File
	file_ai_stigmer_agentic_plugin_v1_api_proto_goTypes = nil
	file_ai_stigmer_agentic_plugin_v1_api_proto_depIdxs = nil
}
