load("@rules_go//go:def.bzl", "go_library")
load("@rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "ai_stigmer_agentic_agent_v1_proto",
    srcs = [
        "agent-api.proto",
        "agent-spec.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//ai/stigmer/agentic/agent/v1:v1_proto",
        "//ai/stigmer/agentic/environment/v1:v1_proto",
        "//ai/stigmer/commons/apiresource:apiresource_proto",
        "//buf/validate:validate_proto",
    ],
)

go_proto_library(
    name = "ai_stigmer_agentic_agent_v1_go_proto",
    importpath = "github.com/stigmer/stigmer/backend/libs/go/seedpack/drafts/agent-drafter/inputs",
    proto = ":ai_stigmer_agentic_agent_v1_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//ai/stigmer/agentic/agent/v1:spec_proto",
        "//ai/stigmer/agentic/agent/v1:status_proto",
        "//ai/stigmer/agentic/environment/v1:spec_proto",
        "//ai/stigmer/commons/apiresource:io_proto",
        "//ai/stigmer/commons/apiresource:metadata_proto",
        "//buf/validate:validate_proto",
    ],
)

go_library(
    name = "inputs",
    embed = [":ai_stigmer_agentic_agent_v1_go_proto"],
    importpath = "github.com/stigmer/stigmer/backend/libs/go/seedpack/drafts/agent-drafter/inputs",
    visibility = ["//visibility:public"],
)
