// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=js"
// @generated from file ai/stigmer/agentic/vault/v1/query.proto (package ai.stigmer.agentic.vault.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ApiResourceId, ApiResourceReference } from "../../../commons/apiresource/io_pbjs";
import { Vault } from "./api_pbjs";
import { MethodKind } from "@bufbuild/protobuf";
import { GetMyVaultInput, GetVaultByExternalIdInput, ListVaultsRequest, VaultList } from "./io_pbjs";

/**
 * VaultQueryController handles read operations for vaults.
 *
 * Every read shows entry names, addresses, descriptions and who saved them,
 * never a value.
 *
 * @generated from service ai.stigmer.agentic.vault.v1.VaultQueryController
 */
export const VaultQueryController = {
  typeName: "ai.stigmer.agentic.vault.v1.VaultQueryController",
  methods: {
    /**
     * Get a vault by ID.
     *
     * @generated from rpc ai.stigmer.agentic.vault.v1.VaultQueryController.get
     */
    get: {
      name: "get",
      I: ApiResourceId,
      O: Vault,
      kind: MethodKind.Unary,
    },
    /**
     * Get a vault by its organization-scoped reference (org/slug).
     *
     * @generated from rpc ai.stigmer.agentic.vault.v1.VaultQueryController.getByReference
     */
    getByReference: {
      name: "getByReference",
      I: ApiResourceReference,
      O: Vault,
      kind: MethodKind.Unary,
    },
    /**
     * Get the caller's own My vault in an organization.
     *
     * Answers NOT_FOUND until the caller saves their first login or secret.
     *
     * @generated from rpc ai.stigmer.agentic.vault.v1.VaultQueryController.getMine
     */
    getMine: {
      name: "getMine",
      I: GetMyVaultInput,
      O: Vault,
      kind: MethodKind.Unary,
    },
    /**
     * Get a shared vault by the integrator's own id for it.
     *
     * @generated from rpc ai.stigmer.agentic.vault.v1.VaultQueryController.getByExternalId
     */
    getByExternalId: {
      name: "getByExternalId",
      I: GetVaultByExternalIdInput,
      O: Vault,
      kind: MethodKind.Unary,
    },
    /**
     * List the vaults the caller can see in an organization: their own My
     * vault and the shared vaults they may view.
     *
     * @generated from rpc ai.stigmer.agentic.vault.v1.VaultQueryController.list
     */
    list: {
      name: "list",
      I: ListVaultsRequest,
      O: VaultList,
      kind: MethodKind.Unary,
    },
  }
} as const;

