load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "controller",
    srcs = ["github_controller.go"],
    importpath = "github.com/stigmer/stigmer/backend/services/stigmer-server/pkg/domain/github/controller",
    visibility = ["//visibility:public"],
    deps = [
        "//apis/stubs/go/ai/stigmer/platform/github/v1:github",
        "@com_github_rs_zerolog//log",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
