// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/iam/invitation/v1/command.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.iam.invitation.v1;

@com.google.protobuf.Generated
public final class CommandProto extends com.google.protobuf.GeneratedFile {
  private CommandProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "CommandProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*ai/stigmer/iam/invitation/v1/command.p" +
      "roto\022\034ai.stigmer.iam.invitation.v1\0328ai/s" +
      "tigmer/commons/apiresource/rpc_service_o" +
      "ptions.proto\032+ai/stigmer/commons/rpc/met" +
      "hod_options.proto\032&ai/stigmer/iam/invita" +
      "tion/v1/api.proto\032%ai/stigmer/iam/invita" +
      "tion/v1/io.proto2\247\003\n\033InvitationCommandCo" +
      "ntroller\022\254\001\n\006create\022(.ai.stigmer.iam.inv" +
      "itation.v1.Invitation\032(.ai.stigmer.iam.i" +
      "nvitation.v1.Invitation\"N\302\270\030J\010\004\020\036\"\014metad" +
      "ata.org*6unauthorized to create invitati" +
      "on in this organization\022d\n\006revoke\022*.ai.s" +
      "tigmer.iam.invitation.v1.InvitationId\032(." +
      "ai.stigmer.iam.invitation.v1.Invitation\"" +
      "\004\320\270\030\001\022m\n\006redeem\0223.ai.stigmer.iam.invitat" +
      "ion.v1.RedeemInvitationInput\032(.ai.stigme" +
      "r.iam.invitation.v1.Invitation\"\004\320\270\030\001\032\004\240\377" +
      "+\024B\243\001B\014CommandProtoP\001\242\002\004ASII\252\002\034Ai.Stigme" +
      "r.Iam.Invitation.V1\312\002\034Ai\\Stigmer\\Iam\\Inv" +
      "itation\\V1\342\002(Ai\\Stigmer\\Iam\\Invitation\\V" +
      "1\\GPBMetadata\352\002 Ai::Stigmer::Iam::Invita" +
      "tion::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ai.stigmer.commons.apiresource.RpcServiceOptionsProto.getDescriptor(),
          ai.stigmer.commons.rpc.MethodOptionsProto.getDescriptor(),
          ai.stigmer.iam.invitation.v1.ApiProto.getDescriptor(),
          ai.stigmer.iam.invitation.v1.IoProto.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    ai.stigmer.commons.apiresource.RpcServiceOptionsProto.getDescriptor();
    ai.stigmer.commons.rpc.MethodOptionsProto.getDescriptor();
    ai.stigmer.iam.invitation.v1.ApiProto.getDescriptor();
    ai.stigmer.iam.invitation.v1.IoProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(ai.stigmer.commons.apiresource.RpcServiceOptionsProto.apiResourceKind);
    registry.add(ai.stigmer.commons.rpc.MethodOptionsProto.config);
    registry.add(ai.stigmer.commons.rpc.MethodOptionsProto.isSkipAuthorization);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
