# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/stigmer/agentic/credential/v1/query.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai/stigmer/agentic/credential/v1/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.stigmer.agentic.credential.v1 import api_pb2 as ai_dot_stigmer_dot_agentic_dot_credential_dot_v1_dot_api__pb2
from ai.stigmer.agentic.credential.v1 import io_pb2 as ai_dot_stigmer_dot_agentic_dot_credential_dot_v1_dot_io__pb2
from ai.stigmer.agentic.credential.v1 import spec_pb2 as ai_dot_stigmer_dot_agentic_dot_credential_dot_v1_dot_spec__pb2
from ai.stigmer.commons.apiresource import io_pb2 as ai_dot_stigmer_dot_commons_dot_apiresource_dot_io__pb2
from ai.stigmer.commons.apiresource import rpc_service_options_pb2 as ai_dot_stigmer_dot_commons_dot_apiresource_dot_rpc__service__options__pb2
from ai.stigmer.commons.rpc import method_options_pb2 as ai_dot_stigmer_dot_commons_dot_rpc_dot_method__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,ai/stigmer/agentic/credential/v1/query.proto\x12 ai.stigmer.agentic.credential.v1\x1a*ai/stigmer/agentic/credential/v1/api.proto\x1a)ai/stigmer/agentic/credential/v1/io.proto\x1a+ai/stigmer/agentic/credential/v1/spec.proto\x1a\'ai/stigmer/commons/apiresource/io.proto\x1a\x38\x61i/stigmer/commons/apiresource/rpc_service_options.proto\x1a+ai/stigmer/commons/rpc/method_options.proto2\xee\x04\n\x19\x43redentialQueryController\x12\x93\x01\n\x03get\x12-.ai.stigmer.commons.apiresource.ApiResourceId\x1a,.ai.stigmer.agentic.credential.v1.Credential\"/\xc2\xb8\x18+\x08\x01\x10;\"\x05value*\x1eunauthorized to get credential\x12z\n\x0egetByReference\x12\x34.ai.stigmer.commons.apiresource.ApiResourceReference\x1a,.ai.stigmer.agentic.credential.v1.Credential\"\x04\xd0\xb8\x18\x01\x12\xc0\x01\n\x0brevealField\x12<.ai.stigmer.agentic.credential.v1.RevealCredentialFieldInput\x1a\x31.ai.stigmer.agentic.credential.v1.CredentialField\"@\xc2\xb8\x18<\x08\x10\x10;\"\rcredential_id*\'unauthorized to reveal credential field\x12v\n\x04list\x12\x36.ai.stigmer.agentic.credential.v1.ListCredentialsInput\x1a\x30.ai.stigmer.agentic.credential.v1.CredentialList\"\x04\xd0\xb8\x18\x01\x1a\x04\xa0\xff+;B\xd7\x01\n$com.ai.stigmer.agentic.credential.v1B\nQueryProtoP\x01\xa2\x02\x04\x41SAC\xaa\x02 Ai.Stigmer.Agentic.Credential.V1\xca\x02 Ai\\Stigmer\\Agentic\\Credential\\V1\xe2\x02,Ai\\Stigmer\\Agentic\\Credential\\V1\\GPBMetadata\xea\x02$Ai::Stigmer::Agentic::Credential::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.stigmer.agentic.credential.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$com.ai.stigmer.agentic.credential.v1B\nQueryProtoP\001\242\002\004ASAC\252\002 Ai.Stigmer.Agentic.Credential.V1\312\002 Ai\\Stigmer\\Agentic\\Credential\\V1\342\002,Ai\\Stigmer\\Agentic\\Credential\\V1\\GPBMetadata\352\002$Ai::Stigmer::Agentic::Credential::V1'
  _globals['_CREDENTIALQUERYCONTROLLER']._loaded_options = None
  _globals['_CREDENTIALQUERYCONTROLLER']._serialized_options = b'\240\377+;'
  _globals['_CREDENTIALQUERYCONTROLLER'].methods_by_name['get']._loaded_options = None
  _globals['_CREDENTIALQUERYCONTROLLER'].methods_by_name['get']._serialized_options = b'\302\270\030+\010\001\020;\"\005value*\036unauthorized to get credential'
  _globals['_CREDENTIALQUERYCONTROLLER'].methods_by_name['getByReference']._loaded_options = None
  _globals['_CREDENTIALQUERYCONTROLLER'].methods_by_name['getByReference']._serialized_options = b'\320\270\030\001'
  _globals['_CREDENTIALQUERYCONTROLLER'].methods_by_name['revealField']._loaded_options = None
  _globals['_CREDENTIALQUERYCONTROLLER'].methods_by_name['revealField']._serialized_options = b'\302\270\030<\010\020\020;\"\rcredential_id*\'unauthorized to reveal credential field'
  _globals['_CREDENTIALQUERYCONTROLLER'].methods_by_name['list']._loaded_options = None
  _globals['_CREDENTIALQUERYCONTROLLER'].methods_by_name['list']._serialized_options = b'\320\270\030\001'
  _globals['_CREDENTIALQUERYCONTROLLER']._serialized_start=359
  _globals['_CREDENTIALQUERYCONTROLLER']._serialized_end=981
# @@protoc_insertion_point(module_scope)
