// Provider and context
export { StigmerProvider, type StigmerProviderProps } from "./provider.js";
export { StigmerContext } from "./context.js";

// Runner adapter
export { type RunnerAdapter, useRunnerAdapter } from "./runner-adapter.js";
// Construction helper lives in @stigmer/sdk (framework-agnostic); re-exported
// here so React embedders import it alongside the adapter interface.
export { type RunnerWorkerHost, createRunnerAdapter } from "@stigmer/sdk";

// Fetch cache
export { FetchCacheProvider } from "./internal/FetchCacheProvider.js";
export type { FetchCacheOptions } from "./internal/fetch-cache.js";

// Hooks
export { useStigmer } from "./hooks.js";

// Color mode
export { ColorModeContext, useColorMode } from "./color-mode.js";
export type { ColorMode, ResolvedColorMode } from "./color-mode.js";

// Portal container
export { useStigmerPortalContainer } from "./portal-container.js";

// Deployment mode and resource availability
export {
  DeploymentModeContext,
  useDeploymentMode,
  useResourceAvailable,
} from "./deployment-mode.js";
export { type DeploymentMode, isResourceAvailable, ApiResourceKind } from "@stigmer/sdk";
export { CloudFeatureNotice, type CloudFeatureNoticeProps } from "./internal/CloudFeatureNotice.js";

// Models — data hook, styled components, and registry data
export {
  DEFAULT_MODEL_ID,
  DEFAULT_CURSOR_MODEL_ID,
  DISABLED_PROVIDERS,
  modelKey,
  parseModelKey,
  fetchModelRegistry,
  parseRegistryJson,
  useModelRegistry,
  ModelRegistryContext,
  ModelSelector,
  HarnessSelector,
  DEFAULT_HARNESS,
  HARNESS_LABELS,
  toProtoHarness,
  fromProtoHarness,
} from "./models/index.js";
export type {
  ModelInfo,
  ModelRegistryState,
  ParsedModelKey,
  Provider,
  CostTier,
  UseModelRegistryReturn,
  UseModelRegistryOptions,
  ModelSelectorProps,
  HarnessSelectorProps,
  HarnessOption,
} from "./models/index.js";

// Workspace — behavior hooks and styled components
export {
  useWorkspaceEntries,
  useWorkspaceFiles,
  useWorkspaceFileContent,
  useWorkspaceFileSearch,
  useWorkspaceContentSearch,
  useWorkspaceSources,
  MAX_WORKSPACE_FILE_READ_BYTES,
  WorkspaceFileNotFoundError,
  WorkspaceEditor,
  WorkspaceFileSearch,
  WorkspaceContentSearch,
  WorkspaceSummary,
  FileViewer,
  WorkspaceSurface,
  PanelChip,
  ExplorerTree,
  virtualEntryId,
  isVirtualEntryId,
} from "./workspace/index.js";
export type {
  WorkspaceEntry,
  WorkspaceFileEntry,
  WorkspaceFileLister,
  WorkspaceFileContent,
  WorkspaceFileReader,
  UseWorkspaceEntriesReturn,
  UseWorkspaceFilesOptions,
  UseWorkspaceFilesReturn,
  UseWorkspaceFileContentOptions,
  UseWorkspaceFileContentReturn,
  UseWorkspaceFileSearchOptions,
  UseWorkspaceFileSearchReturn,
  WorkspaceFileSearchGroup,
  WorkspaceFileMatch,
  WorkspaceFileSearchProps,
  WorkspaceContentMatch,
  WorkspaceContentSearchResult,
  WorkspaceContentSearcher,
  UseWorkspaceContentSearchOptions,
  UseWorkspaceContentSearchReturn,
  WorkspaceContentSearchGroup,
  WorkspaceContentSearchProps,
  FileViewerProps,
  FileViewerHandle,
  SelectedWorkspaceFile,
  UseWorkspaceSourcesOptions,
  UseWorkspaceSourcesReturn,
  WorkspaceEditorProps,
  WorkspaceSummaryProps,
  WorkspaceSurfaceProps,
  SurfaceRailView,
  SurfaceVirtualDocument,
  BuiltInViewId,
  PanelChipProps,
  ExplorerTreeProps,
  OpenEditor,
  OpenFileOptions,
  RevealTarget,
} from "./workspace/index.js";

// Session — data hooks, behavior hooks, utilities (Session aggregate + conversation lifecycle)
export {
  useCreateSession,
  useUpdateSession,
  useSession,
  useSessionList,
  useSessionExecutions,
  useSessionConversation,
  useSessionArtifacts,
  artifactKey,
  useSessionWriteBacks,
  useWorkspaceReadRefs,
  useSessionFileChanges,
  useSessionUsage,
  useAgentRefFromSession,
  useNewSessionFlow,
  useSessionPageFlow,
  usePersistedModel,
  useEditSessionPrep,
  CREATOR_AGENTS,
  parseDraftType,
  parseDraftParams,
  groupSessionsByTime,
  groupSearchResultsByTime,
  useSessionSearch,
  PENDING_SUBJECT,
  resolvedSubject,
  CHANNEL_SESSION_LABELS,
  isChannelOriginSession,
  channelSessionExternalUserKey,
  SessionViewer,
  NewSessionViewer,
  useSessionPanel,
  usePlanDraft,
  planDraftKey,
  PlanEditor,
  PlanStreamingDocument,
  PLAN_DOCUMENT_ENTRY_ID,
  PLAN_DOCUMENT_PATH,
  ARTIFACT_DOCUMENT_ENTRY_ID,
  SetupTab,
} from "./session/index.js";
export type {
  SharedSessionFields,
  CreateSessionInput,
  CreateSessionResult,
  UseCreateSessionReturn,
  UseUpdateSessionReturn,
  UseSessionReturn,
  UseSessionListOptions,
  UseSessionListReturn,
  UseSessionSearchOptions,
  UseSessionSearchReturn,
  UseSessionExecutionsReturn,
  SendFollowUpOptions,
  UseSessionConversationReturn,
  SessionArtifactEntry,
  UseSessionArtifactsReturn,
  SessionWriteBackEntry,
  UseSessionWriteBacksReturn,
  UseSessionFileChangesReturn,
  ModelCostEntry,
  UseSessionUsageReturn,
  UseAgentRefFromSessionReturn,
  UseNewSessionFlowOptions,
  UseNewSessionFlowReturn,
  UseSessionPageFlowOptions,
  UseSessionPageFlowReturn,
  UsePersistedModelOptions,
  UsePersistedModelReturn,
  UseEditSessionPrepReturn,
  DraftResourceType,
  DraftParams,
  SessionGroup,
  SearchResultGroup,
  SessionViewerProps,
  NewSessionViewerProps,
  SessionPanelController,
  UseSessionPanelOptions,
  PlanDraftController,
  PlanEditorProps,
  PlanStreamingDocumentProps,
  ExecutionTargetOption,
  RuntimeEnvProvider,
  SessionAudience,
  SetupTabProps,
  SetupTabMutationCallbacks,
} from "./session/index.js";

// Activity — unified recent activity (sessions + workflow executions)
export {
  useRecentActivity,
  groupRecentActivityByTime,
  formatRelativeTime,
  recentActivityStatusBadge,
} from "./activity/index.js";
export type {
  RecentActivityType,
  RecentActivityEntry,
  RecentActivityGroup,
  RecentActivityStatusBadge,
  UseRecentActivityOptions,
  UseRecentActivityReturn,
} from "./activity/index.js";

// Execution — behavior hooks, styled components, and utilities (AgentExecution aggregate)
export {
  isTerminalPhase,
  useCreateAgentExecution,
  useExecutionStream,
  useLiveAgentExecution,
  useAgentExecutionActions,
  useSubmitApproval,
  useFileReview,
  fileDecisionKey,
  fileReviewability,
  changeSetReviewability,
  deriveEffectiveVerdicts,
  changeForRowPath,
  fileReviewRowState,
  fileReviewRowChange,
  foldFileReviewEventStream,
  displayFileChangeSets,
  toDisplayFileChange,
  ExecutionPhaseBadge,
  InteractionModeBadge,
  SetupProgress,
  ExecutionProgress,
  TodoList,
  TodoCard,
  TodoInProgressIcon,
  findActiveTodo,
  todoCompletionSummary,
  UsageWidget,
  ContextGauge,
  SummarizationBadge,
  SummarizationCard,
  PlanCompletionCard,
  PlanArtifactCard,
  PlanStreamingCard,
  PlanDocumentMessage,
  useContextWindow,
  formatCost,
  formatTokenCount,
  ToolCallGroup,
  ToolCallDetail,
  ResultView,
  summarizeResultView,
  TerminalSession,
  useToolPresentation,
  registerToolPresenter,
  getToolPresenter,
  resolveToolCategory,
  resolveToolCategoryFromCall,
  resolveToolCategoryFromKind,
  toolKindToCategoryInfo,
  defaultDisclosureForCategory,
  extractPrimaryArg,
  McpToolDetail,
  parseMcpResult,
  formatDuration,
  humanizeToolName,
  ToolCallItem,
  SubAgentSection,
  MessageEntry,
  MessageThread,
  ThreadSkeleton,
  FollowUpInput,
  ApprovalCard,
  ApprovalCardHeader,
  ApprovalCardBody,
  FileReviewCard,
  FileReviewDock,
  FileChangeProgressBar,
  ApprovalContext,
  useApproval,
  FileReviewContext,
  useFileReviewRowState,
  useFileReviewRowChange,
  ArtifactRow,
  ArtifactRowView,
  fromExecutionArtifact,
  fromArtifact,
  ArtifactContentRenderer,
  ArtifactContentBody,
  ArtifactFileContent,
  ArtifactDocument,
  useArtifactInspection,
  ArtifactPreviewContent,
  ArtifactPreviewModal,
  ArtifactsWidget,
  WriteBacksWidget,
  ToolArgsView,
  McpArgsView,
  McpMetadataRow,
  FilePathLink,
  FilePathContext,
  classifyPath,
  resolveGitBrowseUrl,
  resolvePathAction,
  useSessionVariables,
  SessionVariablesInput,
  useExecutionArtifacts,
  useArtifactContent,
  useArtifactContentById,
  useArtifactDownloadUrl,
  useArtifactDownload,
  useArtifactCopy,
  useToolOutputContent,
  useFileChangeContent,
  execIdFromStorageKey,
  useWorkspaceWriteBacks,
  WriteBackCard,
  parseDiffStatSummary,
  trailingDiffStatLine,
  writeBackDisplayName,
  FileChangesView,
  FileChangeDiff,
  deriveExecutionFileChanges,
  toFileDiffEntry,
  FILE_CHANGE_DOCUMENT_ENTRY_ID,
  fileChangeTabPath,
  EmptyChangeNotice,
  isTextArtifact,
  formatArtifactSize,
  getArtifactExtension,
  getFileExtension,
  getArtifactRenderMode,
} from "./execution/index.js";
export type {
  BootstrapSessionSpec,
  CreateAgentExecutionInput,
  CreateAgentExecutionResult,
  SharedAgentExecutionFields,
  UseCreateAgentExecutionReturn,
  UseExecutionStreamReturn,
  UseLiveAgentExecutionOptions,
  UseLiveAgentExecutionReturn,
  UseAgentExecutionActionsOptions,
  UseAgentExecutionActionsReturn,
  UseSubmitApprovalReturn,
  UseFileReviewReturn,
  FileDecisionOptions,
  FileReviewability,
  FileBlockReason,
  ChangeSetReviewability,
  FileReviewRowState,
  ExecutionPhaseBadgeProps,
  InteractionModeBadgeProps,
  SetupProgressProps,
  ExecutionProgressProps,
  TodoListProps,
  TodoCardProps,
  UsageWidgetProps,
  ContextGaugeProps,
  SummarizationBadgeProps,
  SummarizationCardProps,
  PlanCompletionCardProps,
  PlanArtifactCardProps,
  PlanStreamingCardProps,
  PlanDocumentMessageProps,
  ContextHealth,
  SummarizationEventView,
  UseContextWindowReturn,
  ToolCallGroupProps,
  ToolCallDetailProps,
  ResultViewProps,
  TerminalSessionProps,
  ToolPresentation,
  ToolPresenter,
  ToolDisclosure,
  McpToolDetailProps,
  McpArgsViewProps,
  McpMetadataRowProps,
  ToolArgsViewProps,
  ToolCallItemProps,
  SubAgentSectionProps,
  MessageEntryProps,
  MessageThreadProps,
  ThreadContentColumn,
  ThreadSkeletonProps,
  FollowUpInputProps,
  ApprovalCardProps,
  ApprovalCardHeaderProps,
  ApprovalCardBodyProps,
  FileReviewCardProps,
  FileReviewDockProps,
  FileChangeProgressBarProps,
  ApprovalContextValue,
  UseApprovalResult,
  FileReviewContextValue,
  ArtifactRowProps,
  ArtifactRowViewProps,
  ArtifactRowItem,
  ArtifactContentRendererProps,
  ArtifactContentBodyProps,
  ArtifactFileContentProps,
  ArtifactDocumentProps,
  ArtifactInspection,
  UseArtifactInspectionOptions,
  ArtifactRenderMode,
  ArtifactPreviewContentProps,
  ArtifactPreviewModalProps,
  ArtifactsWidgetProps,
  WriteBacksWidgetProps,
  FilePathLinkProps,
  FilePathContextValue,
  PathClassification,
  ResolvedPathAction,
  SessionVariableEntry,
  UseSessionVariablesReturn,
  SessionVariablesInputProps,
  UseExecutionArtifactsReturn,
  UseArtifactContentReturn,
  UseArtifactContentByIdReturn,
  UseArtifactDownloadUrlReturn,
  UseArtifactDownloadUrlOptions,
  UseArtifactDownloadReturn,
  UseArtifactCopyReturn,
  UseToolOutputContentReturn,
  ToolOutputRefLike,
  UseFileChangeContentReturn,
  UseWorkspaceWriteBacksReturn,
  WriteBackCardProps,
  DiffStatSummary,
  FileChangesViewProps,
  FileChangeDiffProps,
  EmptyChangeNoticeProps,
  EmptyChangeKind,
} from "./execution/index.js";

// Execution — proto type re-exports for artifact consumers
export type { ExecutionArtifact } from "@stigmer/protos/ai/stigmer/agentic/agentexecution/v1/artifact_pb";
export { ExecutionArtifactKind } from "@stigmer/protos/ai/stigmer/agentic/agentexecution/v1/enum_pb";

// Attachment — file upload behavior hook and styled chip list
export {
  useAttachments,
  AttachmentChipList,
  MAX_ATTACHMENT_BYTES,
  detectContentType,
  formatFileSize,
  validateAttachmentSize,
} from "./attachment/index.js";
export type {
  AttachmentPhase,
  AttachmentEntry,
  UseAttachmentsOptions,
  UseAttachmentsReturn,
  AttachmentChipListProps,
} from "./attachment/index.js";

// File Reference — workspace file-reference behavior hook and styled chip list
export {
  useFileReferences,
  FileReferenceChipList,
} from "./file-reference/index.js";
export type {
  UseFileReferencesReturn,
  FileReferenceChipListProps,
} from "./file-reference/index.js";
export { FILE_REF_MIME } from "./internal/file-tree/index.js";

// Composer — unified message input with model, workspace, and file attachments
export {
  useComposer,
  SessionComposer,
  InteractionModePicker,
} from "./composer/index.js";
export type {
  UseComposerOptions,
  UseComposerReturn,
  SessionComposerHandle,
  SessionComposerProps,
  SessionComposerSubmitContext,
  InteractionModePickerProps,
  InteractionModeOption,
} from "./composer/index.js";

// MCP Server — data hook, count hook, list hook, search hook, picker, config panel, tool selector, detail view, setup orchestration, OAuth connect, and update
export {
  useMcpServer,
  useMcpServerCount,
  useMcpServerList,
  useMcpServerSearch,
  useMcpServerSetup,
  useMcpServerConnect,
  useMcpServerOAuthConnect,
  useMcpServerCredentials,
  useOAuthGrantStatus,
  useDisconnectOAuth,
  OAuthCallbackHandler,
  McpServerPicker,
  McpServerConfigPanel,
  McpServerDetailView,
  McpServerConnectDialog,
  McpServerCreationWizard,
  McpToolSelector,
  useCreateMcpServer,
  useUpdateMcpServer,
  mcpServerToInput,
  toServerKey,
} from "./mcp-server/index.js";
export type {
  UseMcpServerReturn,
  UseMcpServerCountOptions,
  UseMcpServerCountReturn,
  UseMcpServerListOptions,
  UseMcpServerListReturn,
  UseMcpServerSearchOptions,
  UseMcpServerSearchReturn,
  UseMcpServerSetupReturn,
  SubmitMcpEnvVarsOptions,
  McpServerSetupEntry,
  McpServerSetupPhase,
  McpServerSetupState,
  McpServerPickerProps,
  McpServerSetupIntegration,
  McpServerConfigPanelProps,
  McpServerCredentialsProps,
  McpServerOAuthSignInProps,
  McpServerDetailViewProps,
  McpServerConnectDialogProps,
  CapabilityTab,
  McpToolSelectorProps,
  UseMcpServerConnectReturn,
  UseMcpServerOAuthConnectReturn,
  OAuthConnectPhase,
  OAuthCallbackHandlerProps,
  OAuthCallbackParams,
  UseMcpServerCredentialsReturn,
  UseOAuthGrantStatusReturn,
  UseDisconnectOAuthReturn,
  McpServerAuthMode,
  UseCreateMcpServerReturn,
  UseUpdateMcpServerReturn,
  McpServerCreationWizardProps,
  McpServerCreationResult,
  McpServerWizardData,
} from "./mcp-server/index.js";

// Skill — data hooks, upload, file browser, and mutation
export {
  useSkill,
  useSkillCount,
  useSkillList,
  useSkillSearch,
  SkillPicker,
  SkillDetailView,
  usePushSkill,
  useSkillUpload,
  useSkillArtifact,
  useSkillVersions,
  useSkillDiff,
  useSkillDuplicateCheck,
  SkillUploader,
  SkillFileBrowser,
  SkillDiffDialog,
} from "./skill/index.js";
export type {
  UseSkillReturn,
  UseSkillCountOptions,
  UseSkillCountReturn,
  UseSkillListOptions,
  UseSkillListReturn,
  UseSkillSearchOptions,
  UseSkillSearchReturn,
  SkillPickerProps,
  SkillDetailViewProps,
  PushSkillInput,
  UsePushSkillReturn,
  SkillUploadPreview,
  SkillFileEntry,
  UseSkillUploadReturn,
  UseSkillArtifactReturn,
  UseSkillVersionsReturn,
  UseSkillDiffReturn,
  UseSkillDuplicateCheckReturn,
  SkillDiffDialogProps,
  SkillDiffDialogState,
  SkillUploaderProps,
  SkillFileBrowserProps,
} from "./skill/index.js";

// GitHub — OAuth connection, repo picker, tree lister, and hooks
export {
  useGitHubConnection,
  useGitHubRepos,
  useGitHubSearch,
  useGitHubTreeLister,
  useGitHubFileReader,
  parseGitUrl,
  GitHubRepoPicker,
  GITHUB_CALLBACK_MESSAGE_TYPE,
} from "./github/index.js";
export type {
  GitHubUser,
  GitHubConnectOptions,
  UseGitHubConnectionConfig,
  UseGitHubConnectionReturn,
  GitHubRepo,
  GitHubBranch,
  UseGitHubReposReturn,
  UseGitHubSearchReturn,
  GitHubRepoPickerProps,
  ParsedGitRepo,
} from "./github/index.js";

// Agent — data hook, count hook, list hook, search hook, picker, detail view, env form, setup orchestration, env diffing, default agent, creation wizard, update
export {
  useAgent,
  useAgentCount,
  useAgentList,
  useAgentSearch,
  AgentPicker,
  AgentDetailView,
  AgentEnvForm,
  diffEnv,
  useAgentSetup,
  useDefaultAgent,
  useCreateAgent,
  useUpdateAgent,
  agentToInput,
  AgentCreationWizard,
} from "./agent/index.js";
export type {
  UseAgentReturn,
  UseAgentCountOptions,
  UseAgentCountReturn,
  UseAgentListOptions,
  UseAgentListReturn,
  UseAgentSearchOptions,
  UseAgentSearchReturn,
  AgentPickerProps,
  AgentDetailViewProps,
  AgentEnvFormProps,
  AgentEnvFormSubmitOptions,
  AgentEnvFormVariable,
  AgentSetupResult,
  AgentSetupReadyResult,
  AgentSetupState,
  AgentSetupPhase,
  AgentResolution,
  SubmitEnvVarsOptions,
  UseAgentSetupReturn,
  UseDefaultAgentReturn,
  UseCreateAgentReturn,
  UseUpdateAgentReturn,
  AgentCreationWizardProps,
  AgentCreationResult,
  AgentWizardData,
} from "./agent/index.js";

// Environment — data hooks, list hook, personal convenience hook, secret reveal, variable management, env var form, system env vars, and styled components
export {
  useEnvironment,
  useEnvironmentList,
  usePersonalEnvironment,
  useCreateEnvironment,
  useUpdateEnvironment,
  useUpdateEnvironmentVariables,
  useRemoveEnvironmentVariables,
  useRevealSecretValue,
  EnvironmentVariableEditor,
  EnvironmentListPanel,
  CreateEnvironmentForm,
  EnvVarForm,
  useSessionEnvPool,
  SYSTEM_ENV_VAR_KEYS,
  toGrpcAddress,
  buildSystemEnvVars,
  resolveSystemEnvVarValues,
  resolveDeclaredSystemEnvVars,
  EnvironmentPicker,
  useToolCredentialsReadiness,
} from "./environment/index.js";
export type {
  UseEnvironmentReturn,
  UseEnvironmentListReturn,
  UsePersonalEnvironmentReturn,
  UseCreateEnvironmentReturn,
  UseUpdateEnvironmentReturn,
  UpdateEnvironmentVariablesInput,
  UseUpdateEnvironmentVariablesReturn,
  RemoveEnvironmentVariablesInput,
  UseRemoveEnvironmentVariablesReturn,
  UseRevealSecretValueOptions,
  UseRevealSecretValueReturn,
  EnvironmentVariableEditorProps,
  EnvironmentListPanelProps,
  CreateEnvironmentFormProps,
  EnvVarFormProps,
  EnvVarFormVariable,
  EnvVarFormSubmitOptions,
  SessionEnvPoolInput,
  UseSessionEnvPoolReturn,
  EnvironmentPickerProps,
  ToolCredentialsReadiness,
} from "./environment/index.js";

// Identity Account — gate hook for ensuring the caller's identity account exists before app render
export {
  useIdentityAccountGate,
} from "./identity-account/index.js";
export type {
  IdentityAccountGateState,
  UseIdentityAccountGateReturn,
} from "./identity-account/index.js";

// IAM Policy — data hooks, behavior hooks, headless hook, and styled components for access management
export {
  useGrantableRoles,
  useRoleSelector,
  useResourceAccess,
  usePrincipalsCount,
  useWhoAmI,
  useCreateIamPolicy,
  useDeleteIamPolicy,
  useRevokeOrgAccess,
  useShareFlow,
  useCheckPermission,
  RoleSelector,
  PrincipalPicker,
  ProviderBadge,
  providerLabel,
  GrantAccessForm,
  PeopleWithAccess,
  OrgMembersPanel,
  SharePanel,
  PermissionGate,
} from "./iam-policy/index.js";
export type {
  UseGrantableRolesReturn,
  RoleOption,
  UseRoleSelectorReturn,
  ResourceAccessRef,
  UseResourceAccessOptions,
  UseResourceAccessReturn,
  UsePrincipalsCountReturn,
  UseWhoAmIReturn,
  UseCreateIamPolicyReturn,
  UseDeleteIamPolicyReturn,
  UseRevokeOrgAccessReturn,
  UseShareFlowReturn,
  ShareFlowResource,
  UseCheckPermissionReturn,
  PermissionCheckResource,
  RoleSelectorProps,
  PrincipalPickerProps,
  SelectedPrincipal,
  ProviderBadgeProps,
  GrantAccessFormProps,
  PeopleWithAccessProps,
  OrgMembersPanelProps,
  SharePanelProps,
  PermissionGateProps,
} from "./iam-policy/index.js";

// Access — unified "Manage access" experience (visibility + people) as one
// dialog, with a kebab hook and a visible-button trigger.
export {
  ManageAccessDialog,
  ManageAccessButton,
  useManageAccess,
} from "./access/index.js";
export type {
  ManageAccessDialogProps,
  ManageAccessButtonProps,
  UseManageAccessArgs,
  UseManageAccessReturn,
  AccessResource,
  AccessVisibility,
  AccessExtraSection,
} from "./access/index.js";

// Organization — context provider, hooks, data hooks, behavior hooks, styled form, profile panel, and org switcher
export {
  OrgProvider,
  useOrg,
  useActiveOrgSlug,
  useActiveOrgId,
  useOrgGate,
  useOrganization,
  useCreateOrganization,
  useUpdateOrganization,
  CreateOrganizationForm,
  OrgProfilePanel,
  OrgSwitcher,
} from "./organization/index.js";
export type {
  OrgContextValue,
  UseOrgGateOptions,
  OrgGateState,
  UseOrgGateReturn,
  UseOrganizationReturn,
  UseCreateOrganizationReturn,
  UseUpdateOrganizationReturn,
  CreateOrganizationFormProps,
  OrgProfilePanelProps,
  OrgSwitcherProps,
} from "./organization/index.js";

// Billing — data hooks, behavior hooks, styled components, catalog, and formatting utilities
export {
  useBillingAccount,
  useCreditLedger,
  useBillingUsageReport,
  useCustomerModelPricing,
  usePricingGovernance,
  useModelPricingBaselines,
  useCreateCheckoutSession,
  useCreateBillingPortalSession,
  useSetAutoRechargeConfig,
  useDecidePricingOverride,
  useUpsertModelPricingBaseline,
  useRetireModelPricingBaseline,
  BillingSection,
  CreditBalanceCard,
  PaymentMethodCard,
  AutoRechargeCard,
  CreditPackGrid,
  CreditLedgerTable,
  LowBalanceBanner,
  PricingGovernancePanel,
  ModelCatalogPanel,
  CREDIT_PACKS,
  formatPackPrice,
  formatCreditCount,
  formatCreditBalance,
  formatLedgerAmount,
  ledgerEntryLabel,
  isCredit,
  isHold,
  formatLedgerDate,
} from "./billing/index.js";
export type {
  UseBillingAccountReturn,
  UseCreditLedgerReturn,
  UseCreditLedgerOptions,
  UseBillingUsageReportReturn,
  UseCustomerModelPricingReturn,
  UsePricingGovernanceReturn,
  UseModelPricingBaselinesOptions,
  UseModelPricingBaselinesReturn,
  CreateCheckoutSessionInput,
  UseCreateCheckoutSessionReturn,
  UseCreateBillingPortalSessionReturn,
  SetAutoRechargeConfigInput,
  UseSetAutoRechargeConfigReturn,
  DecidePricingOverrideInput,
  UseDecidePricingOverrideReturn,
  UpsertModelPricingBaselineInput,
  UseUpsertModelPricingBaselineReturn,
  RetireModelPricingBaselineInput,
  UseRetireModelPricingBaselineReturn,
  BillingSectionProps,
  CreditBalanceCardProps,
  PaymentMethodCardProps,
  AutoRechargeCardProps,
  CreditPackGridProps,
  CreditLedgerTableProps,
  LowBalanceBannerProps,
  PricingGovernancePanelProps,
  ModelCatalogPanelProps,
  CreditPackInfo,
} from "./billing/index.js";

// Settings — navigation structure + section components shared across app shells
export { SETTINGS_NAV_GROUPS } from "./settings/index.js";
export type { SettingsNavItem, SettingsNavGroup } from "./settings/index.js";
export { ApiKeysSection } from "./settings/index.js";
export { MembersSection } from "./settings/index.js";
export { OrgProfileSection } from "./settings/index.js";
export { EnvironmentsSection } from "./settings/index.js";
export { InvitationsSection } from "./settings/index.js";
export { IdentityProvidersSection } from "./settings/index.js";
export type { IdentityProvidersSectionProps } from "./settings/index.js";
export { PlatformClientsSection } from "./settings/index.js";
export { OAuthAppsSection } from "./settings/index.js";
export { ChannelAppsSection } from "./settings/index.js";
export { UsageSection } from "./settings/index.js";

// User — app shell user menu
export { UserMenu } from "./user/index.js";
export type { UserMenuProps } from "./user/index.js";

// API Key — data hooks, behavior hooks, and styled components for API key lifecycle
export {
  useApiKeyList,
  useCreateApiKey,
  useDeleteApiKey,
  ApiKeyListPanel,
  CreateApiKeyForm,
  ApiKeyCreatedAlert,
} from "./api-key/index.js";
export type {
  UseApiKeyListReturn,
  UseCreateApiKeyReturn,
  UseDeleteApiKeyReturn,
  ApiKeyListPanelProps,
  CreateApiKeyFormProps,
  ApiKeyCreatedAlertProps,
} from "./api-key/index.js";

// Platform Client — data hooks, mutation hooks, and styled components for platform client lifecycle
export {
  usePlatformClientList,
  usePlatformClient,
  useCreatePlatformClient,
  useUpdatePlatformClient,
  useDeletePlatformClient,
  useRotatePlatformClientSecret,
  PlatformClientListPanel,
  CreatePlatformClientForm,
  PlatformClientDetailPanel,
  PlatformClientSecretAlert,
} from "./platform-client/index.js";
export type {
  UsePlatformClientListReturn,
  UsePlatformClientReturn,
  UseCreatePlatformClientReturn,
  UseUpdatePlatformClientReturn,
  UseDeletePlatformClientReturn,
  UseRotatePlatformClientSecretReturn,
  PlatformClientListPanelProps,
  CreatePlatformClientFormProps,
  PlatformClientDetailPanelProps,
  PlatformClientSecretAlertProps,
} from "./platform-client/index.js";

// OAuth App — data hooks, mutation hooks, and styled components for OAuth app management
export {
  useOAuthAppList,
  useCreateOAuthApp,
  useUpdateOAuthApp,
  useDeleteOAuthApp,
  OAuthAppListPanel,
  CreateOAuthAppForm,
  OAuthAppDetailPanel,
} from "./oauth-app/index.js";
export type {
  UseOAuthAppListReturn,
  UseCreateOAuthAppReturn,
  UseUpdateOAuthAppReturn,
  UseDeleteOAuthAppReturn,
  OAuthAppListPanelProps,
  CreateOAuthAppFormProps,
  OAuthAppDetailPanelProps,
} from "./oauth-app/index.js";

// Channel App — data hooks, mutation hooks, styled components, and Slack
// setup helpers for bring-your-own channel apps (T04 item 2)
export {
  useChannelAppList,
  useCreateChannelApp,
  useUpdateChannelApp,
  useDeleteChannelApp,
  ChannelAppListPanel,
  CreateChannelAppForm,
  ChannelAppDetailPanel,
  buildSlackChannelAppManifest,
  slackChannelAppRedirectUrl,
  slackChannelAppWebhookUrl,
  SLACK_CHANNEL_APP_BOT_EVENTS,
  SLACK_CHANNEL_APP_BOT_SCOPES,
} from "./channel-app/index.js";
export type {
  UseChannelAppListReturn,
  UseCreateChannelAppReturn,
  UseUpdateChannelAppReturn,
  UseDeleteChannelAppReturn,
  ChannelAppListPanelProps,
  CreateChannelAppFormProps,
  ChannelAppDetailPanelProps,
  SlackChannelAppManifestInput,
} from "./channel-app/index.js";

// Identity Provider — data hooks, mutation hooks, styled components, presets, and guided wizard for IdP management and SSO discovery
export {
  useIdentityProviderList,
  useIdentityProvider,
  useSsoProvider,
  useCreateIdentityProvider,
  useUpdateIdentityProvider,
  useDeleteIdentityProvider,
  IdentityProviderListPanel,
  CreateIdentityProviderForm,
  PROVIDER_PRESETS,
  getPreset,
  ProviderPicker,
  IdentityProviderWizard,
  IdentityProviderDetailPanel,
  SsoLoginPrompt,
} from "./identity-provider/index.js";
export type {
  UseIdentityProviderListReturn,
  UseIdentityProviderReturn,
  UseSsoProviderReturn,
  UseCreateIdentityProviderReturn,
  UseUpdateIdentityProviderReturn,
  UseDeleteIdentityProviderReturn,
  IdentityProviderListPanelProps,
  CreateIdentityProviderFormProps,
  ProviderPreset,
  ProviderVariable,
  ProviderConfig,
  ProviderPickerProps,
  IdentityProviderWizardProps,
  IdentityProviderDetailPanelProps,
  SsoLoginPromptProps,
} from "./identity-provider/index.js";

// Invitation — data hooks, behavior hooks, and feature components for org invite links
export {
  useOrgInvitations,
  useCreateInvitation,
  useRevokeInvitation,
  useInvitationPreview,
  useRedeemInvitation,
  InvitationCreatedAlert,
  InvitationManager,
  InvitationRedemption,
} from "./invitation/index.js";
export type {
  UseOrgInvitationsReturn,
  UseCreateInvitationReturn,
  UseRevokeInvitationReturn,
  UseInvitationPreviewReturn,
  UseRedeemInvitationReturn,
  InvitationCreatedAlertProps,
  InvitationManagerProps,
  InvitationRedemptionProps,
} from "./invitation/index.js";

// Sharing — shared-agent public profile, the anonymous-visitor chat organism,
// and the owner-side Share experience (Shares tab list, dialog, AgentShare hooks).
export {
  useSharedAgentProfile,
  SharedAgentChat,
  draftFromShare,
  sharingAudienceFromProto,
  useAgentShares,
  useCanCreateAgentShare,
  useSaveAgentShare,
  useDeleteAgentShare,
  useRotateShareLink,
  ShareAgentDialog,
  AgentShareList,
  useShareToolReadiness,
  validateOrigin,
  MAX_ALLOWED_ORIGINS,
} from "./sharing/index.js";
export type {
  UseSharedAgentProfileOptions,
  UseSharedAgentProfileReturn,
  SharedAgentChatProps,
  AgentShareCreateIdentity,
  AgentShareDraft,
  SharingAudience,
  UseAgentSharesReturn,
  UseCanCreateAgentShareReturn,
  UseSaveAgentShareReturn,
  UseDeleteAgentShareReturn,
  UseRotateShareLinkReturn,
  ShareAgentDialogProps,
  AgentShareListProps,
  ShareToolReadiness,
} from "./sharing/index.js";

// Channel — agent channels on external messaging platforms (Slack + WhatsApp):
// the Channels tab panel, the per-provider connect dialogs, and the
// AgentChannel hooks.
export {
  useAgentChannelList,
  useAgentChannel,
  useSaveAgentChannel,
  agentChannelToInput,
  useCreateAgentChannel,
  useDeleteAgentChannel,
  useConnectSlackChannel,
  useInstallChannel,
  useChannelToolReadiness,
  useChannelSessions,
  AgentChannelsPanel,
  ConnectSlackDialog,
  ConnectWhatsAppDialog,
  ChannelCredentialsDialog,
  ChannelToolCredentials,
  ChannelConversationsDialog,
} from "./channel/index.js";
export type {
  UseAgentChannelListReturn,
  UseAgentChannelReturn,
  UseSaveAgentChannelReturn,
  UseCreateAgentChannelReturn,
  UseDeleteAgentChannelReturn,
  UseConnectSlackChannelReturn,
  SlackConnectPhase,
  UseInstallChannelReturn,
  InstallChannelPhase,
  UseChannelSessionsReturn,
  AgentChannelsPanelProps,
  ConnectSlackDialogProps,
  ConnectWhatsAppDialogProps,
  ChannelCredentialsDialogProps,
  ChannelToolCredentialsProps,
  ChannelConversationsDialogProps,
} from "./channel/index.js";

// Error — structured error display with classification, retry, and contextual guidance
export { ErrorMessage, SecretFlowErrorGuide, isSecretFlowError } from "./error/index.js";
export type { ErrorMessageProps, SecretFlowErrorGuideProps } from "./error/index.js";

// Library — cross-resource UI components, resource detection, apply flow, browsing, and visibility management
export {
  LibraryBreadcrumbProvider,
  useBreadcrumbLabel,
  useBreadcrumbOverride,
  ScopeToggle,
  ResourceCountCard,
  detectStigmerResource,
  useDetectStigmerResource,
  isSkillPackage,
  detectSkillPackage,
  useDetectSkillPackage,
  isPlanArtifact,
  isPlanArtifactName,
  findPlanArtifact,
  findLatestSessionPlan,
  findStreamingPlan,
  PLAN_ARTIFACT_NAME,
  PLAN_ARTIFACT_SUFFIX,
  useApplyResource,
  useExportResource,
  VisibilitySelector,
  VisibilityBadge,
  blueprintVisibilityLevels,
  INSTANCE_VISIBILITY_LEVELS,
  visibilityLabel,
  useUpdateVisibility,
} from "./library/index.js";
export type {
  ScopeToggleProps,
  ResourceCountCardProps,
  StigmerResourceKind,
  StigmerResourceDetection,
  SkillPackageDetection,
  SessionPlan,
  StreamingPlan,
  UseDetectSkillPackageReturn,
  UseApplyResourceReturn,
  ApplyResourceResult,
  PushSkillParams,
  UseExportResourceOptions,
  UseExportResourceReturn,
  VisibilitySelectorProps,
  VisibilityBadgeProps,
  VisibilityLevelOption,
  BlueprintVisibilityLevelsContext,
  VisibilityResourceKind,
  UseUpdateVisibilityReturn,
} from "./library/index.js";

// Manifest — kind-agnostic YAML edit/apply (editor, hooks, dialogs)
export {
  YamlEditor,
  useEditResourceYaml,
  useApplyManifest,
  EditResourceYamlDialog,
  ApplyManifestDialog,
  RedactedSecretsNotice,
} from "./manifest/index.js";
export type {
  YamlEditorProps,
  EditYamlTarget,
  EditYamlValidation,
  UseEditResourceYamlOptions,
  UseEditResourceYamlReturn,
  ManifestEntryStatus,
  ManifestPreviewEntry,
  UseApplyManifestReturn,
  EditResourceYamlDialogProps,
  ApplyManifestDialogProps,
  RedactedSecretsNoticeProps,
} from "./manifest/index.js";

// Action menu — compound component for resource item actions
export { ActionMenu } from "./action-menu/index.js";
export type {
  ActionMenuProps,
  ActionMenuTriggerProps,
  ActionMenuContentProps,
  ActionMenuItemProps,
  ActionMenuSeparatorProps,
  ActionMenuGroupProps,
} from "./action-menu/index.js";

// Feedback — toast notification system wrapping Sonner
export { StigmerToaster, toast } from "./feedback/index.js";
export type { StigmerToasterProps } from "./feedback/index.js";

// Empty state — reusable empty/zero/permission/error state primitives
export { EmptyState, useEmptyState } from "./empty-state/index.js";
export type {
  EmptyStateVariant,
  EmptyStateAction,
  EmptyStateProps,
  UseEmptyStateOptions,
  UseEmptyStateReturn,
} from "./empty-state/index.js";

// Search — shared search/list/count infrastructure re-exported for public API surface
export type {
  UseResourceSearchOptions,
  UseResourceSearchReturn,
} from "./search/index.js";

// Usage — org-level usage report hook, dashboard panel, and date-range utilities
export {
  useOrgUsageReport,
  OrgUsagePanel,
  CreditRunwayIndicator,
  AgentBreakdownList,
  HarnessSplitCard,
  useExportCSV,
  ExportButton,
  DATE_RANGE_PRESETS,
  dateRangeFromPreset,
  formatDateRange,
  presetLabel,
} from "./usage/index.js";
export type {
  UseOrgUsageReportReturn,
  OrgUsagePanelProps,
  CreditRunwayIndicatorProps,
  AgentBreakdownListProps,
  HarnessSplitCardProps,
  UseExportCSVReturn,
  ExportFormat,
  ExportButtonProps,
  DateRange,
  DateRangePreset,
} from "./usage/index.js";

// Agent Instance — data hooks, mutation hooks, management components, and behavior hook
export {
  useAgentInstance,
  useAgentInstanceList,
  useAgentInstances,
  usePersonalAgentInstance,
  useCreateAgentInstance,
  useUpdateAgentInstance,
  useDeleteAgentInstance,
  AgentInstanceList,
  AgentInstanceEmptyState,
  CreateAgentInstanceDialog,
  AgentInstanceDetailPanel,
} from "./agent-instance/index.js";
export type {
  UseAgentInstanceReturn,
  UseAgentInstanceListReturn,
  UseAgentInstancesReturn,
  GetOrCreatePersonalInstanceInput,
  UsePersonalAgentInstanceReturn,
  UseCreateAgentInstanceReturn,
  UseUpdateAgentInstanceReturn,
  UseDeleteAgentInstanceReturn,
  AgentInstanceListProps,
  AgentInstanceEmptyStateProps,
  CreateAgentInstanceDialogProps,
  AgentInstanceDetailPanelProps,
} from "./agent-instance/index.js";

// Tabs — accessible tabbed panel primitive
export { Tabs } from "./tabs/index.js";
export type { TabsProps, TabItem } from "./tabs/index.js";

// Switch — accessible on/off toggle primitive (WAI-ARIA Switch pattern)
export { Switch } from "./switch/index.js";
export type { SwitchProps } from "./switch/index.js";

// Button — shared action primitive (variants for the console's action tiers)
export { Button } from "./button/index.js";
export type { ButtonProps, ButtonSize, ButtonVariant } from "./button/index.js";

// Resource Detail — headless hooks, action bar, and composed shell for resource detail pages
export {
  useCopyResource,
  useConfirmAction,
  useDeleteResource,
  ResourceActionBar,
  ResourceDetailShell,
  Section,
  ConfirmDialog,
} from "./resource-detail/index.js";
export type {
  AdditionalTab,
  DetailAction,
  ResourceHeaderMeta,
  ConfirmOptions,
  ConfirmState,
  ResourceDetailShellProps,
  SectionProps,
  UseCopyResourceReturn,
  UseConfirmActionReturn,
  DeletableResourceKind,
  UseDeleteResourceReturn,
  ResourceActionBarProps,
  ConfirmDialogProps,
} from "./resource-detail/index.js";

// Resource Creation — shared wizard infrastructure for multi-step creation flows
export {
  useWizardState,
  useTemplateFilter,
  WizardShell,
  WizardNav,
  StepIndicator,
  TemplateCard,
  TemplateGallery,
  CreationPicker,
  TEMPLATE_CATEGORY_LABELS,
  AGENT_TEMPLATES,
  MCP_SERVER_TEMPLATES,
  WORKFLOW_TEMPLATES,
} from "./resource-creation/index.js";
export type {
  EnvVarEntry,
  KeyValueEntry,
  WizardStepDef,
  WizardState,
  WizardShellProps,
  UseWizardStateOptions,
  UseWizardStateReturn,
  UseTemplateFilterOptions,
  UseTemplateFilterReturn,
  WizardNavProps,
  StepIndicatorProps,
  ResourceTemplate,
  TemplateCategory,
  TemplateCardProps,
  TemplateGalleryProps,
  CreationPickerProps,
  CreationPath,
} from "./resource-creation/index.js";

// Dependency Graph — visual tree of agent dependencies (MCP servers, skills, sub-agents)
export { DependencyGraph, useDependencyGraph } from "./dependency-graph/index.js";
export type {
  NodeKind,
  DependencyNode,
  DependencyTree,
  DependencyGraphProps,
  UseDependencyGraphOptions,
  UseDependencyGraphReturn,
} from "./dependency-graph/index.js";

// Version History — generic timeline, diff infrastructure for versioned resources
export {
  VersionTimeline,
  VersionTimelineEntry,
  DiffViewer,
  DiffFileList,
  DiffSummary,
  MultiFileDiffView,
  computeDiff,
  computeMultiFileDiff,
} from "./version-history/index.js";
export type {
  VersionEntry,
  VersionTimelineProps,
  VersionTimelineEntryProps,
  DiffViewerProps,
  DiffFileListProps,
  DiffSummaryProps,
  MultiFileDiffViewProps,
  DiffLine,
  DiffHunk,
  FileDiffEntry,
  MultiFileDiffResult,
  DiffViewMode,
} from "./version-history/index.js";

// Inline Edit — click-to-edit field primitives for detail page inline editing
export {
  InlineEditText,
  InlineEditTextarea,
  InlineEditImage,
  InlineEditSelect,
  InlineEditKeyValue,
  InlineEditResourceList,
  useInlineFieldSave,
} from "./inline-edit/index.js";
export type {
  InlineEditTextProps,
  InlineEditTextareaProps,
  InlineEditImageProps,
  InlineEditSelectProps,
  InlineEditKeyValueProps,
  InlineEditResourceListProps,
  UseInlineFieldSaveReturn,
  InlineEditBaseProps,
  KeyValueRow,
  ResourceRefRow,
  SelectOption,
} from "./inline-edit/index.js";

// Resource Workbench — headless hooks, view components, and composed shell for resource collection management
export {
  useViewPreference,
  useResourceCollection,
  useResourceFilters,
  useResourceSelection,
  StatusBadge,
  ColumnHeader,
  SelectionCheckbox,
  ResourceTable,
  ResourceCards,
  ResourceList,
  BulkActionBar,
  FilterBar,
  ViewSwitcher,
  ResourceInspector,
  ResourceWorkbench,
  ResourceAvatar,
} from "./resource-workbench/index.js";
export type {
  ViewMode,
  StatusPhase,
  WorkbenchColumnDef,
  FilterOperator,
  FilterValue,
  FilterDef,
  FilterOption,
  SortDirection,
  SortValue,
  SortDef,
  ResourceAction,
  BulkAction,
  WorkbenchState,
  UseViewPreferenceReturn,
  UseResourceCollectionOptions,
  UseResourceCollectionReturn,
  UseResourceFiltersOptions,
  UseResourceFiltersReturn,
  FilterSortState,
  UseResourceSelectionReturn,
  StatusBadgeProps,
  ColumnHeaderProps,
  SelectionCheckboxProps,
  ResourceTableProps,
  ResourceCardsProps,
  ResourceListProps,
  BulkActionBarProps,
  FilterBarProps,
  ViewSwitcherProps,
  ResourceInspectorProps,
  ResourceWorkbenchProps,
  ResourceAvatarProps,
} from "./resource-workbench/index.js";

// Workflow — data hooks, styled components, task kind registry
export {
  TaskKindRegistryContext,
  useTaskKindRegistry,
  useWorkflow,
  useWorkflowList,
  useWorkflowCount,
  useWorkflowInstances,
  useWorkflowExecutionList,
  useWorkflowExecution,
  useWorkflowExecutionEventLog,
  useWorkflowExecutionArtifacts,
  useWorkflowExecutionEventStream,
  useWorkflowExecutionActions,
  WorkflowExecutionPhaseBadge,
  WorkflowTaskList,
  WorkflowDetailView,
  WorkflowExecutionViewer,
  WorkflowExecutionHeader,
  useWorkflowExecutionPanel,
  workflowArtifactTabPath,
  DIAGNOSIS_DOCUMENT_ENTRY_ID,
  DIAGNOSIS_DOCUMENT_PATH,
  useWorkflowExecutionRailViews,
  WorkflowArtifactsTab,
  WorkflowChangesTab,
  WorkflowUsageTab,
  WorkflowArtifactDocument,
  WorkflowAgentCallTranscript,
  useWorkflowArtifactDownload,
  useWorkflowExecutionFileChanges,
  enumerateAgentCallChildren,
  agentCallChildrenSignature,
  deriveWorkflowArtifactItems,
  deriveWorkflowUsageItems,
  WorkflowApprovalList,
  WorkflowFileReviewList,
  serializeWorkflowYaml,
  parseWorkflowYaml,
  useWorkflowYaml,
  useWorkflowSave,
  useWorkflowValidation,
  useWorkflowTopology,
  WorkflowYamlEditor,
  WorkflowCodePreviewGraph,
  useWorkflowEditor,
  WorkflowEditorView,
  useRunWorkflowFlow,
  WorkflowRunForm,
  WorkflowRunDialog,
  useWorkflowDashboardSummary,
  usePendingApprovals,
  ExecutionSummaryWidget,
  PendingApprovalsWidget,
  FailedRunsWidget,
  WorkflowDashboard,
  START_NODE_ID,
  END_NODE_ID,
  yamlToGraph,
  graphToYaml,
  graphToWorkflowInput,
  useWorkflowCanvas,
  TASK_KIND_DRAG_MIME,
  WorkflowCanvasEditor,
  WorkflowTaskPalette,
  TaskPickerPopover,
  CanvasContextMenu,
  WorkflowInspectorPanel,
  TaskConfigForm,
  BranchConditionBuilder,
  ApprovalFormBuilder,
  useResolveAgentExecutionSession,
  CostByWorkflowChart,
  ExecutionTrendChart,
  extractWorkflowYaml,
  useWorkflowArchitectFlow,
  WorkflowArchitectDialog,
  useRefineWorkflowFlow,
  WorkflowRefinePanel,
  computeUnifiedDiff,
  useDiagnoseExecutionFlow,
  WorkflowRepairCard,
  STARTER_WORKFLOW_YAML,
  useElkLayoutEngine,
  // T13: Execution history
  deriveExecutionRow,
  deriveExecutionRows,
  sortExecutionRows,
  filterExecutionRows,
  deriveFailureAnalysis,
  useExecutionHistoryData,
  ExecutionHistoryTable,
  ExecutionFilterBar,
  HealthMetricsStrip,
  FailureAnalysisPanel,
  WorkflowExecutionHistory,
  // Workflow Instance management
  useWorkflowInstance,
  useCreateWorkflowInstance,
  useUpdateWorkflowInstance,
  useUpdateWorkflowInstanceExecutionVisibility,
  useDeleteWorkflowInstance,
  WorkflowInstanceEmptyState,
  WorkflowInstanceList,
  CreateWorkflowInstanceDialog,
  WorkflowInstanceDetailPanel,
  RunVisibilityControl,
  // T15: Workflow Template Gallery
  PATTERN_LABELS,
  WORKFLOW_CATEGORY_LABELS,
  deriveTemplateMeta,
  WorkflowTemplateCard,
  WorkflowTemplatePreview,
  WorkflowTemplateGallery,
  // Review payloads (issue #234): custom renderers for human_input gates
  WorkflowTaskReviewGate,
  useReviewRenderer,
  useReviewPayload,
  // S8: Workflow task thread (session-style center view)
  projectThreadItems,
  threadCardVariant,
  useWorkflowThreadItems,
  WorkflowTaskThread,
  // T04: session-parity task cards — per-kind presentation seam (the
  // workflow twin of registerToolPresenter)
  resolveTaskPreview,
  registerTaskPresenter,
  getTaskPresenter,
  defaultDisclosureForKind,
  // S9: approval-boundary watcher (snapshot freshness + gate attention)
  useApprovalBoundary,
} from "./workflow/index.js";
export type {
  TaskKindDescriptor,
  TaskKindCategory,
  TaskFieldDescriptor,
  TaskFieldType,
  TaskFieldGroup,
  TaskKindRegistryState,
  UseTaskKindRegistryReturn,
  UseWorkflowReturn,
  UseWorkflowListOptions,
  UseWorkflowListReturn,
  UseWorkflowCountOptions,
  UseWorkflowCountReturn,
  UseWorkflowInstancesReturn,
  UseWorkflowExecutionListOptions,
  UseWorkflowExecutionListReturn,
  UseWorkflowExecutionReturn,
  UseWorkflowExecutionEventLogOptions,
  UseWorkflowExecutionEventLogReturn,
  UseWorkflowExecutionArtifactsReturn,
  UseWorkflowExecutionEventStreamOptions,
  UseWorkflowExecutionEventStreamReturn,
  UseWorkflowExecutionActionsReturn,
  WorkflowExecutionPhaseBadgeProps,
  WorkflowTaskListProps,
  WorkflowDetailViewProps,
  WorkflowExecutionViewerProps,
  WorkflowExecutionHeaderProps,
  WorkflowExecutionPanelController,
  UseWorkflowExecutionPanelOptions,
  UseWorkflowExecutionRailViewsOptions,
  WorkflowArtifactsTabProps,
  WorkflowChangesTabProps,
  WorkflowUsageTabProps,
  AgentCallChild,
  UseWorkflowExecutionFileChangesOptions,
  UseWorkflowExecutionFileChangesReturn,
  WorkflowArtifactDocumentProps,
  WorkflowAgentCallTranscriptProps,
  WorkflowAgentExecutionHitl,
  UseWorkflowArtifactDownloadReturn,
  WorkflowArtifactEntry,
  WorkflowUsageItem,
  WorkflowApprovalListProps,
  WorkflowApprovalSubmit,
  WorkflowFileReviewListProps,
  WorkflowFileDecisionSubmit,
  UseWorkflowYamlReturn,
  UseWorkflowSaveReturn,
  UseWorkflowValidationReturn,
  UseWorkflowTopologyReturn,
  TopologyNode,
  TopologyEdge,
  TopologyNodeCategory,
  WorkflowYamlEditorProps,
  WorkflowCodePreviewGraphProps,
  UseWorkflowEditorOptions,
  UseWorkflowEditorReturn,
  WorkflowEditorViewProps,
  WorkflowEditorMode,
  UseRunWorkflowFlowOptions,
  UseRunWorkflowFlowReturn,
  RunWorkflowFieldErrors,
  WorkflowRunFormProps,
  WorkflowRunDialogProps,
  UseWorkflowDashboardSummaryOptions,
  UseWorkflowDashboardSummaryReturn,
  UsePendingApprovalsOptions,
  UsePendingApprovalsReturn,
  ExecutionSummaryWidgetProps,
  PendingApprovalsWidgetProps,
  FailedRunsWidgetProps,
  WorkflowDashboardProps,
  WorkflowGraphModel,
  WorkflowGraphNode,
  WorkflowGraphEdge,
  WorkflowGraphDocument,
  WorkflowGraphEnvVar,
  WorkflowGraphBudget,
  CanvasSelection,
  UseWorkflowCanvasOptions,
  UseWorkflowCanvasReturn,
  WorkflowCanvasEditorProps,
  WorkflowTaskPaletteProps,
  TaskPickerPopoverProps,
  CanvasContextMenuProps,
  CanvasContextMenuTarget,
  WorkflowInspectorPanelProps,
  TaskConfigFormProps,
  BranchConditionBuilderProps,
  ApprovalFormBuilderProps,
  UseResolveAgentExecutionSessionReturn,
  CostByWorkflowChartProps,
  ExecutionTrendChartProps,
  ExtractedWorkflowYaml,
  ArchitectPhase,
  UseWorkflowArchitectFlowOptions,
  UseWorkflowArchitectFlowReturn,
  WorkflowArchitectDialogProps,
  RefinePhase,
  UseRefineWorkflowFlowOptions,
  UseRefineWorkflowFlowReturn,
  WorkflowRefinePanelProps,
  DiffLine as WorkflowDiffLine,
  DiffLineType as WorkflowDiffLineType,
  DiagnosePhase,
  UseDiagnoseExecutionFlowOptions,
  UseDiagnoseExecutionFlowReturn,
  WorkflowRepairCardProps,
  UseElkLayoutEngineOptions,
  // T13: Execution history types
  ExecutionRow,
  ExecutionHistorySortField,
  ExecutionHistorySortDirection,
  ExecutionClientFilters,
  FailureGroup,
  FailureInstance,
  UseExecutionHistoryDataOptions,
  UseExecutionHistoryDataReturn,
  ExecutionHistoryTableProps,
  ExecutionFilterBarProps,
  HealthMetricsStripProps,
  FailureAnalysisPanelProps,
  WorkflowExecutionHistoryProps,
  // Workflow Instance management types
  UseWorkflowInstanceReturn,
  UseCreateWorkflowInstanceReturn,
  UseUpdateWorkflowInstanceReturn,
  UseUpdateWorkflowInstanceExecutionVisibilityReturn,
  UseDeleteWorkflowInstanceReturn,
  WorkflowInstanceEmptyStateProps,
  WorkflowInstanceListProps,
  CreateWorkflowInstanceDialogProps,
  WorkflowInstanceDetailPanelProps,
  RunVisibilityControlProps,
  // T15: Workflow Template Gallery types
  WorkflowTemplateData,
  WorkflowTemplateCategory,
  WorkflowTemplateMeta,
  WorkflowPattern,
  WorkflowTemplate,
  WorkflowTemplateCardProps,
  WorkflowTemplatePreviewProps,
  WorkflowTemplateGalleryProps,
  // Review payloads (issue #234): custom renderer contract
  ReviewRendererProps,
  ReviewRenderers,
  TaskOutcome,
  WorkflowTaskReviewGateProps,
  UseReviewPayloadReturn,
  // S8: Workflow task thread (session-style center view) types
  WorkflowThreadItem,
  WorkflowThreadProgress,
  WorkflowThreadProjection,
  WorkflowThreadCardVariant,
  WorkflowTaskThreadProps,
  // T04: session-parity task cards — presentation seam types
  WorkflowTaskPresenter,
  WorkflowTaskPreview,
  WorkflowTaskDisclosure,
  // S10: in-thread HITL wiring type
  WorkflowThreadHitl,
  // S9: approval-boundary watcher types
  ApprovalBoundaryCrossing,
} from "./workflow/index.js";

// ─── Dashboard (Unified Platform) ──────────────────────────────────────────
export {
  // Types
  type DashboardSummary,
  type DashboardFailedRun,
  // Data Hooks
  useAgentExecutionSummary,
  AgentExecutionSummaryTimeWindow,
  type UseAgentExecutionSummaryOptions,
  type UseAgentExecutionSummaryReturn,
  useDashboardSummary,
  type UseDashboardSummaryOptions,
  type UseDashboardSummaryReturn,
  useDashboardFailedRuns,
  type UseDashboardFailedRunsReturn,
  // Styled Components
  DashboardKPICards,
  type DashboardKPICardsProps,
  DashboardFailedRuns,
  type DashboardFailedRunsProps,
  OperationalDashboard,
  type OperationalDashboardProps,
} from "./dashboard/index.js";
