load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "controller",
    srcs = ["search_controller.go"],
    importpath = "github.com/stigmer/stigmer/backend/services/stigmer-server/pkg/query/search/controller",
    visibility = ["//visibility:public"],
    deps = [
        "//apis/stubs/go/ai/stigmer/commons/apiresource/apiresourcekind",
        "//apis/stubs/go/ai/stigmer/search/v1:search",
        "//backend/libs/go/grpc",
        "//backend/services/stigmer-server/pkg/query/search/handler",
        "@com_github_rs_zerolog//log",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
