// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/commons/apiresource/apiresourcekind/authorization_config.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.commons.apiresource.apiresourcekind;

@com.google.protobuf.Generated
public final class AuthorizationConfigProto extends com.google.protobuf.GeneratedFile {
  private AuthorizationConfigProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "AuthorizationConfigProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_commons_apiresource_apiresourcekind_VisibilityConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_commons_apiresource_apiresourcekind_VisibilityConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_commons_apiresource_apiresourcekind_ParentRelationConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_commons_apiresource_apiresourcekind_ParentRelationConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_stigmer_commons_apiresource_apiresourcekind_AuthorizationConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_stigmer_commons_apiresource_apiresourcekind_AuthorizationConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nIai/stigmer/commons/apiresource/apireso" +
      "urcekind/authorization_config.proto\022.ai." +
      "stigmer.commons.apiresource.apiresourcek" +
      "ind\032\034ai/stigmer/iam/v1/enum.proto\"\213\001\n\020Vi" +
      "sibilityConfig\022\'\n\017supports_public\030\001 \001(\010R" +
      "\016supportsPublic\022+\n\021supports_platform\030\002 \001" +
      "(\010R\020supportsPlatform\022!\n\014supports_org\030\003 \001" +
      "(\010R\013supportsOrg\"e\n\024ParentRelationConfig\022" +
      "\022\n\004kind\030\001 \001(\tR\004kind\022\032\n\010relation\030\002 \001(\tR\010r" +
      "elation\022\035\n\nspec_field\030\003 \001(\tR\tspecField\"\221" +
      "\005\n\023AuthorizationConfig\022e\n\nscope_type\030\001 \001" +
      "(\0162F.ai.stigmer.commons.apiresource.apir" +
      "esourcekind.AuthorizationScopeTypeR\tscop" +
      "eType\022c\n\nowner_type\030\002 \001(\0162D.ai.stigmer.c" +
      "ommons.apiresource.apiresourcekind.Owner" +
      "AttributionTypeR\townerType\022\\\n\006parent\030\003 \001" +
      "(\0132D.ai.stigmer.commons.apiresource.apir" +
      "esourcekind.ParentRelationConfigR\006parent" +
      "\022s\n\022additional_parents\030\004 \003(\0132D.ai.stigme" +
      "r.commons.apiresource.apiresourcekind.Pa" +
      "rentRelationConfigR\021additionalParents\022`\n" +
      "\nvisibility\030\005 \001(\0132@.ai.stigmer.commons.a" +
      "piresource.apiresourcekind.VisibilityCon" +
      "figR\nvisibility\0224\n\026requires_creator_tupl" +
      "e\030\006 \001(\010R\024requiresCreatorTuple\022C\n\017grantab" +
      "le_roles\030\007 \003(\0162\032.ai.stigmer.iam.v1.IamRo" +
      "leR\016grantableRoles*\205\002\n\026AuthorizationScop" +
      "eType\022(\n$AUTHORIZATION_SCOPE_TYPE_UNSPEC" +
      "IFIED\020\000\022%\n!AUTHORIZATION_SCOPE_TYPE_PLAT" +
      "FORM\020\001\022)\n%AUTHORIZATION_SCOPE_TYPE_ORGAN" +
      "IZATION\020\002\022#\n\037AUTHORIZATION_SCOPE_TYPE_PA" +
      "RENT\020\003\022\'\n#AUTHORIZATION_SCOPE_TYPE_OWNER" +
      "_ONLY\020\004\022!\n\035AUTHORIZATION_SCOPE_TYPE_NONE" +
      "\020\005*\311\001\n\024OwnerAttributionType\022&\n\"OWNER_ATT" +
      "RIBUTION_TYPE_UNSPECIFIED\020\000\022!\n\035OWNER_ATT" +
      "RIBUTION_TYPE_DIRECT\020\001\022$\n OWNER_ATTRIBUT" +
      "ION_TYPE_INHERITED\020\002\022\037\n\033OWNER_ATTRIBUTIO" +
      "N_TYPE_SELF\020\003\022\037\n\033OWNER_ATTRIBUTION_TYPE_" +
      "NONE\020\004B\370\001B\030AuthorizationConfigProtoP\001\242\002\005" +
      "ASCAA\252\002.Ai.Stigmer.Commons.Apiresource.A" +
      "piresourcekind\312\002.Ai\\Stigmer\\Commons\\Apir" +
      "esource\\Apiresourcekind\342\002:Ai\\Stigmer\\Com" +
      "mons\\Apiresource\\Apiresourcekind\\GPBMeta" +
      "data\352\0022Ai::Stigmer::Commons::Apiresource" +
      "::Apiresourcekindb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ai.stigmer.iam.v1.EnumProto.getDescriptor(),
        });
    internal_static_ai_stigmer_commons_apiresource_apiresourcekind_VisibilityConfig_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_ai_stigmer_commons_apiresource_apiresourcekind_VisibilityConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_commons_apiresource_apiresourcekind_VisibilityConfig_descriptor,
        new java.lang.String[] { "SupportsPublic", "SupportsPlatform", "SupportsOrg", });
    internal_static_ai_stigmer_commons_apiresource_apiresourcekind_ParentRelationConfig_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_ai_stigmer_commons_apiresource_apiresourcekind_ParentRelationConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_commons_apiresource_apiresourcekind_ParentRelationConfig_descriptor,
        new java.lang.String[] { "Kind", "Relation", "SpecField", });
    internal_static_ai_stigmer_commons_apiresource_apiresourcekind_AuthorizationConfig_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_ai_stigmer_commons_apiresource_apiresourcekind_AuthorizationConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ai_stigmer_commons_apiresource_apiresourcekind_AuthorizationConfig_descriptor,
        new java.lang.String[] { "ScopeType", "OwnerType", "Parent", "AdditionalParents", "Visibility", "RequiresCreatorTuple", "GrantableRoles", });
    descriptor.resolveAllFeaturesImmutable();
    ai.stigmer.iam.v1.EnumProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
