load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "backend",
    srcs = ["client.go"],
    importpath = "github.com/stigmer/stigmer/client-apps/cli/internal/cli/backend",
    visibility = ["//client-apps/cli:__subpackages__"],
    deps = [
        "//client-apps/cli/internal/cli/config",
        "@com_github_pkg_errors//:errors",
        "@com_github_rs_zerolog//log",
        "@com_github_stigmer_stigmer_sdk_go//:go",
        "@org_golang_google_grpc//keepalive",
    ],
)
