# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ai.stigmer.agentic.artifact.v1 import api_pb2 as ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_api__pb2
from ai.stigmer.agentic.artifact.v1 import io_pb2 as ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2


class ArtifactQueryControllerStub(object):
    """ArtifactQueryController handles read operations for Artifact resources.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get = channel.unary_unary(
                '/ai.stigmer.agentic.artifact.v1.ArtifactQueryController/get',
                request_serializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactId.SerializeToString,
                response_deserializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_api__pb2.Artifact.FromString,
                _registered_method=True)
        self.listByRun = channel.unary_unary(
                '/ai.stigmer.agentic.artifact.v1.ArtifactQueryController/listByRun',
                request_serializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ListArtifactsByRunRequest.SerializeToString,
                response_deserializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactList.FromString,
                _registered_method=True)
        self.getDownloadUrl = channel.unary_unary(
                '/ai.stigmer.agentic.artifact.v1.ArtifactQueryController/getDownloadUrl',
                request_serializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactId.SerializeToString,
                response_deserializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactDownloadUrl.FromString,
                _registered_method=True)
        self.getContent = channel.unary_unary(
                '/ai.stigmer.agentic.artifact.v1.ArtifactQueryController/getContent',
                request_serializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.GetArtifactContentRequest.SerializeToString,
                response_deserializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.GetArtifactContentResponse.FromString,
                _registered_method=True)


class ArtifactQueryControllerServicer(object):
    """ArtifactQueryController handles read operations for Artifact resources.
    """

    def get(self, request, context):
        """Get a single artifact by ID.

        Returns the complete Artifact resource including metadata, spec,
        and status (content hash, size, storage state, expiration).

        Does NOT return the artifact content — use getDownloadUrl to
        retrieve a URL for downloading the content via HTTP GET.

        Use Cases:

        1. Artifact Detail View:
        - User clicks an artifact in the run viewer
        - UI calls get() to fetch full metadata
        - UI displays content type, size, source task, expiration

        2. Artifact Reference Resolution:
        - Task output contains _artifact_ref field
        - UI calls get() to resolve the reference to metadata
        - UI renders a download/preview widget instead of raw JSON

        Error Cases:

        - NOT_FOUND: No Artifact exists with the given ID
        - PERMISSION_DENIED: User doesn't have view access to the parent run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listByRun(self, request, context):
        """List all artifacts produced by a specific run.

        Returns a paginated list of artifacts filtered by either
        workflow_run_id or agent_run_id.

        Use Cases:

        1. Run Viewer Artifact Panel:
        - User views a workflow run in the run viewer
        - UI calls listByRun() to populate the artifact sidebar
        - Each artifact shows display name, content type, size, source task

        2. CLI Artifact Listing:
        - `stigmer workflow artifacts wex_abc123`
        - CLI calls listByRun() and formats as a table

        Error Cases:

        - INVALID_ARGUMENT: Neither workflow_run_id nor agent_run_id provided
        - PERMISSION_DENIED: User doesn't have view access to the parent run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDownloadUrl(self, request, context):
        """Get a download URL for artifact content.

        Returns a URL that the client can use to download the artifact's
        content via HTTP GET. This avoids streaming large blobs through
        the gRPC control plane.

        Cloud: returns a pre-signed S3 URL with a short TTL (15 minutes).
        OSS: returns a direct URL to the local artifact server endpoint.

        Use Cases:

        1. Download Artifact:
        - User clicks "Download" in the run viewer
        - UI calls getDownloadUrl() to get a URL
        - Browser opens the URL in a new tab or triggers a download

        2. Preview Artifact:
        - UI calls getDownloadUrl() for JSON/text artifacts
        - UI fetches content from the URL and renders inline
        - Large artifacts show a truncated preview with download option

        3. CLI Download:
        - `stigmer workflow artifact download art_abc123 -o output.json`
        - CLI calls getDownloadUrl() then fetches via HTTP GET

        Error Cases:

        - NOT_FOUND: No Artifact exists with the given ID
        - PERMISSION_DENIED: User doesn't have view access to the parent run
        - FAILED_PRECONDITION: Artifact blob has been deleted (storage_state_deleted)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getContent(self, request, context):
        """Read artifact content bytes through the Stigmer API.

        Returns the artifact's raw bytes directly in the response, eliminating
        CORS concerns for SDK consumers who need to read content
        programmatically — e.g., rendering an artifact-backed review payload
        inside an embedded approval gate.

        For direct file downloads, use getDownloadUrl instead — it returns a
        presigned URL that avoids proxying bytes through the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtifactQueryControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactId.FromString,
                    response_serializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_api__pb2.Artifact.SerializeToString,
            ),
            'listByRun': grpc.unary_unary_rpc_method_handler(
                    servicer.listByRun,
                    request_deserializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ListArtifactsByRunRequest.FromString,
                    response_serializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactList.SerializeToString,
            ),
            'getDownloadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.getDownloadUrl,
                    request_deserializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactId.FromString,
                    response_serializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactDownloadUrl.SerializeToString,
            ),
            'getContent': grpc.unary_unary_rpc_method_handler(
                    servicer.getContent,
                    request_deserializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.GetArtifactContentRequest.FromString,
                    response_serializer=ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.GetArtifactContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.stigmer.agentic.artifact.v1.ArtifactQueryController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.stigmer.agentic.artifact.v1.ArtifactQueryController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArtifactQueryController(object):
    """ArtifactQueryController handles read operations for Artifact resources.
    """

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.stigmer.agentic.artifact.v1.ArtifactQueryController/get',
            ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactId.SerializeToString,
            ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_api__pb2.Artifact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listByRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.stigmer.agentic.artifact.v1.ArtifactQueryController/listByRun',
            ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ListArtifactsByRunRequest.SerializeToString,
            ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getDownloadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.stigmer.agentic.artifact.v1.ArtifactQueryController/getDownloadUrl',
            ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactId.SerializeToString,
            ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.ArtifactDownloadUrl.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.stigmer.agentic.artifact.v1.ArtifactQueryController/getContent',
            ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.GetArtifactContentRequest.SerializeToString,
            ai_dot_stigmer_dot_agentic_dot_artifact_dot_v1_dot_io__pb2.GetArtifactContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
