// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/workflow/v1/tasks/try.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.workflow.v1.tasks;

@com.google.protobuf.Generated
public interface TryTaskConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.agentic.workflow.v1.tasks.TryTaskConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Tasks to attempt (at least one required).
   * If any task fails, execution jumps to catch block.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.workflow.v1.WorkflowTask try = 1 [json_name = "try", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<ai.stigmer.agentic.workflow.v1.WorkflowTask> 
      getTryList();
  /**
   * <pre>
   * Tasks to attempt (at least one required).
   * If any task fails, execution jumps to catch block.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.workflow.v1.WorkflowTask try = 1 [json_name = "try", (.buf.validate.field) = { ... }</code>
   */
  ai.stigmer.agentic.workflow.v1.WorkflowTask getTry(int index);
  /**
   * <pre>
   * Tasks to attempt (at least one required).
   * If any task fails, execution jumps to catch block.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.workflow.v1.WorkflowTask try = 1 [json_name = "try", (.buf.validate.field) = { ... }</code>
   */
  int getTryCount();
  /**
   * <pre>
   * Tasks to attempt (at least one required).
   * If any task fails, execution jumps to catch block.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.workflow.v1.WorkflowTask try = 1 [json_name = "try", (.buf.validate.field) = { ... }</code>
   */
  java.util.List<? extends ai.stigmer.agentic.workflow.v1.WorkflowTaskOrBuilder> 
      getTryOrBuilderList();
  /**
   * <pre>
   * Tasks to attempt (at least one required).
   * If any task fails, execution jumps to catch block.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.workflow.v1.WorkflowTask try = 1 [json_name = "try", (.buf.validate.field) = { ... }</code>
   */
  ai.stigmer.agentic.workflow.v1.WorkflowTaskOrBuilder getTryOrBuilder(
      int index);

  /**
   * <pre>
   * Catch block for error handling (optional).
   * If not provided, errors propagate to parent.
   * </pre>
   *
   * <code>.ai.stigmer.agentic.workflow.v1.tasks.CatchBlock catch = 2 [json_name = "catch"];</code>
   * @return Whether the catch field is set.
   */
  boolean hasCatch();
  /**
   * <pre>
   * Catch block for error handling (optional).
   * If not provided, errors propagate to parent.
   * </pre>
   *
   * <code>.ai.stigmer.agentic.workflow.v1.tasks.CatchBlock catch = 2 [json_name = "catch"];</code>
   * @return The catch.
   */
  ai.stigmer.agentic.workflow.v1.tasks.CatchBlock getCatch();
  /**
   * <pre>
   * Catch block for error handling (optional).
   * If not provided, errors propagate to parent.
   * </pre>
   *
   * <code>.ai.stigmer.agentic.workflow.v1.tasks.CatchBlock catch = 2 [json_name = "catch"];</code>
   */
  ai.stigmer.agentic.workflow.v1.tasks.CatchBlockOrBuilder getCatchOrBuilder();
}
