# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/stigmer/billing/plan/v1/io.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai/stigmer/billing/plan/v1/io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.stigmer.billing.plan.v1 import api_pb2 as ai_dot_stigmer_dot_billing_dot_plan_dot_v1_dot_api__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ai/stigmer/billing/plan/v1/io.proto\x12\x1a\x61i.stigmer.billing.plan.v1\x1a$ai/stigmer/billing/plan/v1/api.proto\x1a\x1b\x62uf/validate/validate.proto\")\n\x06PlanId\x12\x1f\n\x05value\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\x05value\"C\n\x05Plans\x12:\n\x07\x65ntries\x18\x01 \x03(\x0b\x32 .ai.stigmer.billing.plan.v1.PlanR\x07\x65ntries\"9\n\x0eListPlansInput\x12\'\n\x0finclude_retired\x18\x01 \x01(\x08R\x0eincludeRetiredB\xb6\x01\n\x1e\x63om.ai.stigmer.billing.plan.v1B\x07IoProtoP\x01\xa2\x02\x04\x41SBP\xaa\x02\x1a\x41i.Stigmer.Billing.Plan.V1\xca\x02\x1a\x41i\\Stigmer\\Billing\\Plan\\V1\xe2\x02&Ai\\Stigmer\\Billing\\Plan\\V1\\GPBMetadata\xea\x02\x1e\x41i::Stigmer::Billing::Plan::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.stigmer.billing.plan.v1.io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.ai.stigmer.billing.plan.v1B\007IoProtoP\001\242\002\004ASBP\252\002\032Ai.Stigmer.Billing.Plan.V1\312\002\032Ai\\Stigmer\\Billing\\Plan\\V1\342\002&Ai\\Stigmer\\Billing\\Plan\\V1\\GPBMetadata\352\002\036Ai::Stigmer::Billing::Plan::V1'
  _globals['_PLANID'].fields_by_name['value']._loaded_options = None
  _globals['_PLANID'].fields_by_name['value']._serialized_options = b'\272H\006r\004\020\001\030@'
  _globals['_PLANID']._serialized_start=134
  _globals['_PLANID']._serialized_end=175
  _globals['_PLANS']._serialized_start=177
  _globals['_PLANS']._serialized_end=244
  _globals['_LISTPLANSINPUT']._serialized_start=246
  _globals['_LISTPLANSINPUT']._serialized_end=303
# @@protoc_insertion_point(module_scope)
