// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/agentrun/v1/approval.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.agentrun.v1;

@com.google.protobuf.Generated
public interface ChildApprovalNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.agentic.agentrun.v1.ChildApprovalNotification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Child agent run ID that requires approval.
   * Format: AgentRun.metadata.id (e.g., "agx-abc123xyz456")
   * Used by parent to track which child needs approval.
   * </pre>
   *
   * <code>string run_id = 1 [json_name = "runId"];</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <pre>
   * Child agent run ID that requires approval.
   * Format: AgentRun.metadata.id (e.g., "agx-abc123xyz456")
   * Used by parent to track which child needs approval.
   * </pre>
   *
   * <code>string run_id = 1 [json_name = "runId"];</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <pre>
   * All pending approvals from this child agent run.
   *
   * Contains one entry per tool call requiring approval. Each entry carries
   * the full PendingApproval details (tool_call_id, tool_name, message,
   * args_preview, requested_at).
   *
   * The parent workflow wraps each entry in a WorkflowPendingApproval with
   * run_id above as the child_agent_run_id for routing.
   *
   * One signal, complete picture, no partial states.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.agentrun.v1.PendingApproval pending_approvals = 2 [json_name = "pendingApprovals"];</code>
   */
  java.util.List<ai.stigmer.agentic.agentrun.v1.PendingApproval> 
      getPendingApprovalsList();
  /**
   * <pre>
   * All pending approvals from this child agent run.
   *
   * Contains one entry per tool call requiring approval. Each entry carries
   * the full PendingApproval details (tool_call_id, tool_name, message,
   * args_preview, requested_at).
   *
   * The parent workflow wraps each entry in a WorkflowPendingApproval with
   * run_id above as the child_agent_run_id for routing.
   *
   * One signal, complete picture, no partial states.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.agentrun.v1.PendingApproval pending_approvals = 2 [json_name = "pendingApprovals"];</code>
   */
  ai.stigmer.agentic.agentrun.v1.PendingApproval getPendingApprovals(int index);
  /**
   * <pre>
   * All pending approvals from this child agent run.
   *
   * Contains one entry per tool call requiring approval. Each entry carries
   * the full PendingApproval details (tool_call_id, tool_name, message,
   * args_preview, requested_at).
   *
   * The parent workflow wraps each entry in a WorkflowPendingApproval with
   * run_id above as the child_agent_run_id for routing.
   *
   * One signal, complete picture, no partial states.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.agentrun.v1.PendingApproval pending_approvals = 2 [json_name = "pendingApprovals"];</code>
   */
  int getPendingApprovalsCount();
  /**
   * <pre>
   * All pending approvals from this child agent run.
   *
   * Contains one entry per tool call requiring approval. Each entry carries
   * the full PendingApproval details (tool_call_id, tool_name, message,
   * args_preview, requested_at).
   *
   * The parent workflow wraps each entry in a WorkflowPendingApproval with
   * run_id above as the child_agent_run_id for routing.
   *
   * One signal, complete picture, no partial states.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.agentrun.v1.PendingApproval pending_approvals = 2 [json_name = "pendingApprovals"];</code>
   */
  java.util.List<? extends ai.stigmer.agentic.agentrun.v1.PendingApprovalOrBuilder> 
      getPendingApprovalsOrBuilderList();
  /**
   * <pre>
   * All pending approvals from this child agent run.
   *
   * Contains one entry per tool call requiring approval. Each entry carries
   * the full PendingApproval details (tool_call_id, tool_name, message,
   * args_preview, requested_at).
   *
   * The parent workflow wraps each entry in a WorkflowPendingApproval with
   * run_id above as the child_agent_run_id for routing.
   *
   * One signal, complete picture, no partial states.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.agentrun.v1.PendingApproval pending_approvals = 2 [json_name = "pendingApprovals"];</code>
   */
  ai.stigmer.agentic.agentrun.v1.PendingApprovalOrBuilder getPendingApprovalsOrBuilder(
      int index);
}
