"use client";

import { useCallback, useState } from "react";
import type { AgentExecution } from "@stigmer/protos/ai/stigmer/agentic/agentexecution/v1/api_pb";
import {
  useSessionArtifacts,
  type SessionArtifactEntry,
} from "../useSessionArtifacts.js";
import { ArtifactCard } from "../../execution/ArtifactCard.js";
import { ArtifactPreviewModal } from "../../execution/ArtifactPreviewModal.js";
import { isPlanArtifact } from "../../library/detect-plan-artifact.js";
import type { ApplyResourceResult } from "../../library/useApplyResource.js";

export interface ArtifactsTabProps {
  readonly executions: readonly AgentExecution[];
  readonly org: string;
  readonly onApplied?: (result: ApplyResourceResult) => void;
  /**
   * Implement a plan. When provided, the preview of a `plan.md` artifact
   * shows an Implement action (turn the plan into an Agent run) — the same
   * action as the message-thread plan card.
   */
  readonly onImplementPlan?: () => void;
  /**
   * Open a plan in the session panel's plan document tab. When provided, a
   * `plan.md` artifact routes there instead of the preview modal — the plan
   * is a first-class document, not a popup. Non-plan artifacts keep the
   * modal. When omitted (hosts without the plan tab) the modal remains for
   * every artifact.
   */
  readonly onOpenPlan?: (executionId: string) => void;
}

/**
 * Artifacts facet for the session panel (a `useSessionRailViews` rail view).
 *
 * Wraps `useSessionArtifacts` → `ArtifactCard` list with
 * `ArtifactPreviewModal` — the same content as `ArtifactsWidget`
 * without the section heading.
 */
export function ArtifactsTab({
  executions,
  org,
  onApplied,
  onImplementPlan,
  onOpenPlan,
}: ArtifactsTabProps) {
  const { artifacts, hasArtifacts } = useSessionArtifacts(executions);
  const [previewEntry, setPreviewEntry] = useState<SessionArtifactEntry | null>(null);

  const handlePreview = useCallback(
    (entry: SessionArtifactEntry) => {
      // The plan opens as a document (the panel's plan tab), never a popup.
      if (onOpenPlan && isPlanArtifact(entry.artifact)) {
        onOpenPlan(entry.executionId);
        return;
      }
      setPreviewEntry(entry);
    },
    [onOpenPlan],
  );

  const handleClosePreview = useCallback(() => {
    setPreviewEntry(null);
  }, []);

  if (!hasArtifacts) {
    return (
      <div className="flex flex-col items-center justify-center px-4 py-8 text-center">
        <p className="text-xs text-muted-foreground">
          No artifacts yet. Files generated by the agent will appear here.
        </p>
      </div>
    );
  }

  return (
    <>
      <div role="list" className="space-y-2">
        {artifacts.map((entry) => (
          <div key={entry.artifact.sandboxPath || entry.artifact.name} role="listitem">
            <ArtifactCard
              artifact={entry.artifact}
              executionId={entry.executionId}
              org={org}
              hasNameCollision={entry.hasNameCollision}
              onPreview={() => handlePreview(entry)}
            />
          </div>
        ))}
      </div>

      {previewEntry && (
        <ArtifactPreviewModal
          artifact={previewEntry.artifact}
          executionId={previewEntry.executionId}
          isTerminal={previewEntry.isTerminal}
          org={org}
          open
          onClose={handleClosePreview}
          onApplied={onApplied}
          onImplement={
            isPlanArtifact(previewEntry.artifact) ? onImplementPlan : undefined
          }
        />
      )}
    </>
  );
}
