syntax = "proto3";

package ai.stigmer.iam.servicecredential.v1;

import "ai/stigmer/iam/servicecredential/v1/api.proto";
import "buf/validate/validate.proto";

// Wrapper for service credential id.
message ServiceCredentialId {
  // The unique identifier of the service credential resource.
  string value = 1 [(buf.validate.field).string = {
    min_len: 1
    max_len: 64
  }];
}

// List of service credentials (unbounded).
message ServiceCredentials {
  repeated ServiceCredential entries = 1;
}

// Response for paginated list query.
message ServiceCredentialList {
  // total number of pages
  int32 total_pages = 1;
  // service credentials in current page
  repeated ServiceCredential entries = 2;
}
