load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "workflows",
    srcs = [
        "invoke_workflow.go",
        "invoke_workflow_impl.go",
        "workflow_creator.go",
    ],
    importpath = "github.com/stigmer/stigmer/backend/services/stigmer-server/pkg/domain/workflowexecution/temporal/workflows",
    visibility = ["//visibility:public"],
    deps = [
        "//apis/stubs/go/ai/stigmer/agentic/workflowexecution/v1:workflowexecution",
        "//backend/services/stigmer-server/pkg/domain/executioncontext/temporal/activities",
        "//backend/services/stigmer-server/pkg/domain/workflowexecution/temporal/activities",
        "@com_github_rs_zerolog//log",
        "@io_temporal_go_api//enums/v1:enums",
        "@io_temporal_go_sdk//client",
        "@io_temporal_go_sdk//converter",
        "@io_temporal_go_sdk//temporal",
        "@io_temporal_go_sdk//workflow",
    ],
)

go_test(
    name = "workflows_test",
    srcs = ["invoke_workflow_impl_test.go"],
    embed = [":workflows"],
    deps = [
        "//apis/stubs/go/ai/stigmer/agentic/workflowexecution/v1:workflowexecution",
        "//backend/services/stigmer-server/pkg/domain/executioncontext/temporal/activities",
        "//backend/services/stigmer-server/pkg/domain/workflowexecution/temporal/activities",
        "@com_github_stretchr_testify//mock",
        "@com_github_stretchr_testify//require",
        "@io_temporal_go_sdk//activity",
        "@io_temporal_go_sdk//testsuite",
        "@io_temporal_go_sdk//workflow",
    ],
)
