load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "store",
    srcs = [
        "search_query_store.go",
        "sqlite_search_query_store.go",
    ],
    importpath = "github.com/stigmer/stigmer/backend/services/stigmer-server/pkg/query/search/store",
    visibility = ["//visibility:public"],
    deps = [
        "//apis/stubs/go/ai/stigmer/commons/apiresource/apiresourcekind",
        "//apis/stubs/go/ai/stigmer/search/v1:search",
        "//backend/libs/go/store",
        "//backend/services/stigmer-server/pkg/query/search/extractor",
        "//backend/services/stigmer-server/pkg/query/search/valueobject",
        "@com_github_rs_zerolog//log",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "store_test",
    srcs = [
        "sqlite_search_query_store_query_test.go",
        "sqlite_search_query_store_test.go",
    ],
    embed = [":store"],
    deps = [
        "//apis/stubs/go/ai/stigmer/agentic/agent/v1:agent",
        "//apis/stubs/go/ai/stigmer/agentic/session/v1:session",
        "//apis/stubs/go/ai/stigmer/commons/apiresource",
        "//apis/stubs/go/ai/stigmer/commons/apiresource/apiresourcekind",
        "//backend/libs/go/store/sqlite",
        "//backend/services/stigmer-server/pkg/query/search/extractor",
        "//backend/services/stigmer-server/pkg/query/search/valueobject",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
