// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/activity/v1/io.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.activity.v1;

@com.google.protobuf.Generated
public interface ListRecentActivityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.activity.v1.ListRecentActivityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Maximum entries to return. Defaults to 30.
   * </pre>
   *
   * <code>int32 page_size = 1 [json_name = "pageSize"];</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * Organization slug to scope the query.
   *
   * When provided, the handler attempts an org-scoped fast path: if the
   * caller is a member of this organization, it queries MongoDB directly
   * with `metadata.org = org` instead of enumerating per-resource FGA
   * tuples. This turns an O(n) FGA reverse-index scan into a single
   * membership check + indexed MongoDB query.
   *
   * When empty, falls back to per-resource FGA enumeration (slower but
   * works regardless of org context).
   * </pre>
   *
   * <code>string org = 2 [json_name = "org"];</code>
   * @return The org.
   */
  java.lang.String getOrg();
  /**
   * <pre>
   * Organization slug to scope the query.
   *
   * When provided, the handler attempts an org-scoped fast path: if the
   * caller is a member of this organization, it queries MongoDB directly
   * with `metadata.org = org` instead of enumerating per-resource FGA
   * tuples. This turns an O(n) FGA reverse-index scan into a single
   * membership check + indexed MongoDB query.
   *
   * When empty, falls back to per-resource FGA enumeration (slower but
   * works regardless of org context).
   * </pre>
   *
   * <code>string org = 2 [json_name = "org"];</code>
   * @return The bytes for org.
   */
  com.google.protobuf.ByteString
      getOrgBytes();
}
