load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "internalcomment",
    srcs = ["internalcomment.go"],
    importpath = "github.com/stigmer/stigmer/tools/codegen/internalcomment",
    visibility = ["//visibility:public"],
)

go_test(
    name = "internalcomment_test",
    srcs = ["internalcomment_test.go"],
    embed = [":internalcomment"],
)
