// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/iam/iampolicy/v1/io.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.iam.iampolicy.v1;

@com.google.protobuf.Generated
public interface PrincipalAccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.iam.iampolicy.v1.PrincipalAccess)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The principal with full display information
   * </pre>
   *
   * <code>.ai.stigmer.iam.iampolicy.v1.ApiResourceRefView principal = 1 [json_name = "principal"];</code>
   * @return Whether the principal field is set.
   */
  boolean hasPrincipal();
  /**
   * <pre>
   * The principal with full display information
   * </pre>
   *
   * <code>.ai.stigmer.iam.iampolicy.v1.ApiResourceRefView principal = 1 [json_name = "principal"];</code>
   * @return The principal.
   */
  ai.stigmer.iam.iampolicy.v1.ApiResourceRefView getPrincipal();
  /**
   * <pre>
   * The principal with full display information
   * </pre>
   *
   * <code>.ai.stigmer.iam.iampolicy.v1.ApiResourceRefView principal = 1 [json_name = "principal"];</code>
   */
  ai.stigmer.iam.iampolicy.v1.ApiResourceRefViewOrBuilder getPrincipalOrBuilder();

  /**
   * <pre>
   * All roles this principal has on the resource
   * </pre>
   *
   * <code>repeated .ai.stigmer.iam.iampolicy.v1.RoleGrant roles = 2 [json_name = "roles"];</code>
   */
  java.util.List<ai.stigmer.iam.iampolicy.v1.RoleGrant> 
      getRolesList();
  /**
   * <pre>
   * All roles this principal has on the resource
   * </pre>
   *
   * <code>repeated .ai.stigmer.iam.iampolicy.v1.RoleGrant roles = 2 [json_name = "roles"];</code>
   */
  ai.stigmer.iam.iampolicy.v1.RoleGrant getRoles(int index);
  /**
   * <pre>
   * All roles this principal has on the resource
   * </pre>
   *
   * <code>repeated .ai.stigmer.iam.iampolicy.v1.RoleGrant roles = 2 [json_name = "roles"];</code>
   */
  int getRolesCount();
  /**
   * <pre>
   * All roles this principal has on the resource
   * </pre>
   *
   * <code>repeated .ai.stigmer.iam.iampolicy.v1.RoleGrant roles = 2 [json_name = "roles"];</code>
   */
  java.util.List<? extends ai.stigmer.iam.iampolicy.v1.RoleGrantOrBuilder> 
      getRolesOrBuilderList();
  /**
   * <pre>
   * All roles this principal has on the resource
   * </pre>
   *
   * <code>repeated .ai.stigmer.iam.iampolicy.v1.RoleGrant roles = 2 [json_name = "roles"];</code>
   */
  ai.stigmer.iam.iampolicy.v1.RoleGrantOrBuilder getRolesOrBuilder(
      int index);
}
