// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/artifact/v1/io.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.artifact.v1;

@com.google.protobuf.Generated
public interface ArtifactIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.agentic.artifact.v1.ArtifactId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Artifact identifier.
   * Format: "art_{unique-suffix}" (auto-generated by backend)
   * </pre>
   *
   * <code>string value = 1 [json_name = "value", (.buf.validate.field) = { ... }</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * Artifact identifier.
   * Format: "art_{unique-suffix}" (auto-generated by backend)
   * </pre>
   *
   * <code>string value = 1 [json_name = "value", (.buf.validate.field) = { ... }</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
