load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "valueobject",
    srcs = [
        "search_criteria.go",
        "search_paged_result.go",
    ],
    importpath = "github.com/stigmer/stigmer/backend/services/stigmer-server/pkg/query/search/valueobject",
    visibility = ["//visibility:public"],
    deps = [
        "//apis/stubs/go/ai/stigmer/commons/apiresource/apiresourcekind",
        "//apis/stubs/go/ai/stigmer/search/v1:search",
    ],
)

go_test(
    name = "valueobject_test",
    srcs = [
        "search_criteria_invariant_test.go",
        "search_criteria_test.go",
        "search_paged_result_test.go",
    ],
    embed = [":valueobject"],
    deps = [
        "//apis/stubs/go/ai/stigmer/commons/apiresource/apiresourcekind",
        "//apis/stubs/go/ai/stigmer/search/v1:search",
        "//backend/libs/go/apiresource",
    ],
)
