// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ai/stigmer/platform/github/v1/query.proto

package githubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitHubQueryController_ListRepositories_FullMethodName   = "/ai.stigmer.platform.github.v1.GitHubQueryController/listRepositories"
	GitHubQueryController_SearchRepositories_FullMethodName = "/ai.stigmer.platform.github.v1.GitHubQueryController/searchRepositories"
	GitHubQueryController_ListBranches_FullMethodName       = "/ai.stigmer.platform.github.v1.GitHubQueryController/listBranches"
	GitHubQueryController_GetTree_FullMethodName            = "/ai.stigmer.platform.github.v1.GitHubQueryController/getTree"
	GitHubQueryController_GetFileContent_FullMethodName     = "/ai.stigmer.platform.github.v1.GitHubQueryController/getFileContent"
)

// GitHubQueryControllerClient is the client API for GitHubQueryController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GitHubQueryController reads GitHub repositories with the caller's saved
// github.com login, so no page holds the token.
//
// Each RPC uses the github.com connection in the caller's My vault in the
// named organization, and answers FAILED_PRECONDITION when there is none.
type GitHubQueryControllerClient interface {
	// List the repositories the connected account can reach, one page at a
	// time, most recently updated first.
	ListRepositories(ctx context.Context, in *ListGitHubRepositoriesInput, opts ...grpc.CallOption) (*GitHubRepositoryList, error)
	// Search the repositories the connected account can reach.
	SearchRepositories(ctx context.Context, in *SearchGitHubRepositoriesInput, opts ...grpc.CallOption) (*GitHubRepositoryList, error)
	// List a repository's branches.
	ListBranches(ctx context.Context, in *ListGitHubBranchesInput, opts ...grpc.CallOption) (*GitHubBranchList, error)
	// List every file and directory of a repository at a branch or commit.
	GetTree(ctx context.Context, in *GetGitHubTreeInput, opts ...grpc.CallOption) (*GitHubTree, error)
	// Read one file of a repository at a branch or commit.
	//
	// Files above 10 MiB are reported by size without their content.
	GetFileContent(ctx context.Context, in *GetGitHubFileContentInput, opts ...grpc.CallOption) (*GitHubFileContent, error)
}

type gitHubQueryControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewGitHubQueryControllerClient(cc grpc.ClientConnInterface) GitHubQueryControllerClient {
	return &gitHubQueryControllerClient{cc}
}

func (c *gitHubQueryControllerClient) ListRepositories(ctx context.Context, in *ListGitHubRepositoriesInput, opts ...grpc.CallOption) (*GitHubRepositoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GitHubRepositoryList)
	err := c.cc.Invoke(ctx, GitHubQueryController_ListRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubQueryControllerClient) SearchRepositories(ctx context.Context, in *SearchGitHubRepositoriesInput, opts ...grpc.CallOption) (*GitHubRepositoryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GitHubRepositoryList)
	err := c.cc.Invoke(ctx, GitHubQueryController_SearchRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubQueryControllerClient) ListBranches(ctx context.Context, in *ListGitHubBranchesInput, opts ...grpc.CallOption) (*GitHubBranchList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GitHubBranchList)
	err := c.cc.Invoke(ctx, GitHubQueryController_ListBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubQueryControllerClient) GetTree(ctx context.Context, in *GetGitHubTreeInput, opts ...grpc.CallOption) (*GitHubTree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GitHubTree)
	err := c.cc.Invoke(ctx, GitHubQueryController_GetTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubQueryControllerClient) GetFileContent(ctx context.Context, in *GetGitHubFileContentInput, opts ...grpc.CallOption) (*GitHubFileContent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GitHubFileContent)
	err := c.cc.Invoke(ctx, GitHubQueryController_GetFileContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitHubQueryControllerServer is the server API for GitHubQueryController service.
// All implementations should embed UnimplementedGitHubQueryControllerServer
// for forward compatibility.
//
// GitHubQueryController reads GitHub repositories with the caller's saved
// github.com login, so no page holds the token.
//
// Each RPC uses the github.com connection in the caller's My vault in the
// named organization, and answers FAILED_PRECONDITION when there is none.
type GitHubQueryControllerServer interface {
	// List the repositories the connected account can reach, one page at a
	// time, most recently updated first.
	ListRepositories(context.Context, *ListGitHubRepositoriesInput) (*GitHubRepositoryList, error)
	// Search the repositories the connected account can reach.
	SearchRepositories(context.Context, *SearchGitHubRepositoriesInput) (*GitHubRepositoryList, error)
	// List a repository's branches.
	ListBranches(context.Context, *ListGitHubBranchesInput) (*GitHubBranchList, error)
	// List every file and directory of a repository at a branch or commit.
	GetTree(context.Context, *GetGitHubTreeInput) (*GitHubTree, error)
	// Read one file of a repository at a branch or commit.
	//
	// Files above 10 MiB are reported by size without their content.
	GetFileContent(context.Context, *GetGitHubFileContentInput) (*GitHubFileContent, error)
}

// UnimplementedGitHubQueryControllerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitHubQueryControllerServer struct{}

func (UnimplementedGitHubQueryControllerServer) ListRepositories(context.Context, *ListGitHubRepositoriesInput) (*GitHubRepositoryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRepositories not implemented")
}
func (UnimplementedGitHubQueryControllerServer) SearchRepositories(context.Context, *SearchGitHubRepositoriesInput) (*GitHubRepositoryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchRepositories not implemented")
}
func (UnimplementedGitHubQueryControllerServer) ListBranches(context.Context, *ListGitHubBranchesInput) (*GitHubBranchList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBranches not implemented")
}
func (UnimplementedGitHubQueryControllerServer) GetTree(context.Context, *GetGitHubTreeInput) (*GitHubTree, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTree not implemented")
}
func (UnimplementedGitHubQueryControllerServer) GetFileContent(context.Context, *GetGitHubFileContentInput) (*GitHubFileContent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileContent not implemented")
}
func (UnimplementedGitHubQueryControllerServer) testEmbeddedByValue() {}

// UnsafeGitHubQueryControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitHubQueryControllerServer will
// result in compilation errors.
type UnsafeGitHubQueryControllerServer interface {
	mustEmbedUnimplementedGitHubQueryControllerServer()
}

func RegisterGitHubQueryControllerServer(s grpc.ServiceRegistrar, srv GitHubQueryControllerServer) {
	// If the following call pancis, it indicates UnimplementedGitHubQueryControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitHubQueryController_ServiceDesc, srv)
}

func _GitHubQueryController_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGitHubRepositoriesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubQueryControllerServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubQueryController_ListRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubQueryControllerServer).ListRepositories(ctx, req.(*ListGitHubRepositoriesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubQueryController_SearchRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGitHubRepositoriesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubQueryControllerServer).SearchRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubQueryController_SearchRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubQueryControllerServer).SearchRepositories(ctx, req.(*SearchGitHubRepositoriesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubQueryController_ListBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGitHubBranchesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubQueryControllerServer).ListBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubQueryController_ListBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubQueryControllerServer).ListBranches(ctx, req.(*ListGitHubBranchesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubQueryController_GetTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGitHubTreeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubQueryControllerServer).GetTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubQueryController_GetTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubQueryControllerServer).GetTree(ctx, req.(*GetGitHubTreeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubQueryController_GetFileContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGitHubFileContentInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubQueryControllerServer).GetFileContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubQueryController_GetFileContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubQueryControllerServer).GetFileContent(ctx, req.(*GetGitHubFileContentInput))
	}
	return interceptor(ctx, in, info, handler)
}

// GitHubQueryController_ServiceDesc is the grpc.ServiceDesc for GitHubQueryController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitHubQueryController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.stigmer.platform.github.v1.GitHubQueryController",
	HandlerType: (*GitHubQueryControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "listRepositories",
			Handler:    _GitHubQueryController_ListRepositories_Handler,
		},
		{
			MethodName: "searchRepositories",
			Handler:    _GitHubQueryController_SearchRepositories_Handler,
		},
		{
			MethodName: "listBranches",
			Handler:    _GitHubQueryController_ListBranches_Handler,
		},
		{
			MethodName: "getTree",
			Handler:    _GitHubQueryController_GetTree_Handler,
		},
		{
			MethodName: "getFileContent",
			Handler:    _GitHubQueryController_GetFileContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai/stigmer/platform/github/v1/query.proto",
}
