load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cliprint",
    srcs = ["progress.go"],
    importpath = "github.com/stigmer/stigmer/client-apps/cli/internal/cli/cliprint",
    visibility = ["//client-apps/cli:__subpackages__"],
    deps = [
        "@land_charm_bubbles_v2//spinner",
        "@land_charm_bubbletea_v2//:bubbletea",
        "@land_charm_lipgloss_v2//:lipgloss",
    ],
)
