// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/workflowexecution/v1/io.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.workflowexecution.v1;

@com.google.protobuf.Generated
public interface GetEventLogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.agentic.workflowexecution.v1.GetEventLogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Execution ID to fetch events for.
   * </pre>
   *
   * <code>string execution_id = 1 [json_name = "executionId", (.buf.validate.field) = { ... }</code>
   * @return The executionId.
   */
  java.lang.String getExecutionId();
  /**
   * <pre>
   * Execution ID to fetch events for.
   * </pre>
   *
   * <code>string execution_id = 1 [json_name = "executionId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for executionId.
   */
  com.google.protobuf.ByteString
      getExecutionIdBytes();

  /**
   * <pre>
   * Return events with sequence_number strictly greater than this value.
   * </pre>
   *
   * <code>uint64 after_sequence = 2 [json_name = "afterSequence"];</code>
   * @return The afterSequence.
   */
  long getAfterSequence();

  /**
   * <pre>
   * Optional filter: return only events of these types.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.workflowexecution.v1.WorkflowEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @return A list containing the eventTypes.
   */
  java.util.List<ai.stigmer.agentic.workflowexecution.v1.WorkflowEventType> getEventTypesList();
  /**
   * <pre>
   * Optional filter: return only events of these types.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.workflowexecution.v1.WorkflowEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @return The count of eventTypes.
   */
  int getEventTypesCount();
  /**
   * <pre>
   * Optional filter: return only events of these types.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.workflowexecution.v1.WorkflowEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @param index The index of the element to return.
   * @return The eventTypes at the given index.
   */
  ai.stigmer.agentic.workflowexecution.v1.WorkflowEventType getEventTypes(int index);
  /**
   * <pre>
   * Optional filter: return only events of these types.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.workflowexecution.v1.WorkflowEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @return A list containing the enum numeric values on the wire for eventTypes.
   */
  java.util.List<java.lang.Integer>
  getEventTypesValueList();
  /**
   * <pre>
   * Optional filter: return only events of these types.
   * </pre>
   *
   * <code>repeated .ai.stigmer.agentic.workflowexecution.v1.WorkflowEventType event_types = 3 [json_name = "eventTypes"];</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of eventTypes at the given index.
   */
  int getEventTypesValue(int index);

  /**
   * <pre>
   * Optional filter: return only events for this task.
   * </pre>
   *
   * <code>string task_name = 4 [json_name = "taskName"];</code>
   * @return The taskName.
   */
  java.lang.String getTaskName();
  /**
   * <pre>
   * Optional filter: return only events for this task.
   * </pre>
   *
   * <code>string task_name = 4 [json_name = "taskName"];</code>
   * @return The bytes for taskName.
   */
  com.google.protobuf.ByteString
      getTaskNameBytes();

  /**
   * <pre>
   * Maximum number of events to return per page.
   * </pre>
   *
   * <code>int32 page_size = 5 [json_name = "pageSize"];</code>
   * @return The pageSize.
   */
  int getPageSize();
}
