// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/mcpserver/v1/spec.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.mcpserver.v1;

/**
 * <pre>
 * HttpServerConfig defines an MCP server accessible via HTTP + Server-Sent Events.
 *
 * &#64;internal
 * Communication flow:
 * 1. Agent sends JSON-RPC requests via HTTP POST
 * 2. Server streams responses via Server-Sent Events (SSE)
 *
 * Use cases:
 * - Managed MCP services (e.g., hosted by a cloud provider)
 * - MCP servers behind a reverse proxy or API gateway
 * - Sharing a single MCP server instance across multiple agents
 * </pre>
 *
 * Protobuf type {@code ai.stigmer.agentic.mcpserver.v1.HttpServerConfig}
 */
@com.google.protobuf.Generated
public final class HttpServerConfig extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:ai.stigmer.agentic.mcpserver.v1.HttpServerConfig)
    HttpServerConfigOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 0,
      /* suffix= */ "",
      "HttpServerConfig");
  }
  // Use HttpServerConfig.newBuilder() to construct.
  private HttpServerConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HttpServerConfig() {
    url_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.stigmer.agentic.mcpserver.v1.SpecProto.internal_static_ai_stigmer_agentic_mcpserver_v1_HttpServerConfig_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return ai.stigmer.agentic.mcpserver.v1.SpecProto.internal_static_ai_stigmer_agentic_mcpserver_v1_HttpServerConfig_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 2:
        return internalGetHeaders();
      case 3:
        return internalGetQueryParams();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.stigmer.agentic.mcpserver.v1.SpecProto.internal_static_ai_stigmer_agentic_mcpserver_v1_HttpServerConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.stigmer.agentic.mcpserver.v1.HttpServerConfig.class, ai.stigmer.agentic.mcpserver.v1.HttpServerConfig.Builder.class);
  }

  public static final int URL_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object url_ = "";
  /**
   * <pre>
   * Base URL of the MCP server endpoint.
   * Must be a valid HTTP or HTTPS URL.
   * Examples:
   * - "http://localhost:3000/mcp"
   * - "https://mcp.example.com/v1"
   * - "https://api.company.com/mcp/github"
   * </pre>
   *
   * <code>string url = 1 [json_name = "url", (.buf.validate.field) = { ... }</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Base URL of the MCP server endpoint.
   * Must be a valid HTTP or HTTPS URL.
   * Examples:
   * - "http://localhost:3000/mcp"
   * - "https://mcp.example.com/v1"
   * - "https://api.company.com/mcp/github"
   * </pre>
   *
   * <code>string url = 1 [json_name = "url", (.buf.validate.field) = { ... }</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADERS_FIELD_NUMBER = 2;
  private static final class HeadersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                ai.stigmer.agentic.mcpserver.v1.SpecProto.internal_static_ai_stigmer_agentic_mcpserver_v1_HttpServerConfig_HeadersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> headers_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetHeaders() {
    if (headers_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          HeadersDefaultEntryHolder.defaultEntry);
    }
    return headers_;
  }
  public int getHeadersCount() {
    return internalGetHeaders().getMap().size();
  }
  /**
   * <pre>
   * HTTP headers to include with every request.
   * Use for authentication, API versioning, or custom routing.
   *
   * Header values can reference environment variables using ${VAR_NAME} syntax.
   * These placeholders are resolved at runtime from AgentInstance's environment.
   *
   * Examples:
   * "Authorization": "Bearer ${API_TOKEN}"
   * "X-API-Version": "2024-01"
   * "X-Tenant-ID": "${TENANT_ID}"
   *
   * &#64;internal
   * Templates may also reference the reserved caller-identity keys
   * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
   * server declares them in spec.env — see the env field's reserved-key
   * contract. Placeholders resolve against the env FILTERED to declared
   * keys, so an undeclared reserved key in a template fails resolution.
   * </pre>
   *
   * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
   */
  @java.lang.Override
  public boolean containsHeaders(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetHeaders().getMap().containsKey(key);
  }
  /**
   * Use {@link #getHeadersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
    return getHeadersMap();
  }
  /**
   * <pre>
   * HTTP headers to include with every request.
   * Use for authentication, API versioning, or custom routing.
   *
   * Header values can reference environment variables using ${VAR_NAME} syntax.
   * These placeholders are resolved at runtime from AgentInstance's environment.
   *
   * Examples:
   * "Authorization": "Bearer ${API_TOKEN}"
   * "X-API-Version": "2024-01"
   * "X-Tenant-ID": "${TENANT_ID}"
   *
   * &#64;internal
   * Templates may also reference the reserved caller-identity keys
   * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
   * server declares them in spec.env — see the env field's reserved-key
   * contract. Placeholders resolve against the env FILTERED to declared
   * keys, so an undeclared reserved key in a template fails resolution.
   * </pre>
   *
   * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
    return internalGetHeaders().getMap();
  }
  /**
   * <pre>
   * HTTP headers to include with every request.
   * Use for authentication, API versioning, or custom routing.
   *
   * Header values can reference environment variables using ${VAR_NAME} syntax.
   * These placeholders are resolved at runtime from AgentInstance's environment.
   *
   * Examples:
   * "Authorization": "Bearer ${API_TOKEN}"
   * "X-API-Version": "2024-01"
   * "X-Tenant-ID": "${TENANT_ID}"
   *
   * &#64;internal
   * Templates may also reference the reserved caller-identity keys
   * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
   * server declares them in spec.env — see the env field's reserved-key
   * contract. Placeholders resolve against the env FILTERED to declared
   * keys, so an undeclared reserved key in a template fails resolution.
   * </pre>
   *
   * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getHeadersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetHeaders().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * HTTP headers to include with every request.
   * Use for authentication, API versioning, or custom routing.
   *
   * Header values can reference environment variables using ${VAR_NAME} syntax.
   * These placeholders are resolved at runtime from AgentInstance's environment.
   *
   * Examples:
   * "Authorization": "Bearer ${API_TOKEN}"
   * "X-API-Version": "2024-01"
   * "X-Tenant-ID": "${TENANT_ID}"
   *
   * &#64;internal
   * Templates may also reference the reserved caller-identity keys
   * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
   * server declares them in spec.env — see the env field's reserved-key
   * contract. Placeholders resolve against the env FILTERED to declared
   * keys, so an undeclared reserved key in a template fails resolution.
   * </pre>
   *
   * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
   */
  @java.lang.Override
  public java.lang.String getHeadersOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetHeaders().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int QUERY_PARAMS_FIELD_NUMBER = 3;
  private static final class QueryParamsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                ai.stigmer.agentic.mcpserver.v1.SpecProto.internal_static_ai_stigmer_agentic_mcpserver_v1_HttpServerConfig_QueryParamsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> queryParams_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetQueryParams() {
    if (queryParams_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          QueryParamsDefaultEntryHolder.defaultEntry);
    }
    return queryParams_;
  }
  public int getQueryParamsCount() {
    return internalGetQueryParams().getMap().size();
  }
  /**
   * <pre>
   * Query parameters to append to the URL.
   * Values can reference environment variables using ${VAR_NAME} syntax.
   *
   * Examples:
   * "region": "${AWS_REGION}"
   * "version": "v1"
   * </pre>
   *
   * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
   */
  @java.lang.Override
  public boolean containsQueryParams(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetQueryParams().getMap().containsKey(key);
  }
  /**
   * Use {@link #getQueryParamsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getQueryParams() {
    return getQueryParamsMap();
  }
  /**
   * <pre>
   * Query parameters to append to the URL.
   * Values can reference environment variables using ${VAR_NAME} syntax.
   *
   * Examples:
   * "region": "${AWS_REGION}"
   * "version": "v1"
   * </pre>
   *
   * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getQueryParamsMap() {
    return internalGetQueryParams().getMap();
  }
  /**
   * <pre>
   * Query parameters to append to the URL.
   * Values can reference environment variables using ${VAR_NAME} syntax.
   *
   * Examples:
   * "region": "${AWS_REGION}"
   * "version": "v1"
   * </pre>
   *
   * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getQueryParamsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetQueryParams().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Query parameters to append to the URL.
   * Values can reference environment variables using ${VAR_NAME} syntax.
   *
   * Examples:
   * "region": "${AWS_REGION}"
   * "version": "v1"
   * </pre>
   *
   * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
   */
  @java.lang.Override
  public java.lang.String getQueryParamsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetQueryParams().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TIMEOUT_SECONDS_FIELD_NUMBER = 4;
  private int timeoutSeconds_ = 0;
  /**
   * <pre>
   * Timeout for HTTP requests in seconds.
   * Applies to both the initial connection and response streaming.
   * Default: 30 seconds if not specified.
   * Set higher values for MCP servers that perform long-running operations.
   * </pre>
   *
   * <code>int32 timeout_seconds = 4 [json_name = "timeoutSeconds", (.buf.validate.field) = { ... }</code>
   * @return The timeoutSeconds.
   */
  @java.lang.Override
  public int getTimeoutSeconds() {
    return timeoutSeconds_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(url_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, url_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetHeaders(),
        HeadersDefaultEntryHolder.defaultEntry,
        2);
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetQueryParams(),
        QueryParamsDefaultEntryHolder.defaultEntry,
        3);
    if (timeoutSeconds_ != 0) {
      output.writeInt32(4, timeoutSeconds_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(url_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, url_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetHeaders().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      headers__ = HeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, headers__);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetQueryParams().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      queryParams__ = QueryParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, queryParams__);
    }
    if (timeoutSeconds_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, timeoutSeconds_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.stigmer.agentic.mcpserver.v1.HttpServerConfig)) {
      return super.equals(obj);
    }
    ai.stigmer.agentic.mcpserver.v1.HttpServerConfig other = (ai.stigmer.agentic.mcpserver.v1.HttpServerConfig) obj;

    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (!internalGetHeaders().equals(
        other.internalGetHeaders())) return false;
    if (!internalGetQueryParams().equals(
        other.internalGetQueryParams())) return false;
    if (getTimeoutSeconds()
        != other.getTimeoutSeconds()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    if (!internalGetHeaders().getMap().isEmpty()) {
      hash = (37 * hash) + HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetHeaders().hashCode();
    }
    if (!internalGetQueryParams().getMap().isEmpty()) {
      hash = (37 * hash) + QUERY_PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetQueryParams().hashCode();
    }
    hash = (37 * hash) + TIMEOUT_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + getTimeoutSeconds();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.stigmer.agentic.mcpserver.v1.HttpServerConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * HttpServerConfig defines an MCP server accessible via HTTP + Server-Sent Events.
   *
   * &#64;internal
   * Communication flow:
   * 1. Agent sends JSON-RPC requests via HTTP POST
   * 2. Server streams responses via Server-Sent Events (SSE)
   *
   * Use cases:
   * - Managed MCP services (e.g., hosted by a cloud provider)
   * - MCP servers behind a reverse proxy or API gateway
   * - Sharing a single MCP server instance across multiple agents
   * </pre>
   *
   * Protobuf type {@code ai.stigmer.agentic.mcpserver.v1.HttpServerConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ai.stigmer.agentic.mcpserver.v1.HttpServerConfig)
      ai.stigmer.agentic.mcpserver.v1.HttpServerConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.stigmer.agentic.mcpserver.v1.SpecProto.internal_static_ai_stigmer_agentic_mcpserver_v1_HttpServerConfig_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetHeaders();
        case 3:
          return internalGetQueryParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableHeaders();
        case 3:
          return internalGetMutableQueryParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.stigmer.agentic.mcpserver.v1.SpecProto.internal_static_ai_stigmer_agentic_mcpserver_v1_HttpServerConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.stigmer.agentic.mcpserver.v1.HttpServerConfig.class, ai.stigmer.agentic.mcpserver.v1.HttpServerConfig.Builder.class);
    }

    // Construct using ai.stigmer.agentic.mcpserver.v1.HttpServerConfig.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      url_ = "";
      internalGetMutableHeaders().clear();
      internalGetMutableQueryParams().clear();
      timeoutSeconds_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.stigmer.agentic.mcpserver.v1.SpecProto.internal_static_ai_stigmer_agentic_mcpserver_v1_HttpServerConfig_descriptor;
    }

    @java.lang.Override
    public ai.stigmer.agentic.mcpserver.v1.HttpServerConfig getDefaultInstanceForType() {
      return ai.stigmer.agentic.mcpserver.v1.HttpServerConfig.getDefaultInstance();
    }

    @java.lang.Override
    public ai.stigmer.agentic.mcpserver.v1.HttpServerConfig build() {
      ai.stigmer.agentic.mcpserver.v1.HttpServerConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.stigmer.agentic.mcpserver.v1.HttpServerConfig buildPartial() {
      ai.stigmer.agentic.mcpserver.v1.HttpServerConfig result = new ai.stigmer.agentic.mcpserver.v1.HttpServerConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ai.stigmer.agentic.mcpserver.v1.HttpServerConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.url_ = url_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.headers_ = internalGetHeaders();
        result.headers_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.queryParams_ = internalGetQueryParams();
        result.queryParams_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timeoutSeconds_ = timeoutSeconds_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.stigmer.agentic.mcpserver.v1.HttpServerConfig) {
        return mergeFrom((ai.stigmer.agentic.mcpserver.v1.HttpServerConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.stigmer.agentic.mcpserver.v1.HttpServerConfig other) {
      if (other == ai.stigmer.agentic.mcpserver.v1.HttpServerConfig.getDefaultInstance()) return this;
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      internalGetMutableHeaders().mergeFrom(
          other.internalGetHeaders());
      bitField0_ |= 0x00000002;
      internalGetMutableQueryParams().mergeFrom(
          other.internalGetQueryParams());
      bitField0_ |= 0x00000004;
      if (other.getTimeoutSeconds() != 0) {
        setTimeoutSeconds(other.getTimeoutSeconds());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              url_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              headers__ = input.readMessage(
                  HeadersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableHeaders().getMutableMap().put(
                  headers__.getKey(), headers__.getValue());
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              queryParams__ = input.readMessage(
                  QueryParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableQueryParams().getMutableMap().put(
                  queryParams__.getKey(), queryParams__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              timeoutSeconds_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object url_ = "";
    /**
     * <pre>
     * Base URL of the MCP server endpoint.
     * Must be a valid HTTP or HTTPS URL.
     * Examples:
     * - "http://localhost:3000/mcp"
     * - "https://mcp.example.com/v1"
     * - "https://api.company.com/mcp/github"
     * </pre>
     *
     * <code>string url = 1 [json_name = "url", (.buf.validate.field) = { ... }</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Base URL of the MCP server endpoint.
     * Must be a valid HTTP or HTTPS URL.
     * Examples:
     * - "http://localhost:3000/mcp"
     * - "https://mcp.example.com/v1"
     * - "https://api.company.com/mcp/github"
     * </pre>
     *
     * <code>string url = 1 [json_name = "url", (.buf.validate.field) = { ... }</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Base URL of the MCP server endpoint.
     * Must be a valid HTTP or HTTPS URL.
     * Examples:
     * - "http://localhost:3000/mcp"
     * - "https://mcp.example.com/v1"
     * - "https://api.company.com/mcp/github"
     * </pre>
     *
     * <code>string url = 1 [json_name = "url", (.buf.validate.field) = { ... }</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      url_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Base URL of the MCP server endpoint.
     * Must be a valid HTTP or HTTPS URL.
     * Examples:
     * - "http://localhost:3000/mcp"
     * - "https://mcp.example.com/v1"
     * - "https://api.company.com/mcp/github"
     * </pre>
     *
     * <code>string url = 1 [json_name = "url", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      url_ = getDefaultInstance().getUrl();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Base URL of the MCP server endpoint.
     * Must be a valid HTTP or HTTPS URL.
     * Examples:
     * - "http://localhost:3000/mcp"
     * - "https://mcp.example.com/v1"
     * - "https://api.company.com/mcp/github"
     * </pre>
     *
     * <code>string url = 1 [json_name = "url", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      url_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> headers_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetHeaders() {
      if (headers_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeadersDefaultEntryHolder.defaultEntry);
      }
      return headers_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableHeaders() {
      if (headers_ == null) {
        headers_ = com.google.protobuf.MapField.newMapField(
            HeadersDefaultEntryHolder.defaultEntry);
      }
      if (!headers_.isMutable()) {
        headers_ = headers_.copy();
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return headers_;
    }
    public int getHeadersCount() {
      return internalGetHeaders().getMap().size();
    }
    /**
     * <pre>
     * HTTP headers to include with every request.
     * Use for authentication, API versioning, or custom routing.
     *
     * Header values can reference environment variables using ${VAR_NAME} syntax.
     * These placeholders are resolved at runtime from AgentInstance's environment.
     *
     * Examples:
     * "Authorization": "Bearer ${API_TOKEN}"
     * "X-API-Version": "2024-01"
     * "X-Tenant-ID": "${TENANT_ID}"
     *
     * &#64;internal
     * Templates may also reference the reserved caller-identity keys
     * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
     * server declares them in spec.env — see the env field's reserved-key
     * contract. Placeholders resolve against the env FILTERED to declared
     * keys, so an undeclared reserved key in a template fails resolution.
     * </pre>
     *
     * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
     */
    @java.lang.Override
    public boolean containsHeaders(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetHeaders().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
      return getHeadersMap();
    }
    /**
     * <pre>
     * HTTP headers to include with every request.
     * Use for authentication, API versioning, or custom routing.
     *
     * Header values can reference environment variables using ${VAR_NAME} syntax.
     * These placeholders are resolved at runtime from AgentInstance's environment.
     *
     * Examples:
     * "Authorization": "Bearer ${API_TOKEN}"
     * "X-API-Version": "2024-01"
     * "X-Tenant-ID": "${TENANT_ID}"
     *
     * &#64;internal
     * Templates may also reference the reserved caller-identity keys
     * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
     * server declares them in spec.env — see the env field's reserved-key
     * contract. Placeholders resolve against the env FILTERED to declared
     * keys, so an undeclared reserved key in a template fails resolution.
     * </pre>
     *
     * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
      return internalGetHeaders().getMap();
    }
    /**
     * <pre>
     * HTTP headers to include with every request.
     * Use for authentication, API versioning, or custom routing.
     *
     * Header values can reference environment variables using ${VAR_NAME} syntax.
     * These placeholders are resolved at runtime from AgentInstance's environment.
     *
     * Examples:
     * "Authorization": "Bearer ${API_TOKEN}"
     * "X-API-Version": "2024-01"
     * "X-Tenant-ID": "${TENANT_ID}"
     *
     * &#64;internal
     * Templates may also reference the reserved caller-identity keys
     * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
     * server declares them in spec.env — see the env field's reserved-key
     * contract. Placeholders resolve against the env FILTERED to declared
     * keys, so an undeclared reserved key in a template fails resolution.
     * </pre>
     *
     * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getHeadersOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * HTTP headers to include with every request.
     * Use for authentication, API versioning, or custom routing.
     *
     * Header values can reference environment variables using ${VAR_NAME} syntax.
     * These placeholders are resolved at runtime from AgentInstance's environment.
     *
     * Examples:
     * "Authorization": "Bearer ${API_TOKEN}"
     * "X-API-Version": "2024-01"
     * "X-Tenant-ID": "${TENANT_ID}"
     *
     * &#64;internal
     * Templates may also reference the reserved caller-identity keys
     * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
     * server declares them in spec.env — see the env field's reserved-key
     * contract. Placeholders resolve against the env FILTERED to declared
     * keys, so an undeclared reserved key in a template fails resolution.
     * </pre>
     *
     * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
     */
    @java.lang.Override
    public java.lang.String getHeadersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearHeaders() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableHeaders().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * HTTP headers to include with every request.
     * Use for authentication, API versioning, or custom routing.
     *
     * Header values can reference environment variables using ${VAR_NAME} syntax.
     * These placeholders are resolved at runtime from AgentInstance's environment.
     *
     * Examples:
     * "Authorization": "Bearer ${API_TOKEN}"
     * "X-API-Version": "2024-01"
     * "X-Tenant-ID": "${TENANT_ID}"
     *
     * &#64;internal
     * Templates may also reference the reserved caller-identity keys
     * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
     * server declares them in spec.env — see the env field's reserved-key
     * contract. Placeholders resolve against the env FILTERED to declared
     * keys, so an undeclared reserved key in a template fails resolution.
     * </pre>
     *
     * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
     */
    public Builder removeHeaders(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableHeaders().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableHeaders() {
      bitField0_ |= 0x00000002;
      return internalGetMutableHeaders().getMutableMap();
    }
    /**
     * <pre>
     * HTTP headers to include with every request.
     * Use for authentication, API versioning, or custom routing.
     *
     * Header values can reference environment variables using ${VAR_NAME} syntax.
     * These placeholders are resolved at runtime from AgentInstance's environment.
     *
     * Examples:
     * "Authorization": "Bearer ${API_TOKEN}"
     * "X-API-Version": "2024-01"
     * "X-Tenant-ID": "${TENANT_ID}"
     *
     * &#64;internal
     * Templates may also reference the reserved caller-identity keys
     * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
     * server declares them in spec.env — see the env field's reserved-key
     * contract. Placeholders resolve against the env FILTERED to declared
     * keys, so an undeclared reserved key in a template fails resolution.
     * </pre>
     *
     * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
     */
    public Builder putHeaders(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableHeaders().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <pre>
     * HTTP headers to include with every request.
     * Use for authentication, API versioning, or custom routing.
     *
     * Header values can reference environment variables using ${VAR_NAME} syntax.
     * These placeholders are resolved at runtime from AgentInstance's environment.
     *
     * Examples:
     * "Authorization": "Bearer ${API_TOKEN}"
     * "X-API-Version": "2024-01"
     * "X-Tenant-ID": "${TENANT_ID}"
     *
     * &#64;internal
     * Templates may also reference the reserved caller-identity keys
     * (STIGMER_CALLER_IDENTITY_KIND / _VALUE, STIGMER_SESSION_ID) when the
     * server declares them in spec.env — see the env field's reserved-key
     * contract. Placeholders resolve against the env FILTERED to declared
     * keys, so an undeclared reserved key in a template fails resolution.
     * </pre>
     *
     * <code>map&lt;string, string&gt; headers = 2 [json_name = "headers"];</code>
     */
    public Builder putAllHeaders(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableHeaders().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> queryParams_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetQueryParams() {
      if (queryParams_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            QueryParamsDefaultEntryHolder.defaultEntry);
      }
      return queryParams_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableQueryParams() {
      if (queryParams_ == null) {
        queryParams_ = com.google.protobuf.MapField.newMapField(
            QueryParamsDefaultEntryHolder.defaultEntry);
      }
      if (!queryParams_.isMutable()) {
        queryParams_ = queryParams_.copy();
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return queryParams_;
    }
    public int getQueryParamsCount() {
      return internalGetQueryParams().getMap().size();
    }
    /**
     * <pre>
     * Query parameters to append to the URL.
     * Values can reference environment variables using ${VAR_NAME} syntax.
     *
     * Examples:
     * "region": "${AWS_REGION}"
     * "version": "v1"
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
     */
    @java.lang.Override
    public boolean containsQueryParams(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetQueryParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getQueryParamsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getQueryParams() {
      return getQueryParamsMap();
    }
    /**
     * <pre>
     * Query parameters to append to the URL.
     * Values can reference environment variables using ${VAR_NAME} syntax.
     *
     * Examples:
     * "region": "${AWS_REGION}"
     * "version": "v1"
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getQueryParamsMap() {
      return internalGetQueryParams().getMap();
    }
    /**
     * <pre>
     * Query parameters to append to the URL.
     * Values can reference environment variables using ${VAR_NAME} syntax.
     *
     * Examples:
     * "region": "${AWS_REGION}"
     * "version": "v1"
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getQueryParamsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetQueryParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Query parameters to append to the URL.
     * Values can reference environment variables using ${VAR_NAME} syntax.
     *
     * Examples:
     * "region": "${AWS_REGION}"
     * "version": "v1"
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
     */
    @java.lang.Override
    public java.lang.String getQueryParamsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetQueryParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearQueryParams() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableQueryParams().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Query parameters to append to the URL.
     * Values can reference environment variables using ${VAR_NAME} syntax.
     *
     * Examples:
     * "region": "${AWS_REGION}"
     * "version": "v1"
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
     */
    public Builder removeQueryParams(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableQueryParams().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableQueryParams() {
      bitField0_ |= 0x00000004;
      return internalGetMutableQueryParams().getMutableMap();
    }
    /**
     * <pre>
     * Query parameters to append to the URL.
     * Values can reference environment variables using ${VAR_NAME} syntax.
     *
     * Examples:
     * "region": "${AWS_REGION}"
     * "version": "v1"
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
     */
    public Builder putQueryParams(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableQueryParams().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <pre>
     * Query parameters to append to the URL.
     * Values can reference environment variables using ${VAR_NAME} syntax.
     *
     * Examples:
     * "region": "${AWS_REGION}"
     * "version": "v1"
     * </pre>
     *
     * <code>map&lt;string, string&gt; query_params = 3 [json_name = "queryParams"];</code>
     */
    public Builder putAllQueryParams(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableQueryParams().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }

    private int timeoutSeconds_ ;
    /**
     * <pre>
     * Timeout for HTTP requests in seconds.
     * Applies to both the initial connection and response streaming.
     * Default: 30 seconds if not specified.
     * Set higher values for MCP servers that perform long-running operations.
     * </pre>
     *
     * <code>int32 timeout_seconds = 4 [json_name = "timeoutSeconds", (.buf.validate.field) = { ... }</code>
     * @return The timeoutSeconds.
     */
    @java.lang.Override
    public int getTimeoutSeconds() {
      return timeoutSeconds_;
    }
    /**
     * <pre>
     * Timeout for HTTP requests in seconds.
     * Applies to both the initial connection and response streaming.
     * Default: 30 seconds if not specified.
     * Set higher values for MCP servers that perform long-running operations.
     * </pre>
     *
     * <code>int32 timeout_seconds = 4 [json_name = "timeoutSeconds", (.buf.validate.field) = { ... }</code>
     * @param value The timeoutSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setTimeoutSeconds(int value) {

      timeoutSeconds_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timeout for HTTP requests in seconds.
     * Applies to both the initial connection and response streaming.
     * Default: 30 seconds if not specified.
     * Set higher values for MCP servers that perform long-running operations.
     * </pre>
     *
     * <code>int32 timeout_seconds = 4 [json_name = "timeoutSeconds", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeoutSeconds() {
      bitField0_ = (bitField0_ & ~0x00000008);
      timeoutSeconds_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ai.stigmer.agentic.mcpserver.v1.HttpServerConfig)
  }

  // @@protoc_insertion_point(class_scope:ai.stigmer.agentic.mcpserver.v1.HttpServerConfig)
  private static final ai.stigmer.agentic.mcpserver.v1.HttpServerConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.stigmer.agentic.mcpserver.v1.HttpServerConfig();
  }

  public static ai.stigmer.agentic.mcpserver.v1.HttpServerConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HttpServerConfig>
      PARSER = new com.google.protobuf.AbstractParser<HttpServerConfig>() {
    @java.lang.Override
    public HttpServerConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HttpServerConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HttpServerConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.stigmer.agentic.mcpserver.v1.HttpServerConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

