// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/mcpserver/v1/io.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.mcpserver.v1;

@com.google.protobuf.Generated
public interface McpServerIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.agentic.mcpserver.v1.McpServerId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unique identifier of the MCP server resource.
   * This is the system-generated ID (metadata.id), not the slug.
   * Format: "mcp-" followed by a unique identifier.
   * Example: "mcp-abc123xyz"
   * </pre>
   *
   * <code>string value = 1 [json_name = "value", (.buf.validate.field) = { ... }</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <pre>
   * The unique identifier of the MCP server resource.
   * This is the system-generated ID (metadata.id), not the slug.
   * Format: "mcp-" followed by a unique identifier.
   * Example: "mcp-abc123xyz"
   * </pre>
   *
   * <code>string value = 1 [json_name = "value", (.buf.validate.field) = { ... }</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
