package root

import (
	"fmt"
	"strings"

	"github.com/charmbracelet/x/ansi"
	"github.com/stigmer/stigmer/client-apps/cli/pkg/executiontui"
	"github.com/stigmer/stigmer/client-apps/cli/pkg/termctl"
	"github.com/stigmer/stigmer/client-apps/cli/pkg/toolrender"
)

// initPreApprovalStreaming starts the typewriter streaming mode for a
// write/edit tool whose content is being generated by the AI. Prints
// the expanded header and separator, then sets streaming state so
// subsequent ToolStreamDeltaEvents append content below.
//
// The content display is capped at maxStreamContentLines (derived from
// terminal height) to keep the total output within the visible terminal.
// This ensures deterministic row counting for EraseLines-based collapse.
//
// When the tool's primary arg (e.g. file path) is not yet available in
// Args, header rendering is deferred to the first ToolStreamDeltaEvent,
// which carries an updated ToolCall with populated args.
func (r *inlineRenderer) initPreApprovalStreaming(e executiontui.ToolRunningEvent) {
	r.finishAIStreamIfNeeded()
	r.flushPendingReads()

	r.activeStreamToolID = e.ToolCallID
	r.toolStreamedBytes = 0
	r.streamSubAgentID = e.SubAgentID
	r.streamContentLines = 0
	r.streamTruncationShown = false
	r.maxStreamContentLines = approvalContentBudget(termctl.Height(r.cfg.status, 40))

	if !toolrender.HasPrimaryArg(e.ToolCall) {
		r.streamHeaderDeferred = true
		r.streamHeaderRows = 0
		r.streamLineCount = 0
		return
	}

	r.renderStreamHeader(e.ToolCall, e.SubAgentID)
}

// renderStreamHeader prints the pre-approval separator and header for
// a streaming write/edit tool, and updates the row-tracking state.
func (r *inlineRenderer) renderStreamHeader(tc toolrender.ToolCallInfo, subAgentID string) {
	width := termctl.Width(r.cfg.status, 80)
	sep := toolrender.ApprovalSeparator(width)
	header := toolrender.ExpandedApprovalHeader(tc, r.compactOpts)
	output := sep + "\n" + header + "\n"

	if subAgentID != "" {
		output = toolrender.GutterWrap(output)
	}
	fmt.Fprint(r.cfg.status, output)
	r.flushWriter(r.cfg.status)

	r.streamHeaderRows = termctl.DisplayRows(output, width)
	r.streamLineCount = r.streamHeaderRows
}

// initPostApprovalStreaming starts the live output streaming mode for a
// shell tool that the user just approved. Prints the compact running
// header, then sets streaming state so subsequent ToolStreamDeltaEvents
// append command output below.
func (r *inlineRenderer) initPostApprovalStreaming(toolCallID string, tc toolrender.ToolCallInfo, subAgentID string) {
	header := toolrender.RenderCompactRunning(tc, r.compactOpts)
	if subAgentID != "" {
		header = toolrender.GutterWrap(header)
	}
	r.statusf("%s\n", header)

	width := termctl.Width(r.cfg.status, 80)
	r.activeStreamToolID = toolCallID
	r.toolStreamedBytes = 0
	r.streamHeaderRows = termctl.DisplayRows(header+"\n", width)
	r.streamLineCount = r.streamHeaderRows
	r.streamSubAgentID = subAgentID
}

// renderToolStreamDelta prints new content bytes from a streaming tool.
// Uses the same append-only pattern as renderAIStreamDelta: only bytes
// beyond streamedBytes are printed.
//
// For pre-approval streaming (maxStreamContentLines > 0), content is
// capped at maxStreamContentLines. Once the cap is reached, a truncation
// indicator is printed and updated in-place as more content arrives.
// Each displayed line is width-clamped to prevent terminal line wrapping,
// keeping the row count deterministic for EraseLines collapse.
//
// For post-approval streaming (maxStreamContentLines == 0), content flows
// uncapped as before.
//
// When the header was deferred (streamHeaderDeferred), the first delta
// renders the header using e.ToolCall's updated Args before appending
// content. If Args still lack the primary arg, the header is rendered
// anyway to avoid indefinite deferral.
func (r *inlineRenderer) renderToolStreamDelta(e executiontui.ToolStreamDeltaEvent) {
	if r.streamHeaderDeferred {
		r.streamHeaderDeferred = false
		r.renderStreamHeader(e.ToolCall, r.streamSubAgentID)
	}

	content := resolveStreamContent(e)
	if len(content) <= r.toolStreamedBytes {
		return
	}

	newBytes := content[r.toolStreamedBytes:]
	r.toolStreamedBytes = len(content)

	cappingEnabled := r.maxStreamContentLines > 0

	if !cappingEnabled {
		output := newBytes
		if r.streamSubAgentID != "" {
			output = toolrender.GutterWrap(output)
		}
		fmt.Fprint(r.cfg.status, output)
		r.flushWriter(r.cfg.status)

		width := termctl.Width(r.cfg.status, 80)
		displayContent := content
		if r.streamSubAgentID != "" {
			displayContent = toolrender.GutterWrap(content)
		}
		r.streamLineCount = r.streamHeaderRows + termctl.DisplayRows(displayContent, width)
		return
	}

	width := termctl.Width(r.cfg.status, 80)
	maxVisibleWidth := width - 1
	if r.streamSubAgentID != "" {
		maxVisibleWidth = width - 1 - toolrender.GutterWidth()
	}

	totalContentLines := strings.Count(content, "\n")

	if r.streamContentLines >= r.maxStreamContentLines {
		if r.streamTruncationShown {
			termctl.EraseLines(r.cfg.status, 1)
		}
		overflow := totalContentLines - r.maxStreamContentLines
		if overflow < 0 {
			overflow = 0
		}
		indicator := toolrender.StreamTruncationIndicator(overflow)
		if r.streamSubAgentID != "" {
			indicator = toolrender.GutterWrap(indicator)
		}
		fmt.Fprint(r.cfg.status, indicator)
		r.flushWriter(r.cfg.status)
		r.streamTruncationShown = true
		return
	}

	newLines := strings.Split(newBytes, "\n")
	var outputBuf strings.Builder
	for i, line := range newLines {
		if i > 0 {
			outputBuf.WriteByte('\n')
			r.streamContentLines++
			if r.streamContentLines >= r.maxStreamContentLines {
				overflow := totalContentLines - r.maxStreamContentLines
				if overflow < 0 {
					overflow = 0
				}
				out := outputBuf.String()
				if r.streamSubAgentID != "" {
					out = toolrender.GutterWrap(out)
				}
				fmt.Fprint(r.cfg.status, out)

				indicator := toolrender.StreamTruncationIndicator(overflow)
				if r.streamSubAgentID != "" {
					indicator = toolrender.GutterWrap(indicator)
				}
				fmt.Fprint(r.cfg.status, indicator)
				r.flushWriter(r.cfg.status)
				r.streamTruncationShown = true
				r.streamLineCount = r.streamHeaderRows + r.streamContentLines + 1
				return
			}
		}
		outputBuf.WriteString(truncateLineWidth(line, maxVisibleWidth))
	}

	out := outputBuf.String()
	if r.streamSubAgentID != "" {
		out = toolrender.GutterWrap(out)
	}
	fmt.Fprint(r.cfg.status, out)
	r.flushWriter(r.cfg.status)

	r.streamLineCount = r.streamHeaderRows + r.streamContentLines + 1
}

// completeStreamingTool handles ToolCompletedEvent for a tool that was
// streaming output. Erases the streaming content (header + output) when
// cursor control is available, then prints the final compact result.
func (r *inlineRenderer) completeStreamingTool(e executiontui.ToolCompletedEvent) {
	if termctl.IsSupported(r.cfg.status) && r.streamLineCount > 0 {
		termctl.EraseLines(r.cfg.status, r.streamLineCount)
	}

	line := toolrender.RenderCompact(e.ToolCall, r.compactOpts)
	if r.streamSubAgentID != "" {
		line = toolrender.GutterWrap(line)
	}
	r.statusf("%s\n", line)
	r.clearStreamingState()
}

// clearStreamingState resets all streaming tracking fields to their
// zero values. Called after streaming completes — either by
// completeStreamingTool (post-approval) or renderToolWaitingApproval
// (pre-approval transition to approval flow).
func (r *inlineRenderer) clearStreamingState() {
	r.activeStreamToolID = ""
	r.toolStreamedBytes = 0
	r.streamHeaderRows = 0
	r.streamLineCount = 0
	r.streamSubAgentID = ""
	r.streamHeaderDeferred = false
	r.maxStreamContentLines = 0
	r.streamContentLines = 0
	r.streamTruncationShown = false
}

// resolveStreamContent extracts the displayable content from a
// ToolStreamDeltaEvent. Prefers e.Content (shell output, generic
// streaming). Falls back to ExpandedApprovalContent for write/edit
// tools where content lives in Args rather than the Content field.
func resolveStreamContent(e executiontui.ToolStreamDeltaEvent) string {
	if e.Content != "" {
		return e.Content
	}
	return toolrender.ExpandedApprovalContent(e.ToolCall)
}

// truncateLineWidth clamps a single line to maxWidth visible characters.
// ANSI escape codes are preserved and do not count toward the width.
func truncateLineWidth(line string, maxWidth int) string {
	if maxWidth <= 0 || ansi.StringWidth(line) <= maxWidth {
		return line
	}
	if maxWidth <= 3 {
		return ansi.Truncate(line, maxWidth, "")
	}
	return ansi.Truncate(line, maxWidth-1, "…")
}
