// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ai/stigmer/agentic/plugin/v1/spec.proto
// Protobuf Java Version: 4.34.0

package ai.stigmer.agentic.plugin.v1;

@com.google.protobuf.Generated
public interface PluginSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ai.stigmer.agentic.plugin.v1.PluginSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Plugin name as written in the manifest; the source of the resource's slug.
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Plugin name as written in the manifest; the source of the resource's slug.
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Version string as written in the manifest, typically Semantic Versioning.
   *
   * &#64;internal
   * Also the plugin's single-holder audit tag when it matches the tag
   * pattern; the archive digest, not this string, is the version identity.
   * </pre>
   *
   * <code>string version = 2 [json_name = "version"];</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * Version string as written in the manifest, typically Semantic Versioning.
   *
   * &#64;internal
   * Also the plugin's single-holder audit tag when it matches the tag
   * pattern; the archive digest, not this string, is the version identity.
   * </pre>
   *
   * <code>string version = 2 [json_name = "version"];</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * Human-readable description from the manifest.
   * </pre>
   *
   * <code>string description = 3 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Human-readable description from the manifest.
   * </pre>
   *
   * <code>string description = 3 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * Author information from the manifest.
   * </pre>
   *
   * <code>.ai.stigmer.agentic.plugin.v1.PluginAuthor author = 4 [json_name = "author"];</code>
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   * <pre>
   * Author information from the manifest.
   * </pre>
   *
   * <code>.ai.stigmer.agentic.plugin.v1.PluginAuthor author = 4 [json_name = "author"];</code>
   * @return The author.
   */
  ai.stigmer.agentic.plugin.v1.PluginAuthor getAuthor();
  /**
   * <pre>
   * Author information from the manifest.
   * </pre>
   *
   * <code>.ai.stigmer.agentic.plugin.v1.PluginAuthor author = 4 [json_name = "author"];</code>
   */
  ai.stigmer.agentic.plugin.v1.PluginAuthorOrBuilder getAuthorOrBuilder();

  /**
   * <pre>
   * Homepage URL from the manifest.
   * </pre>
   *
   * <code>string homepage = 5 [json_name = "homepage"];</code>
   * @return The homepage.
   */
  java.lang.String getHomepage();
  /**
   * <pre>
   * Homepage URL from the manifest.
   * </pre>
   *
   * <code>string homepage = 5 [json_name = "homepage"];</code>
   * @return The bytes for homepage.
   */
  com.google.protobuf.ByteString
      getHomepageBytes();

  /**
   * <pre>
   * Source repository URL from the manifest.
   * </pre>
   *
   * <code>string repository = 6 [json_name = "repository"];</code>
   * @return The repository.
   */
  java.lang.String getRepository();
  /**
   * <pre>
   * Source repository URL from the manifest.
   * </pre>
   *
   * <code>string repository = 6 [json_name = "repository"];</code>
   * @return The bytes for repository.
   */
  com.google.protobuf.ByteString
      getRepositoryBytes();

  /**
   * <pre>
   * License identifier from the manifest.
   * </pre>
   *
   * <code>string license = 7 [json_name = "license"];</code>
   * @return The license.
   */
  java.lang.String getLicense();
  /**
   * <pre>
   * License identifier from the manifest.
   * </pre>
   *
   * <code>string license = 7 [json_name = "license"];</code>
   * @return The bytes for license.
   */
  com.google.protobuf.ByteString
      getLicenseBytes();

  /**
   * <pre>
   * Keywords from the manifest, for search and marketplace display.
   * </pre>
   *
   * <code>repeated string keywords = 8 [json_name = "keywords"];</code>
   * @return A list containing the keywords.
   */
  java.util.List<java.lang.String>
      getKeywordsList();
  /**
   * <pre>
   * Keywords from the manifest, for search and marketplace display.
   * </pre>
   *
   * <code>repeated string keywords = 8 [json_name = "keywords"];</code>
   * @return The count of keywords.
   */
  int getKeywordsCount();
  /**
   * <pre>
   * Keywords from the manifest, for search and marketplace display.
   * </pre>
   *
   * <code>repeated string keywords = 8 [json_name = "keywords"];</code>
   * @param index The index of the element to return.
   * @return The keywords at the given index.
   */
  java.lang.String getKeywords(int index);
  /**
   * <pre>
   * Keywords from the manifest, for search and marketplace display.
   * </pre>
   *
   * <code>repeated string keywords = 8 [json_name = "keywords"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the keywords at the given index.
   */
  com.google.protobuf.ByteString
      getKeywordsBytes(int index);

  /**
   * <pre>
   * The manifest dialect the package was written in.
   * </pre>
   *
   * <code>.ai.stigmer.agentic.plugin.v1.PluginDialect dialect = 9 [json_name = "dialect"];</code>
   * @return The enum numeric value on the wire for dialect.
   */
  int getDialectValue();
  /**
   * <pre>
   * The manifest dialect the package was written in.
   * </pre>
   *
   * <code>.ai.stigmer.agentic.plugin.v1.PluginDialect dialect = 9 [json_name = "dialect"];</code>
   * @return The dialect.
   */
  ai.stigmer.agentic.plugin.v1.PluginDialect getDialect();
}
