// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ai/stigmer/iam/v1/enum.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IamPermission defines the permissions checked by the authorization
// interceptor before an RPC handler executes.
//
// Each value maps to an FGA permission name (a computed relation derived
// from roles). Permissions are never directly assigned to principals —
// they are granted implicitly through role assignments.
//
// For assignable roles, see IamRole below.
// For structural FGA relations (organization, session, agent, etc.),
// those are internal wiring and not represented in this enum.
type IamPermission int32

const (
	IamPermission_unspecified IamPermission = 0
	// Standard CRUD permissions.
	IamPermission_can_view   IamPermission = 1
	IamPermission_can_edit   IamPermission = 2
	IamPermission_can_delete IamPermission = 3
	// Access management permissions.
	IamPermission_can_grant_access IamPermission = 4
	IamPermission_can_view_access  IamPermission = 5
	// Whether the caller may grant, revoke or remove the owner role on an
	// organization: only its owners hold it.
	IamPermission_can_assign_roles IamPermission = 47
	// Whether the caller may change who reaches the resource: its visibility,
	// who observes its runs, a share link to it, or a channel it answers on.
	IamPermission_can_manage_audience IamPermission = 48
	// Organization-level create permissions.
	IamPermission_can_create_agent            IamPermission = 6
	IamPermission_can_create_session          IamPermission = 8
	IamPermission_can_create_skill            IamPermission = 9
	IamPermission_can_create_idp              IamPermission = 11
	IamPermission_can_create_identity_account IamPermission = 21
	IamPermission_can_create_oauth_app        IamPermission = 23
	IamPermission_can_create_platform_client  IamPermission = 24
	// Resource-level create permissions.
	IamPermission_can_create_run_in IamPermission = 13
	// Execution permission.
	IamPermission_can_execute IamPermission = 15
	// Platform-level permissions.
	IamPermission_can_bootstrap_iam IamPermission = 17
	// MCP server connect permission.
	IamPermission_can_connect IamPermission = 22
	// Billing permissions (org-scoped).
	IamPermission_can_view_billing   IamPermission = 27
	IamPermission_can_manage_billing IamPermission = 28
	// Platform-level permission to execute internal billing operations
	// (authorize, record, finalize). Gated to operator (machine account).
	IamPermission_can_execute_billing_ops IamPermission = 29
	// Organization-level permission to create agent shares billed to the
	// organization.
	IamPermission_can_create_agent_share IamPermission = 30
	// Organization-level permission to connect an agent to a messaging
	// channel (Slack, WhatsApp).
	IamPermission_can_create_agent_channel IamPermission = 54
	// Organization-level permission to register channel apps (customer-owned
	// messaging-platform apps holding webhook and OAuth credentials).
	// Admin-gated like can_create_oauth_app.
	IamPermission_can_create_channel_app IamPermission = 31
	// Platform-level permission to view pricing governance and decide
	// pricing-override sign-offs from the pricing feedback loop. A human
	// operator action, kept distinct from can_execute_billing_ops (the
	// machine account's internal billing pipeline).
	IamPermission_can_manage_model_pricing IamPermission = 32
	// Platform-level permission to manage Cursor accounts: the managed
	// Cursor teams (admin keys, member execution keys, org assignments)
	// that back the cursor harness. A human operator action, gated to
	// platform operators like can_manage_model_pricing — key material and
	// per-member spend are platform-internal, never org-visible.
	IamPermission_can_manage_cursor_accounts IamPermission = 35
	// Resource-level permission to participate in an agent channel's
	// conversations: reply to customers as the business, take over and
	// hand back the control token, and clear the attention flag.
	IamPermission_can_participate IamPermission = 36
	// Platform-level permission to introduce or change labels in the
	// reserved stigmer.ai/* key namespace through client-facing write
	// boundaries. Gated to platform operators (the seeding machine
	// account): reserved labels carry platform semantics the server acts
	// on (plugin membership and lineage, the stamps a run's vaults are found by) — so ordinary requests may echo or
	// remove them but never write them.
	IamPermission_can_write_reserved_labels IamPermission = 37
	// Platform-level permission to view platform provider standing: the
	// canary-probe verdicts (health, billing/auth rejections, latency) for
	// the platform's own LLM provider accounts. Read-only and gated to
	// platform operators — provider account health is platform-internal,
	// never org-visible. Deliberately distinct from the manage-class
	// platform permissions: the standing console only observes.
	IamPermission_can_view_provider_standing IamPermission = 38
	// Organization-level permission to install a plugin: push an Agent
	// Plugins archive that the server materialises into skills, MCP servers
	// and an agent in the organization. Distinct from the child
	// kinds' create permissions, which the materialisation also evaluates for
	// the installing caller: who may bring a package into an organization is a
	// policy an administrator sets on its own.
	IamPermission_can_create_plugin IamPermission = 40
	// Platform-level permission to create and retire Plans, the catalog the
	// cloud sells subscriptions and licenses against. A human operator
	// action on the static platform target, kept distinct from
	// can_execute_billing_ops (the machine account's pipeline) the way
	// can_manage_model_pricing is, so an audit line names what happened.
	IamPermission_can_manage_plans IamPermission = 41
	// Platform-level permission to issue and read Licenses: the signed
	// grants of entitlements to self-hosting customers. Every License RPC
	// checks it on the static platform target. Distinct from
	// can_manage_plans because issuing a license to a named customer is a
	// different act, and a different audit line, from editing the catalog.
	IamPermission_can_issue_license IamPermission = 42
	// Organization-level permission to create an MCP server in the
	// organization.
	IamPermission_can_create_mcp_server IamPermission = 43
	// Organization-level permission to create a team in the organization.
	IamPermission_can_create_team IamPermission = 45
	// Platform-level permission to add or remove an organization's credits
	// without a purchase: BillingCommandController.adjustCredits and
	// grantCredits, checked on the static platform target.
	IamPermission_can_manage_credits IamPermission = 46
	// Organization-level permission to create, find and list the
	// organization's child organizations: OrganizationCommandController.create
	// with spec.parent_org naming it, getByExternalId and listChildOrgs.
	IamPermission_can_manage_child_orgs IamPermission = 49
	// Organization-level permission to read the organization itself (its
	// name, slug, description and preferences): OrganizationQueryController.get.
	IamPermission_can_view_settings IamPermission = 50
	// Whether the caller may save logins and secrets in their own My vault in
	// an organization: its members.
	IamPermission_can_create_vault IamPermission = 51
	// Whether the caller may create a shared vault in an organization: its
	// admins.
	IamPermission_can_create_shared_vault IamPermission = 52
	// Whether a person's runs may use a vault's logins and secrets.
	IamPermission_can_use IamPermission = 53
	// Whether the caller may create, list and revoke a service account's API
	// keys: its organization's admins.
	IamPermission_can_manage_keys IamPermission = 55
)

// Enum value maps for IamPermission.
var (
	IamPermission_name = map[int32]string{
		0:  "unspecified",
		1:  "can_view",
		2:  "can_edit",
		3:  "can_delete",
		4:  "can_grant_access",
		5:  "can_view_access",
		47: "can_assign_roles",
		48: "can_manage_audience",
		6:  "can_create_agent",
		8:  "can_create_session",
		9:  "can_create_skill",
		11: "can_create_idp",
		21: "can_create_identity_account",
		23: "can_create_oauth_app",
		24: "can_create_platform_client",
		13: "can_create_run_in",
		15: "can_execute",
		17: "can_bootstrap_iam",
		22: "can_connect",
		27: "can_view_billing",
		28: "can_manage_billing",
		29: "can_execute_billing_ops",
		30: "can_create_agent_share",
		54: "can_create_agent_channel",
		31: "can_create_channel_app",
		32: "can_manage_model_pricing",
		35: "can_manage_cursor_accounts",
		36: "can_participate",
		37: "can_write_reserved_labels",
		38: "can_view_provider_standing",
		40: "can_create_plugin",
		41: "can_manage_plans",
		42: "can_issue_license",
		43: "can_create_mcp_server",
		45: "can_create_team",
		46: "can_manage_credits",
		49: "can_manage_child_orgs",
		50: "can_view_settings",
		51: "can_create_vault",
		52: "can_create_shared_vault",
		53: "can_use",
		55: "can_manage_keys",
	}
	IamPermission_value = map[string]int32{
		"unspecified":                 0,
		"can_view":                    1,
		"can_edit":                    2,
		"can_delete":                  3,
		"can_grant_access":            4,
		"can_view_access":             5,
		"can_assign_roles":            47,
		"can_manage_audience":         48,
		"can_create_agent":            6,
		"can_create_session":          8,
		"can_create_skill":            9,
		"can_create_idp":              11,
		"can_create_identity_account": 21,
		"can_create_oauth_app":        23,
		"can_create_platform_client":  24,
		"can_create_run_in":           13,
		"can_execute":                 15,
		"can_bootstrap_iam":           17,
		"can_connect":                 22,
		"can_view_billing":            27,
		"can_manage_billing":          28,
		"can_execute_billing_ops":     29,
		"can_create_agent_share":      30,
		"can_create_agent_channel":    54,
		"can_create_channel_app":      31,
		"can_manage_model_pricing":    32,
		"can_manage_cursor_accounts":  35,
		"can_participate":             36,
		"can_write_reserved_labels":   37,
		"can_view_provider_standing":  38,
		"can_create_plugin":           40,
		"can_manage_plans":            41,
		"can_issue_license":           42,
		"can_create_mcp_server":       43,
		"can_create_team":             45,
		"can_manage_credits":          46,
		"can_manage_child_orgs":       49,
		"can_view_settings":           50,
		"can_create_vault":            51,
		"can_create_shared_vault":     52,
		"can_use":                     53,
		"can_manage_keys":             55,
	}
)

func (x IamPermission) Enum() *IamPermission {
	p := new(IamPermission)
	*p = x
	return p
}

func (x IamPermission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IamPermission) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_stigmer_iam_v1_enum_proto_enumTypes[0].Descriptor()
}

func (IamPermission) Type() protoreflect.EnumType {
	return &file_ai_stigmer_iam_v1_enum_proto_enumTypes[0]
}

func (x IamPermission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IamPermission.Descriptor instead.
func (IamPermission) EnumDescriptor() ([]byte, []int) {
	return file_ai_stigmer_iam_v1_enum_proto_rawDescGZIP(), []int{0}
}

// IamRole defines the roles that can be assigned to principals on resources
// via IAM policies.
//
// Roles are human-assigned and represent a principal's relationship to a
// resource. They are distinct from permissions (which are computed from roles
// and checked by the authorization interceptor) and structural relations
// (which are internal FGA wiring like organization or session links).
//
// Each ApiResourceKind declares which of these roles are grantable via
// the grantable_roles field in its AuthorizationConfig, and what each one
// means there in role_descriptions.
type IamRole int32

const (
	IamRole_iam_role_unspecified IamRole = 0
	// Full control of the resource. Typically assigned to the creator.
	IamRole_owner IamRole = 1
	// Administrative access. Grants most permissions except ownership transfer.
	IamRole_admin IamRole = 2
	// Membership-level access. Grants read and limited write permissions.
	IamRole_member IamRole = 3
	// Read-only access to the resource.
	IamRole_viewer IamRole = 4
	// A person who takes part in a conversation: reads it and sends messages.
	// On a conversation (session), a participant's messages run in the
	// conversation's own workspace, as its creator, using only the vaults the
	// conversation names; stopping and approving stay with its owners. On an
	// agent channel, a participant reads the channel's conversations and
	// speaks to its customers as the business (reply, take over, hand back,
	// clear attention), and is not a channel configurator.
	IamRole_participant IamRole = 5
	// Editor of a blueprint (an agent or an MCP server): may change
	// its definition and do whatever a viewer can, and may not delete it,
	// change its visibility, publish it on a share link or a channel, or decide
	// who else has access.
	IamRole_editor IamRole = 6
	// May use a shared vault: the runs of a person who holds it use the
	// vault's logins and secrets. Shown as "Can use".
	IamRole_user IamRole = 7
)

// Enum value maps for IamRole.
var (
	IamRole_name = map[int32]string{
		0: "iam_role_unspecified",
		1: "owner",
		2: "admin",
		3: "member",
		4: "viewer",
		5: "participant",
		6: "editor",
		7: "user",
	}
	IamRole_value = map[string]int32{
		"iam_role_unspecified": 0,
		"owner":                1,
		"admin":                2,
		"member":               3,
		"viewer":               4,
		"participant":          5,
		"editor":               6,
		"user":                 7,
	}
)

func (x IamRole) Enum() *IamRole {
	p := new(IamRole)
	*p = x
	return p
}

func (x IamRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IamRole) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_stigmer_iam_v1_enum_proto_enumTypes[1].Descriptor()
}

func (IamRole) Type() protoreflect.EnumType {
	return &file_ai_stigmer_iam_v1_enum_proto_enumTypes[1]
}

func (x IamRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IamRole.Descriptor instead.
func (IamRole) EnumDescriptor() ([]byte, []int) {
	return file_ai_stigmer_iam_v1_enum_proto_rawDescGZIP(), []int{1}
}

// Metadata for one IamRole value.
type IamRoleMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The role's name as people read it ("Admin", "Can use").
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// What the role means when no resource kind is known. A picker shows the
	// kind's own sentence instead (AuthorizationConfig.role_descriptions).
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IamRoleMeta) Reset() {
	*x = IamRoleMeta{}
	mi := &file_ai_stigmer_iam_v1_enum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IamRoleMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IamRoleMeta) ProtoMessage() {}

func (x *IamRoleMeta) ProtoReflect() protoreflect.Message {
	mi := &file_ai_stigmer_iam_v1_enum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IamRoleMeta.ProtoReflect.Descriptor instead.
func (*IamRoleMeta) Descriptor() ([]byte, []int) {
	return file_ai_stigmer_iam_v1_enum_proto_rawDescGZIP(), []int{0}
}

func (x *IamRoleMeta) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *IamRoleMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var file_ai_stigmer_iam_v1_enum_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*IamRoleMeta)(nil),
		Field:         91201,
		Name:          "ai.stigmer.iam.v1.role_meta",
		Tag:           "bytes,91201,opt,name=role_meta",
		Filename:      "ai/stigmer/iam/v1/enum.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional ai.stigmer.iam.v1.IamRoleMeta role_meta = 91201;
	E_RoleMeta = &file_ai_stigmer_iam_v1_enum_proto_extTypes[0]
)

var File_ai_stigmer_iam_v1_enum_proto protoreflect.FileDescriptor

const file_ai_stigmer_iam_v1_enum_proto_rawDesc = "" +
	"\n" +
	"\x1cai/stigmer/iam/v1/enum.proto\x12\x11ai.stigmer.iam.v1\x1a google/protobuf/descriptor.proto\"R\n" +
	"\vIamRoleMeta\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription*\xdd\n" +
	"\n" +
	"\rIamPermission\x12\x0f\n" +
	"\vunspecified\x10\x00\x12\f\n" +
	"\bcan_view\x10\x01\x12\f\n" +
	"\bcan_edit\x10\x02\x12\x0e\n" +
	"\n" +
	"can_delete\x10\x03\x12\x14\n" +
	"\x10can_grant_access\x10\x04\x12\x13\n" +
	"\x0fcan_view_access\x10\x05\x12\x14\n" +
	"\x10can_assign_roles\x10/\x12\x17\n" +
	"\x13can_manage_audience\x100\x12\x14\n" +
	"\x10can_create_agent\x10\x06\x12\x16\n" +
	"\x12can_create_session\x10\b\x12\x14\n" +
	"\x10can_create_skill\x10\t\x12\x12\n" +
	"\x0ecan_create_idp\x10\v\x12\x1f\n" +
	"\x1bcan_create_identity_account\x10\x15\x12\x18\n" +
	"\x14can_create_oauth_app\x10\x17\x12\x1e\n" +
	"\x1acan_create_platform_client\x10\x18\x12\x15\n" +
	"\x11can_create_run_in\x10\r\x12\x0f\n" +
	"\vcan_execute\x10\x0f\x12\x15\n" +
	"\x11can_bootstrap_iam\x10\x11\x12\x0f\n" +
	"\vcan_connect\x10\x16\x12\x14\n" +
	"\x10can_view_billing\x10\x1b\x12\x16\n" +
	"\x12can_manage_billing\x10\x1c\x12\x1b\n" +
	"\x17can_execute_billing_ops\x10\x1d\x12\x1a\n" +
	"\x16can_create_agent_share\x10\x1e\x12\x1c\n" +
	"\x18can_create_agent_channel\x106\x12\x1a\n" +
	"\x16can_create_channel_app\x10\x1f\x12\x1c\n" +
	"\x18can_manage_model_pricing\x10 \x12\x1e\n" +
	"\x1acan_manage_cursor_accounts\x10#\x12\x13\n" +
	"\x0fcan_participate\x10$\x12\x1d\n" +
	"\x19can_write_reserved_labels\x10%\x12\x1e\n" +
	"\x1acan_view_provider_standing\x10&\x12\x15\n" +
	"\x11can_create_plugin\x10(\x12\x14\n" +
	"\x10can_manage_plans\x10)\x12\x15\n" +
	"\x11can_issue_license\x10*\x12\x19\n" +
	"\x15can_create_mcp_server\x10+\x12\x13\n" +
	"\x0fcan_create_team\x10-\x12\x16\n" +
	"\x12can_manage_credits\x10.\x12\x19\n" +
	"\x15can_manage_child_orgs\x101\x12\x15\n" +
	"\x11can_view_settings\x102\x12\x14\n" +
	"\x10can_create_vault\x103\x12\x1b\n" +
	"\x17can_create_shared_vault\x104\x12\v\n" +
	"\acan_use\x105\x12\x13\n" +
	"\x0fcan_manage_keys\x107\"\x04\b\x0e\x10\x0e\"\x04\b\a\x10\a\"\x04\b\f\x10\f\"\x04\b\x10\x10\x10\"\x04\b\x12\x10\x12\"\x04\b\x14\x10\x14\"\x04\b\x19\x10\x19\"\x04\b\x1a\x10\x1a\"\x04\b!\x10!\"\x04\b\"\x10\"\"\x04\b\n" +
	"\x10\n" +
	"\"\x04\b'\x10'\"\x04\b,\x10,*\x13can_create_instance*\x13can_create_workflow*\x16can_create_environment*\x10can_read_secrets*\x1ccan_manage_identity_accounts*\x14login_to_back_office*\x11can_create_runner*\x12can_delete_session*\x0fcan_use_records*\x14can_create_datastore*\x12can_create_project*\x19can_set_public_visibility*\x19can_create_agent_instance*\xb7\x04\n" +
	"\aIamRole\x12\x18\n" +
	"\x14iam_role_unspecified\x10\x00\x12U\n" +
	"\x05owner\x10\x01\x1aJ\x8a\xc4,F\n" +
	"\x05Owner\x12=Everything, including deleting it and deciding who has access\x12P\n" +
	"\x05admin\x10\x02\x1aE\x8a\xc4,A\n" +
	"\x05Admin\x128Manage the organization's people, settings and resources\x12B\n" +
	"\x06member\x10\x03\x1a6\x8a\xc4,2\n" +
	"\x06Member\x12(Belongs to it and holds what it is given\x123\n" +
	"\x06viewer\x10\x04\x1a'\x8a\xc4,#\n" +
	"\x06Viewer\x12\x19Read it; cannot change it\x12L\n" +
	"\vparticipant\x10\x05\x1a;\x8a\xc4,7\n" +
	"\vParticipant\x12(Read the conversations and send messages\x12V\n" +
	"\x06editor\x10\x06\x1aJ\x8a\xc4,F\n" +
	"\x06Editor\x12<Change and use it; cannot delete it or decide who has access\x12J\n" +
	"\x04user\x10\a\x1a@\x8a\xc4,<\n" +
	"\aCan use\x121Use this vault's logins and secrets in their runs:`\n" +
	"\trole_meta\x12!.google.protobuf.EnumValueOptions\x18\xc1\xc8\x05 \x01(\v2\x1e.ai.stigmer.iam.v1.IamRoleMetaR\broleMetaB\xcb\x01\n" +
	"\x15com.ai.stigmer.iam.v1B\tEnumProtoP\x01Z@github.com/stigmer/stigmer/apis/stubs/go/ai/stigmer/iam/v1;iamv1\xa2\x02\x03ASI\xaa\x02\x11Ai.Stigmer.Iam.V1\xca\x02\x11Ai\\Stigmer\\Iam\\V1\xe2\x02\x1dAi\\Stigmer\\Iam\\V1\\GPBMetadata\xea\x02\x14Ai::Stigmer::Iam::V1b\x06proto3"

var (
	file_ai_stigmer_iam_v1_enum_proto_rawDescOnce sync.Once
	file_ai_stigmer_iam_v1_enum_proto_rawDescData []byte
)

func file_ai_stigmer_iam_v1_enum_proto_rawDescGZIP() []byte {
	file_ai_stigmer_iam_v1_enum_proto_rawDescOnce.Do(func() {
		file_ai_stigmer_iam_v1_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_stigmer_iam_v1_enum_proto_rawDesc), len(file_ai_stigmer_iam_v1_enum_proto_rawDesc)))
	})
	return file_ai_stigmer_iam_v1_enum_proto_rawDescData
}

var file_ai_stigmer_iam_v1_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ai_stigmer_iam_v1_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_stigmer_iam_v1_enum_proto_goTypes = []any{
	(IamPermission)(0),                    // 0: ai.stigmer.iam.v1.IamPermission
	(IamRole)(0),                          // 1: ai.stigmer.iam.v1.IamRole
	(*IamRoleMeta)(nil),                   // 2: ai.stigmer.iam.v1.IamRoleMeta
	(*descriptorpb.EnumValueOptions)(nil), // 3: google.protobuf.EnumValueOptions
}
var file_ai_stigmer_iam_v1_enum_proto_depIdxs = []int32{
	3, // 0: ai.stigmer.iam.v1.role_meta:extendee -> google.protobuf.EnumValueOptions
	2, // 1: ai.stigmer.iam.v1.role_meta:type_name -> ai.stigmer.iam.v1.IamRoleMeta
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_stigmer_iam_v1_enum_proto_init() }
func file_ai_stigmer_iam_v1_enum_proto_init() {
	if File_ai_stigmer_iam_v1_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_stigmer_iam_v1_enum_proto_rawDesc), len(file_ai_stigmer_iam_v1_enum_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_ai_stigmer_iam_v1_enum_proto_goTypes,
		DependencyIndexes: file_ai_stigmer_iam_v1_enum_proto_depIdxs,
		EnumInfos:         file_ai_stigmer_iam_v1_enum_proto_enumTypes,
		MessageInfos:      file_ai_stigmer_iam_v1_enum_proto_msgTypes,
		ExtensionInfos:    file_ai_stigmer_iam_v1_enum_proto_extTypes,
	}.Build()
	File_ai_stigmer_iam_v1_enum_proto = out.File
	file_ai_stigmer_iam_v1_enum_proto_goTypes = nil
	file_ai_stigmer_iam_v1_enum_proto_depIdxs = nil
}
