name: release.buf

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push-to-bsr:
    name: Push to Buf Schema Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint protos
        working-directory: apis
        run: buf lint

      - name: Push to BSR
        working-directory: apis
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: buf push
