load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "sdk",
    srcs = [
        "agentcalltaskconfig.go",
        "callactivitytaskconfig.go",
        "forktaskconfig.go",
        "fortaskconfig.go",
        "grpccalltaskconfig.go",
        "helpers.go",
        "httpcalltaskconfig.go",
        "listentaskconfig.go",
        "raisetaskconfig.go",
        "runtaskconfig.go",
        "settaskconfig.go",
        "switchtaskconfig.go",
        "trytaskconfig.go",
        "waittaskconfig.go",
    ],
    importpath = "github.com/stigmer/stigmer/docs/sdk",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_stigmer_stigmer_sdk_go//gen/types",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_google_protobuf//types/known/structpb",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
