apiVersion: kubernetes.project-planton.org/v1
kind: KubernetesDeployment
metadata:
  name: stigmer-web
  env: prod
  labels:
    pulumi.project-planton.org/stack.name: prod.KubernetesDeployment.stigmer-web
spec:
  namespace:
    value: stigmer-prod
  container:
    app:
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 20m
          memory: 32Mi
      env:
        variables:
          - name: NEXT_PUBLIC_API_URL
            value: $variables-group/stigmer-web-config/prod.api-url
          - name: NEXT_PUBLIC_AUTH_MODE
            value: $variables-group/stigmer-web-config/prod.auth-mode
          - name: NEXT_PUBLIC_OIDC_ISSUER
            value: $variables-group/stigmer-web-config/prod.oidc-issuer
          - name: NEXT_PUBLIC_OIDC_CLIENT_ID
            value: $variables-group/stigmer-web-config/prod.oidc-client-id
          - name: NEXT_PUBLIC_OIDC_AUDIENCE
            value: $variables-group/stigmer-web-config/prod.oidc-audience
  ingress:
    enabled: true
    hostname: app.stigmer.ai
